### ISSUE TITLE
Typescript typings

### ISSUE THREAD

**Issue by jog1t** [KubeJS-Mods/KubeJS#10]
It will be very cool if this mod provide Typescript typings for exposed apis. It will help in writing reliable scripts.

Adding support to custom library in IDEs:
- WebStorm: https://www.jetbrains.com/help/webstorm/configuring-javascript-libraries.html

I can volunteer for that feature :)

**Comment by DonovanDMC** [comment]
I'd definitely be up to helping with this, it's pretty hard to go over the documentation and pull it from there. I've started kind of doing that to see how far I can get without delving into the Java code itself and sifting through that. 
https://github.com/DonovanDMC/KubeJSTypings/blob/master/index.d.ts

**Comment by mkaito** [comment]
This looks like it could perhaps be helpful https://github.com/bsorrentino/java2typescript

**Comment by LatvianModder** [comment]
This hasn't been forgotten, but it will be a while before this happens officially. The idea is that both online docs and typings will be generated automatically from docs github repo

**Comment by MaxNeedsSnacks** [comment]
I'd like to merge this (and other documentation-related issues) into the discussion thread for documentation in KubeJS, feel free to contribute with your opinions there, as well!

 https://github.com/KubeJS-Mods/KubeJS/discussions/113
