### ISSUE TITLE
Check if item exists for a recipe

### ISSUE THREAD

**Issue by pjlasl** [KubeJS-Mods/KubeJS#104]
I know I can check if a mod exists using Platform.isLoaded, but is there a way to check if a particular item is registered? 
If the item exists I would like to create a recipe with it, if not, bypass it.

Any help would be appreciated.

**Comment by MaxNeedsSnacks** [comment]
You can use Item.exists(id) for that

**Comment by pjlasl** [comment]
Perfect, Thanks!
