### ISSUE TITLE
Block Registery doesn't opaque() does not set the block to opaque

### ISSUE THREAD

**Issue by hotdog95** [KubeJS-Mods/KubeJS#108]
When registering a block, calling .opaque(false) does not set the block to transparent. 

Similarly .notSolid() has no function, the block is still solid.

After looking at the code I have found that the createProperties method does not use the opaque boolean to set up a transparent property. I have no idea why properties.noOcclusion() does not work

**Comment by MaxNeedsSnacks** [comment]
Is this still an issue? I couldn't reproduce this

**Comment by Spiker985** [comment]
@hotdog95 Is this still an issue? We'll close this in 3 days if no response is given.
