### ISSUE TITLE
breaks IE treated wood recipe

### ISSUE THREAD

**Issue by Darkere** [KubeJS-Mods/KubeJS#11]
From the debug log:

`Parsing error loading recipe immersiveengineering:crafting/treated_wood_horizontal: Shaped recipe ingredient {"amount":1000,"fluid":"immersiveengineering:creosote","type":"immersiveengineering:fluid"} with key 'b' is not a valid ingredient!`

Adding KubeJS to IE makes the recipe disappear.

**Comment by Snownee** [comment]
Can confirm this for my shapeless recipe as well

**Comment by NillerMedDild** [comment]
Fixed by #14
