### ISSUE TITLE
mob spawning 

### ISSUE THREAD

**Issue by benbenlaw** [KubeJS-Mods/KubeJS#112]
ok so i done more testing and it seem that the "monster" category does not work correctly it ignores the light level. Monster still only spawn at night but do no follow light level rules
spawning it max light at night
![image](https://user-images.githubusercontent.com/42780877/113570584-92b45d80-960c-11eb-8b1b-4b4baac987e3.png)

**Comment by Spiker985** [comment]
@benbenlaw Hey, can you provide some more context for this? I'm guessing this was a Discord to GH "better keep track of this" type thing?
