### ISSUE TITLE
lava type fluids

### ISSUE THREAD

**Issue by najlitarvan** [KubeJS-Mods/KubeJS#115]
we can make fluids based on water texture, any chance we might lava based fluids?
texture(the color of the fuid overlayed on top of the animated lava texture

**Comment by MaxNeedsSnacks** [comment]
Already possible, this is known as a fluid with a thick texture (https://github.com/KubeJS-Mods/KubeJS/blob/master/common/src/main/resources/assets/kubejs/textures/fluid/fluid_thick.png)

Possible ways to achieve this include either using `fluid.textureStill("kubejs:fluid/fluid_thick")` and `fluid.textureFlowing("kubejs:fluid/fluid_thick_flow")` or just using this method directly if you want to tint the fluid as well:

https://github.com/KubeJS-Mods/KubeJS/blob/d6cedd9727c1da2563c0fea4905a43242394f5b5/common/src/main/java/dev/latvian/kubejs/fluid/FluidBuilder.java#L73

**Comment by najlitarvan** [comment]
sry and thank you

**Comment by MaxNeedsSnacks** [comment]
Absolutely no worries, and feel free to ask more questions in our [Discord](https://discord.gg/bPFfH6P) or over in the [Discussions tab](https://github.com/KubeJS-Mods/KubeJS/discussions/categories/script) if you need anything else!
