### ISSUE TITLE
Loot tables question

### ISSUE THREAD

**Issue by pjlasl** [KubeJS-Mods/KubeJS#118]
Where do I add a loot table script to?
startup or server?

I would like to use KubeJS for my minor loot table changes and not have to bring in something like OpenLoader.

**Comment by MaxNeedsSnacks** [comment]
Loot Tables should go into the **server** scripts, but keep in mind right now only **block** loot tables are supported (though you can edit ANY loot table .json by using the `kubejs/data` folder (which *would* basically be a virtual datapack like you have with OpenLoader)
