### ISSUE TITLE
Ice and Fire Dragonforge

### ISSUE THREAD

**Issue by ghost** [KubeJS-Mods/KubeJS#119]
Is it possible to modify recipes for the Ice and Fire dragonforge using KubeJS? I am working on a modpack and want to be able to modify crafting recipes for items from the dragonforge without having to use CraftTweaker.

**Comment by sciguyryan** [comment]
I could be wrong, but as far as I can see it is not possible. They do not have a recipe type via which recipes can be passed.

They have some compatibility code for CraftTweaker, they could provide something similar for KubeJS, or modify things to work via the conventional methods.

**Comment by SonicSpeedster16** [comment]
That was my suspicion as well; thank you for your input. Is adding KubeJS support something I should bring up with the Ice and Fire devs?

**Comment by Spiker985** [comment]
You can try using `event.printTypes()` to see if there are any Ice and Fire recipe handlers, and then use `event.printExamples('<type from printTypes()>')` to get JSON examples that you can then tweak for `event.custom()`

**Comment by SonicSpeedster16** [comment]
Thank you, but I'm not sure how to go about doing that for sure (I have only ever used CraftTweaker before and have essentially zero JavaScripting knowledge)

**Comment by Spiker985** [comment]
Come join us in the Discord, it'll probably be easier to work through. https://discord.gg/bPFfH6P

Or if you don't have a Discord account, you can take a look at the Wiki, https://kubejs.com/, and see if you can gleam how things work.

**Comment by sciguyryan** [comment]
> 
> 
> You can try using `event.printTypes()` to see if there are any Ice and Fire recipe handlers, and then use `event.printExamples('<type from printTypes()>')` to get JSON examples that you can then tweak for `event.custom()`

I actually decided to go poking around the I&F GitHub. Unfortunately there does not seem to be a recipe type to reference, or at least none I could find:

https://github.com/Alex-the-666/Ice_and_Fire/search?q=DragonForgeRecipe

There is a DragonForgeRecipe class, though no recipe type with which to use with event.custom. I am guessing that is why they decided to bake CT compatibly directly.

**Comment by SonicSpeedster16** [comment]
Thanks @Spiker985 The wiki has definitely been helpful for some things but I couldn't seem to find any specific info regarding the `event.printTypes()` or the `event.custom` I'll check out the Discord at some point.

@sciguyryan I also poked around and found the DragonForge class but couldn't find a recipe type for it anywhere. Thanks for checking!

**Comment by sciguyryan** [comment]
> @sciguyryan I also poked around and found the DragonForge class but couldn't find a recipe type for it anywhere. Thanks for checking!

No problem. Hopefully the author would be amenable to adding some form of API that KubeJS can use. This is something I would be interested in too.

**Comment by MaxNeedsSnacks** [comment]
As you guys already figured out, this *may* be a bit of a pain considering Ice And Fire's dragonforge does not use a recipe type, however I'd love to work together with the mod author to introduce KubeJS integration where possible, anyways. Maybe Dragonforge recipes could just be under a separate event since they are just a public static Map...?

**Comment by SonicSpeedster16** [comment]
I just opened an issue on Ice and Fire's suggestion repo regarding this.

**Comment by Spiker985** [comment]
Added "help wanted" label since this issue requires a change from a 3rd party. Feel free to close, or remove if you feel that this is invalid.

**Comment by MaxNeedsSnacks** [comment]
Original GitHub user that requested this no longer exists, and the suggestion seems to have been ignored / left standing on the IaF tracker

**Comment by caioBB** [comment]
> I just opened an issue on Ice and Fire's suggestion repo regarding this: [AlexModGuy/Ice-and-Fire-Suggestions#1093](https://github.com/AlexModGuy/Ice-and-Fire-Suggestions/issues/1093)

 event.custom({
    type: 'iceandfire:dragonforge',
    dragon_type: 'fire',
    cook_time: 1000,
    input: {
        tag: 'forge:ingots/netherite'
    },
    blood: {
        item: 'iceandfire:fire_dragon_blood'
    },
    result: {
        item: 'iceandfire:dragonsteel_fire_ingot'
    }
})

try this
