### ISSUE TITLE
1.16+ does not support “command.registry”. Is there an alternative？

### ISSUE THREAD

**Issue by WangJiangJiaoZi** [KubeJS-Mods/KubeJS#123]
Need a new version of the basic registration command method

**Comment by MaxNeedsSnacks** [comment]
A new command registry method is planned, however due to how different registering commands is in 1.13+ it's been on the backburner for quite some time now (since we have to deal with an external library `Brigadier` and class that have only *sometimes* obfuscated methods and such)

**Comment by MaxNeedsSnacks** [comment]
This has been implemented in 1.18+ a while ago ^^
