### ISSUE TITLE
[Request] Adding hidden recipes

### ISSUE THREAD

**Issue by NillerMedDild** [KubeJS-Mods/KubeJS#125]
It would be very helpful to be able to add recipes that are hidden in JEI.

A `.hide()` at the end of a recipe so it doesn't register in JEI would be perfect

**Comment by MaxNeedsSnacks** [comment]
There's now a client event for this: `jei.yeet.recipes` (analogous to our one for categories)

See https://github.com/KubeJS-Mods/KubeJS/blob/master/forge/src/main/java/dev/latvian/kubejs/integration/jei/YeetJEIRecipesEvent.java for more info ^^

**Comment by NillerMedDild** [comment]
Thank you :D
