### ISSUE TITLE
[1.16.5] Adding a tag to all items with a specific tag, then removing it from items with ANOTHER tag doesn't actually remove it

### ISSUE THREAD

**Issue by aaronhowser1** [KubeJS-Mods/KubeJS#127]
```js
onEvent('item.tags', tag => {
    tag.add("ftbuniversity:etech_generate_flowers", "#minecraft:flowers")
    tag.remove("ftbuniversity:etech_generate_flowers", "#botania:special_flowers")
})
```
![image](https://user-images.githubusercontent.com/15698722/117365149-7c582680-ae84-11eb-8fb0-13e42a547db5.png)

**Comment by aaronhowser1** [comment]
This also doesn't work:
```js
onEvent('item.tags', tag => {
    tag.add("ftbuniversity:etech_generate_flowers", "#minecraft:flowers")
    tag.remove("ftbuniversity:etech_generate_flowers", [
        "#botania:special_flowers",
        "byg:pollen_block"
    ])
})
```

![image](https://user-images.githubusercontent.com/15698722/117365779-6b5be500-ae85-11eb-99ef-232c697c2cce.png)

**Comment by MaxNeedsSnacks** [comment]
We have decided against implementing this explicitly. Tags are only ever meant to be added to in Vanilla, and if you *do* want to remove from tags recursively, we can just add a method to get all the **current** items along with their sources
