### ISSUE TITLE
[1.15.2] Game Crash with kubejs-2.7.0.41.jar

### ISSUE THREAD

**Issue by realTIMematrix** [KubeJS-Mods/KubeJS#13]
Hi,

I'm using:

- Forge 31.2.22
- kubejs-2.7.0.41.jar
- ftb-quests-2.0.2.246.jar

Error: Failed to create mod instance. ModID: ftbquests, class com.feed_the_beast.ftbquests.FTBQuests
java.lang.BootstrapMethodError: java.lang.NoClassDefFoundError: dev/latvian/kubejs/documentation/DocumentationEvent

if I'm using kubejs-2.6.2.40.jar this works fine in this pack

[latest.log](https://pastebin.com/PnQhhkyC)

[crash.txt](https://pastebin.com/TrebuWCc)

[Minecraft Game Output](https://pastebin.com/8gf42183)

**Comment by NillerMedDild** [comment]
This issue has now been fixed :)
