### ISSUE TITLE
Ore generation ore.squared offsets every ore by the same amount

### ISSUE THREAD

**Issue by Kubius** [KubeJS-Mods/KubeJS#136]
Essentially what the title says; when generating custom ores, no matter the height or cluster count, each chunk's ore of a given type will generate in a single pillar. Disabling ore.squared causes the pillar to appear at one corner of the chunk, as would be expected.

My suspicion is that the problem is in (or one file away from) WorldgenAddEventJS, lines 77-90 - the squared function seems to be applied to all of the clusters at the same time, instead of individually.

KubeJS version: 1605.3.7-build.186-forge

**Comment by Spiker985** [comment]
Marking as duplicate because #205 has more information and is newer. Please follow that issue for further updates.
