### ISSUE TITLE
Recipes in Advanced Rocketry machines

### ISSUE THREAD

**Issue by Freebi85** [KubeJS-Mods/KubeJS#139]
Hey there^^ 
Just noticed an issue with AR. It's not possible to remove default recipes from Advanced Rocketery machines like the Crystallizer or Cutting machine. Neither with output nor by ID although it has one.
Forge: 36.1.25
KubeJS: 1605.3.10 build18
![image](https://user-images.githubusercontent.com/42634622/120873669-59b04f00-c5a3-11eb-8161-9faa6b9c9e7b.png)

Cheers 🍺

**Comment by MaxNeedsSnacks** [comment]
We can't fix this without explicit integration because they circumvent the RecipeManager entirely (that Recipe ID you see there is never even visible to us)
