### ISSUE TITLE
Crafting recipes with Enchanted Books are uncraftable

### ISSUE THREAD

**Issue by DAmNRelentless** [KubeJS-Mods/KubeJS#140]
### Description
Currently, if you add recipes which include Enchanted Books, are uncraftable.
It doesn't matter if the enchantment on the book is by a mod or from Vanilla.

You can create the recipe and in JEI, it will display just fine. You can also quick-move the items into the crafting slots with JEI's `+` button but there is no output showing up.
I was able to reproduce this with just Kube installed.

In our modpack (All the Mods 6), we also have Create and when using the Mechanical Crafters to do it, the recipe is starting to process and then all the ingredients will just pop out close before it's done.
Seems like the recipes are not actually valid.

We tried it with this:
```
Item.of('minecraft:enchanted_book').enchant('minecraft:efficiency', 5)
```
And we also tried it with the direct reference of the nbt:
```
Item.of('minecraft:enchanted_book', {StoredEnchantments:[{lvl:5,id:"minecraft:efficiency"}]})
```
None of those work. The nbt data was retrieved with `/kubejs hand`.

### Versions:
Minecraft: 1.16.5
Loader: Forge
Forge-Version: 36.1.31
KubeJS: 1605.3.10-build.25
Rhino: 1605.1.1-build.14
Architectury: 1.17.22-forge

**Comment by MaxNeedsSnacks** [comment]
Is this still an issue in later versions? Might be related to Create / KJS Create

**Comment by DAmNRelentless** [comment]
This also happened with just KubeJS without the Create addon.

**Comment by MaxNeedsSnacks** [comment]
Right, so this also happens in the latest KubeJS? Lat messed with NBT recently, so this might have been fixed already

**Comment by Spiker985** [comment]
@DAmNRelentless Can you validate this issue still exists?

**Comment by DAmNRelentless** [comment]
Works with just KubeJS installed now.
