### ISSUE TITLE
feature request: Villager trades

### ISSUE THREAD

**Issue by pm065** [KubeJS-Mods/KubeJS#141]
For some enigmatic, mysterious reason, Mojang apparently decided not to make villager trades a recipe type.
This feature is literally the only reason I still use CraftTweaker at all, putting everything else in KubeJS scripts.

So: would it be possible to implement villager trades? I'm guessing it would require more than simple integration since it isn't a recipe type.

Other than that, KJS is incredibly useful for modpacks, thank you for making it!

**Comment by MaxNeedsSnacks** [comment]
Duplicate of #20
