### ISSUE TITLE
Trying to add a new campfire recipe

### ISSUE THREAD

**Issue by Tandryan33** [KubeJS-Mods/KubeJS#142]
As title says, I'm trying to add a new recipe to cook some flesh into leather, but I can't find what event I should use to add a campfire one, tried both with `event.campfire(output, input)` and with `event.campfire_cooking(output, input)` but still doesn't work.

**Comment by MaxNeedsSnacks** [comment]
It's `event.campfireCooking`, so you were close

**Comment by Tandryan33** [comment]
> It's `event.campfireCooking`, so you were close

Well, I'll be damned... and thanks you!

**Comment by pm065** [comment]
Actually, it does seem like the wiki page for RecipeEventJS is missing an example for campfire cooking, though it says in the comment above the smoker/blaster recipes that it has one. Maybe that should be added? This confused me too at one point.

**Comment by Tandryan33** [comment]
> Actually, it does seem like the wiki page for RecipeEventJS is missing an example for campfire cooking, though it says in the comment above the smoker/blaster recipes that it has one. Maybe that should be added? This confused me too at one point.

Exactly that's why I came here to ask help, I didn't found anything like a list of every commands available. 
The wiki tells you some and you have to find out the rest of it.

**Comment by pm065** [comment]
> > Actually, it does seem like the wiki page for RecipeEventJS is missing an example for campfire cooking, though it says in the comment above the smoker/blaster recipes that it has one. Maybe that should be added? This confused me too at one point.
> 
> Exactly that's why I came here to ask help, I didn't found anything like a list of every commands available.
> The wiki tells you some and you have to find out the rest of it.

They do admit that there's [a bit of a problem](https://github.com/KubeJS-Mods/KubeJS/discussions/113) with documentation, but are struggling to find the best way to do it going forward.

I personally feel that opening up the wiki to public editing for people signed in to a GitHub account would be best, but either way that discrepancy should probably be corrected in the current system, too.

For the commands: some of them can be found by looking through issues, but not many, though that was how I found out the [syntax of the food() function](https://github.com/KubeJS-Mods/KubeJS/issues/135) for new items.

You might be able to glean some of them by looking in the code, I guess? I haven't been able to figure anything out from there except the parameters of fluid building (some aren't mentioned in the wiki). (EDIT: though I think I may be on to something in figuring out modifying vanilla items from the code!)
