### ISSUE TITLE
[1.17] Changes to items' tags not being applied in-game

### ISSUE THREAD

**Issue by Vichoriz0** [KubeJS-Mods/KubeJS#145]
#### Issue description
I tried to add and remove items from different tags using `item.tags` event, but the scripts didn't work and nothing got added nor removed.

#### What happens: 
Nothing. The log shows no errors related to that script and the changes written on the script weren't applied in-game.
![imagen](https://user-images.githubusercontent.com/39714360/123165463-42e27700-d442-11eb-8c65-a91443ed2fad.png)

#### What you expected to happen:  
Items specified on the script being added and removed from the tags in-game. For example, the item above should include 
`#fabric:tools`, `#fabric:tools/knives`, `#farmersdelight:tools/knives` and `#farmersdelight:straw_harversters`, and also have `#fabric:swords` removed.

#### Script
The script is named `tags.js` and it's located in `kubejs/server_scripts`
```js
onEvent('item.tags', event => {
    ['copper', 'diamond', 'flint', 'golden', 'iron', 'netherite'].forEach(material => {
        if( material === 'copper' || material === 'flint') {
            event.get('fabric:tools').add(`earlygame:${material}_knife`);
            event.get('fabric:tools/knives').add(`earlygame:${material}_knife`);
            event.get('farmersdelight:tools/knives').add(`earlygame:${material}_knife`);
            event.get('farmersdelight:straw_harvesters').add(`earlygame:${material}_knife`);
        }
        if( material !== 'copper' ) {
            event.get('earlygame:knives').add(`farmersdelight:${material}_knife`);
        }
        event.get('fabric:swords').remove(`earlygame:${material}_knife`);
    }); 
});
```
Also tried the syntax shown in the [wiki](https://mods.latvian.dev/books/kubejs/page/tageventjs) but it didn't work either.

#### Environment
- Minecraft 1.17
- Fabric Loader 0.11.6
- Fabric API 0.36.0
- Architectury API 2.0.11
- Rhino 1605.1.1-build.23
- KubeJS 1605.3.10-build.9999

#### KubeJS server log
https://pastebin.com/Gd0y0dzu
(I have no idea where those warnings are coming from. I don't even have some of the mods listed there and haven't touched any one of those with my scripts either)

**Comment by MaxNeedsSnacks** [comment]
Er, we don't currently have a 1.17 branch, so I'm interested to know where you got that from honestly :P

**Comment by MaxNeedsSnacks** [comment]
@shedaniel *angery*

![image](https://user-images.githubusercontent.com/12750501/123170956-6b3a9780-d47b-11eb-9690-6cc0799c35d7.png)

**Comment by Vichoriz0** [comment]
Yea, from that same place. Didn't notice that changelog, sorry :(

**Comment by MaxNeedsSnacks** [comment]
No worries, maybe Dan can fix it up if he finds out what's wrong

**Comment by Spiker985** [comment]
@Vichoriz0 KubeJS 1.17 was released on Alpha and is unsupported. 1.16.5 is the currently long term support version, until 1.18 becomes stable and is migrated to.
