### ISSUE TITLE
prevent correct rendering of other mods

### ISSUE THREAD

**Issue by krakel** [KubeJS-Mods/KubeJS#146]
After some tests I found the mod prevent the correct rendering of encoded patterns of AE2 (at the interface table).

**Comment by MaxNeedsSnacks** [comment]
- In what way does it "prevent correct rendering"?
- What tests did you perform exactly to determine it's KubeJS?
- How can we verify these results ourselves?

**Comment by Spiker985** [comment]
@krakel Can you provide further information regarding this issue? What Minecraft version, KubeJS version, if the issue is still occurring with newer versions?

If by Wednesday 2021-12-08 you haven't responded, we'll consider the issue closed.
