### ISSUE TITLE
feature request: Modify the food values of items

### ISSUE THREAD

**Issue by pm065** [KubeJS-Mods/KubeJS#147]
I did not seem to find anything mentioning food [here](https://github.com/KubeJS-Mods/KubeJS/blob/main/common/src/main/java/dev/latvian/kubejs/mixin/common/ItemMixin.java), which leads me to believe it isn't possible to modify food values yet.

My reasoning is the exact same as anyone else who ever wanted to modify food values somehow:

![cooked_beef](https://user-images.githubusercontent.com/81559564/123503757-ca033b00-d64c-11eb-890d-2ebc4921e269.png)

**Comment by lythowastaken** [comment]
I implemented it. Will do a PR after some more testing.

**Comment by pm065** [comment]
THANK YOU SO MUCH :heart:

**Comment by MaxNeedsSnacks** [comment]
Implemented in https://github.com/KubeJS-Mods/KubeJS/commit/9178615580be64e54b4d4a18cc170b6c0527ec88 ^^
