### ISSUE TITLE
1.16.1 - game crashes at creating world screen

### ISSUE THREAD

**Issue by bessiq** [KubeJS-Mods/KubeJS#15]
MC 1.16.1
Forge 32.0.38-39
kubejs-2.7.0.42.jar

Probably to be expected with a fresh, new Minecraft version, but the game crashes shortly after clicking Create World when KubeJS is enabled. Disabling it allows the world to load normally.

Also, the FML background in newer Forge versions is now an angry red, and the colors in your client.properties no longer seem to override it. I do have FancyMenu installed, but it seems to only affect the Mojang logo, so I think the red is from Forge themselves?

Just wanted to let you know. Thanks!

[crash-2020-07-01_18.58.58-client.txt](https://github.com/KubeJS-Mods/KubeJS/files/4861163/crash-2020-07-01_18.58.58-client.txt)

**Comment by LatvianModder** [comment]
https://jenkins.latmod.com/job/KubeJS/43/

**Comment by bessiq** [comment]
With the new version enabled (2.7.0.43), the game client crashes just after FML early loading - Forge 32.0.63.
[crash-2020-07-11_19.51.57-client.txt](https://github.com/KubeJS-Mods/KubeJS/files/4907783/crash-2020-07-11_19.51.57-client.txt)
[crash-2020-07-11_19.54.28-client.txt](https://github.com/KubeJS-Mods/KubeJS/files/4907784/crash-2020-07-11_19.54.28-client.txt)
