### ISSUE TITLE
[FORGE] recipes cannot output with custom NBT data

### ISSUE THREAD

**Issue by MerrittK** [KubeJS-Mods/KubeJS#152]
Necessary for certain pack ideas.

**Comment by pm065** [comment]
I think this is a vanilla restriction, but I might be thinking of something else

**Comment by MaxNeedsSnacks** [comment]
Which recipe type are you trying to use Item NBT with? It *should* just work on Forge

**Comment by MerrittK** [comment]
I cannot find documentation on how to output nbt. I tried with a json recipe, but I guess it did not work.

**Comment by Spiker985** [comment]
@MerrittK Is this still a problem? The `Item.of('<item name>', {<NBT>})` format should cover this

**Comment by MerrittK** [comment]
Not right now. Forgot about issue. Working on other stuff.
