### ISSUE TITLE
there is no actual documentation in KubeJS's Aurora pages

### ISSUE THREAD

**Issue by JadianRadiator** [KubeJS-Mods/KubeJS#16]
KubeJS's "documentation" in Aurora doesn't actually provide documentation.
It just gives you a source/function map, and no actual documentation.
Absolutely jack-s*** about how to use _anything_.
All it tells you is the names of functions and arguments.
But nothing about what any of it does, nor what they're for.

Edit:
wouldn't be so bad if it had examples, but it doesn't.
Thank goodness for [this documentation](https://mods.latvian.dev/books/kubejs), would have no clue about how to use KubeJS without it.

**Comment by LatvianModder** [comment]
The documentation is being written now in the page you linked
