### ISSUE TITLE
KubeJS disables "Better End" mod's enchanted book recipes (Forge)

### ISSUE THREAD

**Issue by Rute-Of-All-Evil** [KubeJS-Mods/KubeJS#161]
Minecraft Version: 1.16.5

Forge Modloader Version: 36.1.32

KubeJS Version: kubejs-forge-1605.3.10-build.25

Better End Version: betterendforge-1.16.4-1.6.0

When using the Infusion crafting system in Better End, none of the recipes for making Enchanted Books work if KubeJS is also on the mod list. Other recipes in the Infusion system work, it is just specifically the ones for Enchanted Books as far as we've tested. Also made sure it wasn't somehow one of our own KubeJS scripts, it still happened even with no Scripts active what so ever.

**Comment by MaxNeedsSnacks** [comment]
Suspecting this may be the same as #140

**Comment by Spiker985** [comment]
@Rute-Of-All-Evil Suspecting this to be the same as #140 which is no longer a problem on current versions. Feel free to reopen if you believe this to be an error.
