### ISSUE TITLE
Soft crash on resource reload / end of game initialization when Inspecio is installed [1.17 Fabric]

### ISSUE THREAD

**Issue by SebaSphere** [KubeJS-Mods/KubeJS#164]
When the latest [Inspecio build here](https://www.curseforge.com/minecraft/mc-mods/inspecio/files/3343900) is installed with the [latest KubeJS build + dependencies here](https://www.curseforge.com/minecraft/mc-mods/kubejs-fabric/files/3355296), the game will not start.

You can my latest.log file here: https://pastebin.com/3QneEaqk

Every resource reload, the game soft crashes and attempts to load again.

**Comment by SebaSphere** [comment]
I've posted the same issue on the Inspecio github here: https://github.com/Queerbric/Inspecio/issues/16

**Comment by MaxNeedsSnacks** [comment]
They're definitely right, it's a KubeJS issue, however we currently don't plan on supporting 1.17 unfortunately as we still have to maintain 1.16 for existing modpacks and 1.18 seems like a much more attractive version to move to anyways
