### ISSUE TITLE
[Feature Request] Add methods to use different subclass of Block or Item in the registry events,

### ISSUE THREAD

**Issue by erisdev** [KubeJS-Mods/KubeJS#165]
My naive suggestion is to add a method like `.subclass(className: string)` to the block / item builder that looks up the class by its fully qualified name and checks that it's actually a subclass of the appropriate base class. It would be nice to, for instance, add custom "incomplete" items for Create's sequenced assembly recipes, which need to be an instance of [`SequencedAssemblyItem`](https://github.com/Creators-of-Create/Create/blob/mc1.16/dev/src/main/java/com/simibubi/create/content/contraptions/itemAssembly/SequencedAssemblyItem.java) to properly show the progress bar on the item icon. I think allowing arbitrary subclasses is a nice general solution that works for other use cases too.

**Comment by MaxNeedsSnacks** [comment]
Support for item types has been added in the latest version (including the sequenced assembly item in the newest KubeJS Create), block types will probably be done at another point, but should be easy enough as well ^^

**Comment by erisdev** [comment]
Y'all are awesome. How do I use it? I can't find anything in the docs and a cursory glance at the source code hasn't turned up anything obvious yet.
