### ISSUE TITLE
FTB Ranks and player.chat not compatible

### ISSUE THREAD

**Issue by LLjo** [KubeJS-Mods/KubeJS#178]
Installing FTB Ranks and writing a script listening to player.chat doesn't work.

Forge 1.16.5 36.2.0

ftb-ranks-1605.1.4-build.9

kubejs-forge-1605.3.14-build.60

**Comment by MaxNeedsSnacks** [comment]
That is true, since FTB Ranks intercepts the chat event to add its own chat format. We'll have to look into another way to do things most likely, either by changing the event on the Architectury side or manually firing the chat event from Chunks' end

**Comment by Charismara** [comment]
looks like i ran into the same problem on:

Forge 1.18.2-40.1.68
ftb-ranks-forge-1802.1.8-build.34
kubejs-forge-1802.5.4-build.524

**Comment by MichaelHillcox** [comment]
From my side (FTB Mod dev) ranks needs changes anyway so we can likely fire the event after modifying it unless max has a good solution

**Comment by MaxNeedsSnacks** [comment]
Honestly, that sounds good enough to me. The chat event is mostly decoupled from the Architectury / Forge one anyways, so you can just fire the same `player.chat` event on the KubeJS side from FTB Ranks

**Comment by Jetpack-Cat** [comment]
Any kind of eta on this fix?

**Comment by LarcekGiglamesh** [comment]
Can confirm this happening in 1.18.2 as well, using a minimal setup

architectury-4.10.86-forge
ftb-library-forge-1802.3.7-build.154
ftb-ranks-forge-1802.1.8-build.34.jar
kubejs-forge-1802.5.5-build.554
rhino-forge-1802.2.1-build.255

disabling ftb-ranks will fix the issue.

**Comment by LarcekGiglamesh** [comment]
@MichaelHillcox 
would you happen to be able to forward this issue to the devs, or implement your suggestion directly?
