### ISSUE TITLE
[1.16.1] java.lang.NoSuchMethodError

### ISSUE THREAD

**Issue by realTIMematrix** [KubeJS-Mods/KubeJS#18]
Hi,

the game crash with the latest 1.16.1 forge version

Minecraft: 1.16.1
Forge: 32.0.69
kubejs-2.7.0.45.jar
MixinBootstrap-1.0.3.jar

Steps to reproduce:

1. Start game
2. Create new single player game
3. Crash when the game reaches nearly 100% and try to join the world

[crash-server.txt](https://pastebin.com/uifhpbN7)

[latest.log](https://pastebin.com/PyxQJn2L)

**Comment by LatvianModder** [comment]
Fixed in https://www.curseforge.com/minecraft/mc-mods/kubejs/files/3008127
