### ISSUE TITLE
Mod causes Charcoal Pit ore kiln recipes to break

### ISSUE THREAD

**Issue by etroozo** [KubeJS-Mods/KubeJS#183]
Whenever I run kubejs with a mod called [Charcoal Pit](https://www.curseforge.com/minecraft/mc-mods/charcoal-pit#comments), some of the recipes from Charcoal Pit break. Charcoal Pit adds several types of crafting that aren't handled by kubejs, but only the "ore kiln" recipes break as far as I can tell. The unfired pot and all of its unsmelted contents remain after the burn, which isn't supposed to happen. I was wondering if anyone knew anything about this - help is much appreciated.

Forge version: 36.2.0
Kubejs version: 1605.3.15-build.82
Charcoal pit version: 2.13
Minecraft version: 1.16.5

**Comment by ChiefArug** [comment]
1.16 is now EOL and that mod has not updated past 1.16.5 yet so I am going to close this
Side note, pretty sure TFC itself has now updated to modern versions 👀
