### ISSUE TITLE
Recipe removing somewhat broken after 1605.3.15-build.73 

### ISSUE THREAD

**Issue by joseth257** [KubeJS-Mods/KubeJS#184]
remove({output:str}) only works well until build 67. After 73, if an item has multiples recipes, kubejs doesn't seem to remove all of them. 

I noticed it by looking at my ore unifying scripts, ingots still have some of their recipes. Another example was trying to remove quarks variant chests by script, and it only removed one of the available recipes. 

After noticing this, I simple stopped hiding the items removed and had a check, and quite a few recipes are still there, but it seems that the ones that has just one recipe for output is removed normally. Knowing that, I tested and took note that until 67 it was working as I expected.

**Comment by LatvianModder** [comment]
Yup, we noticed too. Its something to do with item nbt comparing, I recently improved performance of, but broke some checks at the same time. I will probably fix it today. TL;DR is some items get internally created with null tag, but some get {} which is empty but not null, so their == fails

**Comment by LatvianModder** [comment]
Updated KJS, try with it. It should fix NBT issues

**Comment by joseth257** [comment]
I tested the newest release and yep, the issues I mentioned are gone, thank you!
