### ISSUE TITLE
Errors on Direwolf20 1.11.0 Update

### ISSUE THREAD

**Issue by Luxuria0411** [KubeJS-Mods/KubeJS#186]
I have pasted the errors and attached my server log file specifically for Kubesjs. It is the only mod I have found that is having issues so far with the update. I was not seeing any other posts that relate to this modpack or issue. I have attached text files with the information regarding both the old and new versions of Direwolf20. I am using the Official Feed-The-Beast Overwolf App for the client side of things. Server is privately hosted on my side. If anyone is willing to help me investigate, I can give server connection information for confirmation of the errors.  

The changes that happened between the server updates are as follows. 
- Update Forge: 36.2.2
- Mods Added:
- catalogue-1.3.0-1.16.5.jar
- configured-1.1.2-1.16.3.jar
- Mods Updated: All Mods were updated please reference the attached text files for complete list or the official website [](https://feed-the-beast.com/modpack/ftb_presents_direwolf20_1_16)
[Direwolf20 version 1.10.1 version id 2055.txt](https://github.com/KubeJS-Mods/KubeJS/files/7033546/Direwolf20.version.1.10.1.version.id.2055.txt) [Direwolf20 version 1.11.0 version id 2067.txt](https://github.com/KubeJS-Mods/KubeJS/files/7033538/Direwolf20.version.1.11.0.version.id.2067.txt)
- Prior Forge: 36.1.23

The errors being experienced are as follows.

- [23:54:48] [ERR ] server_scripts:recipes/create.js:26: - fluids:forge:milk // create:milk [Not found!]
- [23:54:48] [ERR ] server_scripts:recipes/create.js:26: - fluids:forge:milk // create:flowing_milk [Not found!]
- [23:54:49] [ERR ] server_scripts:recipes/ie.js:19: Failed to create recipe for type 'immersiveengineering:metal_press': create:lapis_sheet is not a valid result!

[server.txt](https://github.com/KubeJS-Mods/KubeJS/files/7033479/server.txt)

**Comment by Sunekaer** [comment]
Did you clear the kubejs folder, so it could get the updated scripts?

**Comment by Luxuria0411** [comment]
I did not. I didnt know that was needed. I will give it a shot.

**Comment by Luxuria0411** [comment]
> Did you clear the kubejs folder, so it could get the updated scripts?

Does it need to be server side or client side for the folder clearing?

**Comment by MaxNeedsSnacks** [comment]
I'm no expert but the launcher should automatically clear out the scripts if the pack updates, so probably on the server side

**Comment by MaxNeedsSnacks** [comment]
Can you confirm this works using the updated scripts?
