### ISSUE TITLE
Modify harvest level / required tool type of block

### ISSUE THREAD

**Issue by copygirl** [KubeJS-Mods/KubeJS#189]
I've personally had to change the harvest level of an existing block (zinc ore) and unfortunately could not find a way to do so with KubeJS. Thankfully it was only a single block and did not care about world generation, so I simply made my own block to replace it. A friend now wants to do the same, with multiple ores that are generated in-world, to make them require a higher tool level.

I'm not sure why this was left out in the initial implementation, if there was a reason, or whether it was simple oversight. Essentially, it would be nice to have a `harvestTool(tool, level)` method like we have with the `block.registry` event, but instead on the `block.modification` event.

**Comment by ChiefArug** [comment]
This is now possible in 1.18.2+ as harvest tool types and levels are controlled by tags!
Tool type tags have the format `minecraft:mineable/tool`, like `minecraft:mineable/shovel`
Tier tags have the format `minecraft:needs_tier_tool`, like `minecraft:needs_diamond_tool`. Note forge also has `forge:needs_netherite_tool`.

**Comment by CannibalishToast** [comment]
hey, by any chance do u know how to enforce the right tool to be required for the block to drop an item? Like how stone will only drop itself if mined with a pickaxe, even if its a wooden one (harvest level 0). I know its not KubejS related but this is the best place  I found for asking this specific thing

**Comment by copygirl** [comment]
I looked into this recently because I wanted a tool to be required for cutting trees, and if I'm correct, that's still hardcoded into the block class and can't be changed using tags or KubeJS.

**Comment by CannibalishToast** [comment]
I wanted to do the same thing lol, how did u proceed then? and thanks for the fast answer

**Comment by CannibalishToast** [comment]
Thank u, I didnt want to add No tree punching because of all the other features but the second one u sent really saved me.

**Comment by Fuyukai** [comment]
This is definitely the wrong issue but you can just do `block.requiresTool = true` in your block modify event. No need for an extra loaded mod.
