### ISSUE TITLE
1.7.10 help plssss

### ISSUE THREAD

**Issue by gdavigamerbr1** [KubeJS-Mods/KubeJS#193]
I know 1.7.10 is discontinued, but I'll try it anyway, I need a script to remove a mob drop, could you help me?

**Comment by Spiker985** [comment]
As you said yourself, 1.7.10 isn't supported.

And I very highly doubt that CommandScripts, as I believe it was called for 1.7.10, had the capability to perform the action you're wanting. So, even if it was supported, it most likely wouldn't be viable.
