### ISSUE TITLE
FTB Structure structures not spawning

### ISSUE THREAD

**Issue by Boolyman** [KubeJS-Mods/KubeJS#199]
I am trying to use KubeJS to designate the structures to spawn with FTB Structures, but despite using nearly the exact script on the wiki, no structures are spawning.  My script is below, and it is going into the server_scripts folder.  Are there any errors that would prevent spawning?  It's impossible to get anyone from FTB to actually respond to issues, even after going to their discord, so I hope you can help.

let FTBStructuresData = java('dev.ftb.mods.ftbstructures.FTBStructuresData');

structuresData.reset();

structuresData.oceanStructures.add((structure) => {
    structure.id = "ftboceanblock:ftb/overworld/tester1";
    structure.y = -16;
    structure.weight = 15;
});

structuresData.oceanStructures.add((structure) => {
    structure.id = "ftboceanblock:ftb/overworld/tester2";
    structure.y = -16;
    structure.weight = 15;
});

structuresData.oceanStructures.add((structure) => {
    structure.id = "ftboceanblock:ftb/overworld/tester3";
    structure.y = -16;
    structure.weight = 15;
})

**Comment by Spiker985** [comment]
What Minecraft, KubeJS, Architectury, Rhino, and FTB Structures versions?
What do your logs at `<instance>\logs\kubejs\startup.txt` and `<instance>\logs\latest.log` say?
What is the full code you are using?
