### ISSUE TITLE
/kubejs docs Command Not Working

### ISSUE THREAD

**Issue by ReelablePenny14** [KubeJS-Mods/KubeJS#2]
I downloaded kubejs.jar file from curse and moved it to my mods folder on my server. I start the server and open my client (running ftb academy 1.0.0). I type in the command "/kubejs docs" like it says i should do to find the documentation but an error pops up saying:

Invalid subcommand 'docs'! Available subcommands: reload

I just want to find the documentation for the mod so i can figure out what different scripts i will use on my server. If there is something I am missing I would gladly like to hear about it since im brand new to this mod and could have missed up big time. I know there are examples of code at https://kubejs.latvian.dev/ but having all the commands would greatly help more. If this is an upcoming feature I would like to know that. 

Thank you for your time and I can't wait to start writing scripts using your powerful mod tool. If you want to contact me faster pm me using my discord name as I am apart of your LatMod Industries server and I am using the same name as github "ReelablePenny14". Or just respond below. Thanks again!

**Comment by MaxNeedsSnacks** [comment]
The 'docs' command has been removed in newer KubeJS builds, there's currently another mod (`Aurora`) in the works that's gonna host the KubeJS documentation server once it's done.
