### ISSUE TITLE
Villager Trades support

### ISSUE THREAD

**Issue by Martmists-GH** [KubeJS-Mods/KubeJS#20]
Please add support for removing/adding trades from the wandering trader.

**Comment by Freebi85** [comment]
It would be great for villager trades in general 😄 Afaik KubeJS Fabric has already this feature 😭 

Cheers 🍺

**Comment by MaxNeedsSnacks** [comment]
This needs a new feature in architectury, the issue for which can be tracked here: https://github.com/architectury/architectury-api/issues/70

For anyone wanting to help out, feel free to add your thoughts there ^^

**Comment by MaxNeedsSnacks** [comment]
I'd like to wait for https://github.com/architectury/architectury-api/issues/86 before implementing this, since the Architectury API structure may still change until then, but @lythowastaken has actually started work on that, so we *may* be good to go on this soon

**Comment by SeeJayEmm** [comment]
That architectury issue is closed. Are there any plans to include this in KubeJS?

**Comment by Spiker985** [comment]
@MaxNeedsSnacks Architectury issues https://github.com/architectury/architectury-api/issues/70, https://github.com/architectury/architectury-api/issues/84, and https://github.com/architectury/architectury-api/issues/86 pertained to the villager trades - which are all closed. 

Do we want to keep this open, and does this need to be marked Forge Specific?

**Comment by MaxNeedsSnacks** [comment]
This has been implemented in AlmostReliable's [MoreJS](https://www.curseforge.com/minecraft/mc-mods/morejs) (on 1.18 and 1.19), and because we don't want to reinvent the wheel here, it likely won't be part of KubeJS itself anytime soon, so I'm going to be closing this for now ^^
