### ISSUE TITLE
[1.16.5] Recipe can't be made to ignore nbt data

### ISSUE THREAD

**Issue by Tismas** [KubeJS-Mods/KubeJS#202]
I think I've found a bug 🤔 
I've setup a create deploying recipe using `kubejs-forge-1605.3.13-build.45.jar` which was ignoring NBT data by default back then. 
With the newest version of kubejs(`kubejs-forge-1605.3.18-build.144.jar`) I cannot make it to ignore NBT data even with `.ignoreNBT()` .

The only thing that was updated was KubeJS (I've checkout my repo to the point in which the recipe was working, tested it and then udpated only KubeJS, left everything else as is, even KubeJS Create) and the recipe was working overall but was not ignoring NBT data (the recipe stops working as soon as deployed item got damaged)

Recipe which broke:
```
event.recipes.create
    .sequenced_assembly(
      [
        Item.of("rftoolsbase:machine_frame").withChance(100.0),
        Item.of("twilightforest:lamp_of_cinders").withChance(1.0),
      ],
      "create:brass_casing",
      [
        event.recipes.create.deploying(
          "immersiveengineering:steel_scaffolding_standard",
          [
            "create:brass_casing",
            "immersiveengineering:steel_scaffolding_standard",
          ]
        ),
        event.recipes.create.deploying("minecraft:iron_block", [
          "create:brass_casing",
          "minecraft:iron_block",
        ]),
        event.recipes.create.deploying("twilightforest:lamp_of_cinders", [
          "create:brass_casing",
          "twilightforest:lamp_of_cinders",
        ]),
      ]
    )
    .loops(1);
```

**Comment by Spiker985** [comment]
@Tismas Build [172](https://www.curseforge.com/minecraft/mc-mods/kubejs-forge/files/3527713) has a fix for items not copying NBT correctly.

Can you validate whether this issue has been fixed with a newer version?

**Comment by Spiker985** [comment]
No response, closing - feel free to reopen.

**Comment by Tismas** [comment]
I've just tested it on `kubejs-forge-1605.3.19-build.229.jar` and it still doesn't seem to work

**Comment by Tismas** [comment]
For anyone coming with the same issue - add tag to the item and use tag instead of that item in the recipe
