### ISSUE TITLE
Error loading resource packs when starting game.

### ISSUE THREAD

**Issue by Zarepheth** [KubeJS-Mods/KubeJS#209]
While attempting to start a game with mod pack: "Better Minecraft [FABRIC] - 1.17.1, v15", I suffer the below error. When it occurs, Minecraft keeps re-attempting to start the game, but keeps getting this error and never finishes starting.
```
Caught error loading resourcepacks, removing all selected resourcepacks
java.util.concurrent.CompletionException: java.lang.NullPointerException: Cannot read field "scriptManager" because "dev.latvian.kubejs.server.ServerScriptManager.instance" is null
```

Gist of Log file: https://gist.github.com/Zarepheth/de48070e19518835bd18d0d1f516dbf4

**Comment by Spiker985** [comment]
@Zarepheth KubeJS 1.17 was released on Alpha and is unsupported. 1.16.5 is the currently long term support version, until 1.18 becomes stable and is migrated to.
