### ISSUE TITLE
Game Not Playable With Mod In Mod Folder

### ISSUE THREAD

**Issue by StickFigureRobots** [KubeJS-Mods/KubeJS#211]
It crashes every time the game tries to load textures.
Here is the crash report:
[crash-2021-10-29_16.15.58-client.txt](https://github.com/KubeJS-Mods/KubeJS/files/7444718/crash-2021-10-29_16.15.58-client.txt)

**Comment by StickFigureRobots** [comment]
Apparently it was because I did something in assets folder in the kubejs folder. If you anything, and I mean ANYTHING, in the assets folder, it completely breaks the game and you have delete the assets folder.

**Comment by MaxNeedsSnacks** [comment]
This is a Mac-specific issue that I don't really know how to solve. Apple uses these weird .DS_Store files to store... some metadata? Users can't see them and Minecraft will complain because you shouldn't be using spaces in the assets folder.

**Comment by StickFigureRobots** [comment]
The only thing I can't do that I want to do is make custom items and blocks in Minecraft. This mod was my one chance to do that, and it failed, because I was on mac. JUST because I was on mac, no other reason?

**Comment by StickFigureRobots** [comment]
I meant, "am" not "was", sorry.
