### ISSUE TITLE
Game crashes while rendering overlay

### ISSUE THREAD

**Issue by DanDragonWolf** [KubeJS-Mods/KubeJS#212]
The game crashed while loading. Here's the crash report: [https://pastebin.com/JQ16PAX1](https://pastebin.com/JQ16PAX1)

**Comment by DanDragon401** [comment]
Seems like there's an incompatibility with some of the mods I have, I will have to see what's causing the issue

**Comment by DanDragonWolf** [comment]
I loaded the game with just kubejs and it's dependencies and now it works fine with all the mods I was using.

**Comment by DanDragonWolf** [comment]
I loaded the game with just kubejs and it's dependencies and now it works fine with all the mods I was using.

**Comment by DanDragonWolf** [comment]
Apparently I didn't have all of my mods loaded. It seems as though it's incompatible with Apocalypse Origins. I don't think that Apocalypse Origins is made for 1.16 anyways.
