### ISSUE TITLE
Why block.right_click runs twice when clicked in game!

### ISSUE THREAD

**Issue by SamukaDEV** [KubeJS-Mods/KubeJS#214]
![image](https://user-images.githubusercontent.com/13206430/140618955-74dee5e0-7111-4944-a317-50188f7176eb.png)
in the server_scripts folder i have registred this event only one time, and in the game is fired twice when the player click in blocks!

this script is in the right place?
i have forgot something?

i dont know why this is happening, and in the documentation i found nothing about this event!

Extra info: 
Minecraft Version: 1.16.5
Using Forge Version: 36.2.8
KubeJS Version: 1605.3.18-build.152

**Comment by LLytho** [comment]
it gets called once for the main hand and once for the off hand.
You can check the hand.

```js
if(event.hand == MAIN_HAND) { // OFF_HAND

}
```

**Comment by SamukaDEV** [comment]
thanks a lot, ill try
