### ISSUE TITLE
replace a recipe from ProjectE

### ISSUE THREAD

**Issue by Er5force** [KubeJS-Mods/KubeJS#216]
This is my first time coding in java and I don't have a lot of experience in it either.
I would like to remove the recipe from the philosopher's stone and then create a new recipe for it but it doesn't work. 

That's my code : 

onEvent('recipes', event => { event.remove({output: 'projecte:philosophers_stone'}) })

{
    "type": "minecraft:crafting_shaped",
    "pattern": [
        "nGn",
        "GDG",
        "nGn"
    ],
    "key": {
        "n": {
            "item": "minecraft:netherite_ingot"
        },
        "G": {
            "item": "minecraft:glowstone_dust"
        },
        "D": {
            "item": "minecraft:diamond"
        }
    },
    "result": {
        "item": "minecraft:projecte:philosophers_stone",
        "count": 1
    }
}

**Comment by Er5force** [comment]
sorry for the code i don't know how to format it

**Comment by 19175** [comment]
The discord is probably a better place to get help for this than the issue tracker.

Before asking there however, I would recommend checking the wiki, especially the recipe page, for learning the basics of using KubeJS to edit recipes. 
https://mods.latvian.dev/books/kubejs/page/recipeeventjs

As for formatting as code, put ``` around it to (both in GH and Discord)

**Comment by Er5force** [comment]
I took my code from there but it didn't want to work.

thanks for all anyway !
