### ISSUE TITLE
Just a coding question.

### ISSUE THREAD

**Issue by TheUntamed** [KubeJS-Mods/KubeJS#22]
Hi, I'm creating my own mod and I'm trying to handle blockstates and models for items/blocks that are not registered during mod build which means I cannot just create jsons for those blocks/items because I don't know them yet.
I know that kubejs allows the user to add items/blocks themselves which results in the same problem. I tried to find out how you did that but I didn't quite get through your code. Could you give me a little hint?

**Comment by LatvianModder** [comment]
If you still need help with this, I basically create a virtual resourcepack that still serves json files, they are just generated with code as strings
