### ISSUE TITLE
thermal.smelter not respecting NBT

### ISSUE THREAD

**Issue by TemperedFool** [KubeJS-Mods/KubeJS#221]
Trying to set up the following recipe:

```
e.recipes.thermal(
     Item.of('resourcefulbees:bee_jar', {Entity: "resourcefulbees:electrum_bee"}),
     [
          Item.of('resourcefulbees:bee_jar', {Entity: "resourcefulbees:silver_bee"}).weakNBT()
          Ingredient.of('resourcefulbees:gold_honeycomb_block', 1)
     ])
```

Recipe doesn't respect the NBT for the `bee_jar` item - it will accept one with no NBT.

Recipe shows correctly in JEI:
![image](https://user-images.githubusercontent.com/13169307/143904164-4311e7ee-b6eb-465f-9f5d-97a7d7d22e3b.png)

**Comment by ChiefArug** [comment]
This is intended on Thermals end:

![Screenshot_2021-12-02-18-50-34-10.jpg](https://user-images.githubusercontent.com/73862885/144365554-4cea4de3-e03f-4beb-9ad4-bbb8cc1ccdce.jpg)
https://discord.com/channels/399037120930512897/434101214548852746/894234754709331968

**Comment by Hunter19823** [comment]
Based on the previous comment, this seems to be an issue with Thermal Expansion, not KubeJS.
