### ISSUE TITLE
crash during client launch

### ISSUE THREAD

**Issue by thevortex** [KubeJS-Mods/KubeJS#228]
getting a crash during load on forge 38.0.14 https://gist.github.com/thevortex/84c828af47c94bf12c299d7c7f563f74 looking to get started on atm7 for 1.18 but we need kube :D lmk if you need anything further(this is initial loading, no scripts installed beyond the default hello worlds that come with it)

**Comment by MaxNeedsSnacks** [comment]
Yep yep, something's wrong with the custom flat chunk generator, already pushed a fix! (Should be out in a minute or two)

**Comment by thevortex** [comment]
thanks for the quick reply!! i hadnt even closed the page yet haha!

**Comment by MaxNeedsSnacks** [comment]
I coincidentally just had this exact same issue in dev because I used Forge for testing once instead of Fabric
