### ISSUE TITLE
Fabric 1.18 - Custom fluids error

### ISSUE THREAD

**Issue by NotSoEpic** [KubeJS-Mods/KubeJS#233]
The game crashes on startup, and this is the only code I have in the startup_scripts folder
```javascript
onEvent('fluid.registry', event => {
    event.create('hyper_gro').textureThin(0xd086f0).bucketColor(0xd086f0).displayName('Hyper-Gro')
})
```
[crash-2021-12-09_13.23.11-client.txt](https://github.com/KubeJS-Mods/KubeJS/files/7682468/crash-2021-12-09_13.23.11-client.txt)

I tried the same code on forge 1.18 and everything works fine

**Comment by MaxNeedsSnacks** [comment]
Custom fluids are not supported on Fabric as, last time I checked, they lack an API for fluid attributes.

**Comment by MaxNeedsSnacks** [comment]
This has been implemented now!
