### ISSUE TITLE
Mod ores not removing

### ISSUE THREAD

**Issue by ShockPuppet** [KubeJS-Mods/KubeJS#234]
Fabric version of kubejs wont remove mod placed ores (tech reborn, didnt test others). Was working great in MC 1.17 but in 1.18 doesnt appear to do anything. Am using start up script worldgen.js with the following content to test TR tin ore removal:

```
onEvent('worldgen.remove', event => {
	
  event.removeOres(ores => {
    ores.blocks = [ 'techreborn:tin_ore' ]
  })
})
```

Latest fabric client, the only mods present are kubejs and tech reborn and required dependencies. No datapacks or resource packs. Tested with latest fabric kubejs mod and also previous version 207.

Apologies if this is known or ive done something wrong, ive spent a few hours testing this. I also tried removing by id.

**Comment by Chuunkyz** [comment]
kubejs can't remove ores in 1.17 too
there's a mod that fixes the removeOre thing, called KubeJS Extras

**Comment by MaxNeedsSnacks** [comment]
The worldgen events have been commented out because I wanted to refactor them (see #149 for an old, unfinished attempt at that), but haven't had the time to do so and because the current implementation is likely broken
