### ISSUE TITLE
Custom Ingredients not working on Fabric

### ISSUE THREAD

**Issue by Vaelzan** [KubeJS-Mods/KubeJS#239]
Testing with this recipe (from the documentation, but with two typos fixed that have been discussed on Discord):
```
event.shapeless('9x minecraft:melon_slice', [ // Craft 9 watermelon slices
    Item.of('minecraft:diamond_sword').ignoreNBT(), // Diamond sword that ignores damage
    'minecraft:melon' // Watermelon block
  ]).damageIngredient(Item.of('minecraft:diamond_sword').ignoreNBT()) // Damage the sword (also has to ignore damage or only 0 damage will work)
 ```
The sword vanishes entirely with kubejs-fabric-1800.4.0-build.238, but is damaged correctly in the corresponding Forge version. The recipe output works in both.

**Comment by MaxNeedsSnacks** [comment]
Custom ingredients are not supported in Fabric since Fabric API has no suitable alternative we could use as of right now, this same could should work properly on Forge though as you said

**Comment by MaxNeedsSnacks** [comment]
Turning this into a more general issue for custom ingredient support on Fabric (this **includes** things like ignoreNBT() and weakNBT())

**Comment by MaxNeedsSnacks** [comment]
With the introduction of Fabric‘s in house custom Ingredient API, this is no longer an issue on 1.19.2+ (KubeJS 6 and above)

Given that the only alternative for <= 1.18 is depending on Ingredient Extension API, this will likely not be backported.
