### ISSUE TITLE
Add handle for top level files

### ISSUE THREAD

**Issue by TiphaineLAURENT** [KubeJS-Mods/KubeJS#241]
Hi 😁
Could you add support for top level files ?
By top level I mean : `kubejs/`

The goal of this feature is to be able to handle common file like constants:
```js
// kubejs/constants.js

const removedItemsId = [...]
```
```js
// kubejs/client_scripts/jei.js

onEvent('jei.hide.items', event => {
    event.hide(removedItemsId)
})
```
```js
// kubejs/server_scripts/remove.js

onEvent('recipes', event => {
    removedItemsId.forEach(removedItemId => {
        event.remove({ input: removedItemsId })
        event.remove({ output: removedItemsId })
    }
})
```

**Comment by MaxNeedsSnacks** [comment]
There's a `global` object you can use to share things across script types ^^

Just add a startup script that has `global.removedItemsId = […]` and then you can use that across files

**Comment by TiphaineLAURENT** [comment]
> There's a `global` object you can use to share things across script types ^^
> 
> Just add a startup script that has `global.removedItemsId = […]` and then you can use that across files

Is there any way I can contribute to https://mods.latvian.dev/books/kubejs ?
