### ISSUE TITLE
[KubeJS Create] [Forge] [1.16.5] createMilling adds milling and crushing recipes.

### ISSUE THREAD

**Issue by shwible** [KubeJS-Mods/KubeJS#243]
I'm not sure if this is intentional but 
`event.recipes.createMilling()`

adds both a crushing recipe and a milling recipe.
They have the same inputs and outputs but they're on different machines.
Is this intended?

**Comment by LatvianModder** [comment]
Yes, thats how create works, all milling recipes are automatocally crushing too
