### ISSUE TITLE
Modrinth Support

### ISSUE THREAD

**Issue by ExoPlant** [KubeJS-Mods/KubeJS#244]

**Comment by LatvianModder** [comment]
Nah. Bluntly put, it gives me no profit and no advantage to pack creators, almost everyone already uses CurseForge

**Comment by copygirl** [comment]
Modrinth keeps growing. It now has:

- [Creator Monitization Program](https://blog.modrinth.com/p/creator-monetization-beta)
- [Modpack Support](https://modrinth.com/modpacks)
- Their own [launcher in development](https://www.gamingonlinux.com/2023/05/modrinth-make-their-own-launcher-for-minecraft-modders/)
- Support from a lot of existing launchers to auto-download and -update mods and modpacks
- Many [KubeJS Addons](https://modrinth.com/mods?q=kubejs) already on the platform
- And, obviously, an ever-growing repertoire of mods and modpacks

It might be a good time to reconsider.
