### ISSUE TITLE
[Forge 1.18.1] editing/adding tags (any type) doesn't work

### ISSUE THREAD

**Issue by freopt** [KubeJS-Mods/KubeJS#246]
Copying and pasting the example from https://mods.latvian.dev/books/kubejs/page/tageventjs does not do anything
based on other issues maybe the names of things changed and the wiki hasnt updated yet

**Comment by MaxNeedsSnacks** [comment]
The event names did change in 1.18, see the initial changelog for 1.18

(TL;DR `item.tags` => `tags.items`)

**Comment by MaxNeedsSnacks** [comment]
Wiki has just been updated to reflect this change, thanks for the reminder!
