### ISSUE TITLE
Modifying existing items doesn't work sometimes

### ISSUE THREAD

**Issue by esilaanawic** [KubeJS-Mods/KubeJS#248]
Some stuff is broken for modifying existing items.

For example, `item.setBurnTime(800)` works,
but `item.setMaxStackSize(16)` _doesn't_ work.

Errors pertaining to this aren't recorded in log file.

I haven't tested every possible thing, probably also some broken stuff for blocks too.

**Comment by blood789** [comment]
Have you done? The website gives too few examples. I want to modify the block hardness, mining level, and the mining level of the tool.

**Comment by blood789** [comment]
Can you give some example templates
