### ISSUE TITLE
Crash on crafting 

### ISSUE THREAD

**Issue by xAlicatt** [KubeJS-Mods/KubeJS#25]
Very weird crash that happens when crafting items from the Farmer's Delight mod using the knife. I haven't done an extensive amount of testing on this, since my pack takes a very long time to load and it crashes both the client and the server when it happens. 

Let me know if I should be reporting this to the Farmer's Delight dev instead. 

Client side crash log: https://paste.ee/p/EgZP7#qZL8RDOT4dUeGw6IuazHVlfPmv5EL5Xq
Server side crash log: https://paste.ee/p/OwtMO#r3WWWgvhH8XXAETAOAAF6Hz4nxpoTRin

**Comment by andrewsf** [comment]
Please reupload crash logs in a manner that will not cause expiration.

**Comment by xAlicatt** [comment]
This was fixed a long time back by the Farmer's Delight dev. Sorry for not coming back and closing it!
