### ISSUE TITLE
Please，Can you give some example templates？

### ISSUE THREAD

**Issue by blood789** [KubeJS-Mods/KubeJS#250]
I want to modify the hardness of the original game block, the mining level, the durability of the tool, the mining level, etc., but the website gives too few examples.

**Comment by blood789** [comment]
tier = tierOptions => {
int uses
float speed
float attackDamageBonus
int level
int enchantmentValue
Ingredient repairIngredient
}
foodProperties = food => { // note: uses functions instead of a = b
hunger(int)
saturation(float)
meat(boolean)
alwaysEdible(boolean)
fastToEat(boolean)
effect(String effectId, int duration, int amplifier, float probability)
removeEffect(String effectId)
}

For example, I don’t know how to use these 2 types

**Comment by blood789** [comment]
onEvent('item.modification', event => {
    event.modify('minecraft:stone_pickaxe', item => {
      item.level = 5
      item.enchantmentValue = 20
    })
 })

I wrote it like this, but it didn't work

**Comment by VampireTechnologyLord** [comment]
Alright… I’m on my phone right now, so this might sound weird:
1. The things you are asking are structured in the[docs](https://mods.latvian.dev/books/kubejs/page/item-modification) like they are, because they are done in the event like this:
```js
onEvent('item.modification', event => {
  event.modify('minecraft:ender_pearl', item => {
    item.maxStackSize = 64
    item.fireResistant = true
    tier = tierOptions => {
    // now the level & stuff
    }
  })
})
```
2. Docs are mentioned under issue #114

**Comment by Spiker985** [comment]
Questions like this are most easily rectified by asking in the Discord: https://discord.gg/bPFfH6P. Also closing due to lack of response.
