### ISSUE TITLE
1.18.1 Creating crafting recipes that require nbt is completely broken

### ISSUE THREAD

**Issue by TheQKnight** [KubeJS-Mods/KubeJS#252]
Crafting recipes that are made to require nbt work with all items. For example this script

```
onEvent('recipes', (event) => {
  event.shapeless('4x minecraft:cobblestone', [
    Item.of('minecraft:firework_star', '{CustomModelData:201}'),
  ])
})
```

Allows all firework stars to be used in the recipe. Same happens if I remove the quotes enclosing the nbt object.

**Comment by MaxNeedsSnacks** [comment]
Is this on Forge or on Fabric? In case of the latter, see https://github.com/KubeJS-Mods/KubeJS/issues/239
