### ISSUE TITLE
Is there a way to modify the hardness of the block?

### ISSUE THREAD

**Issue by blood789** [KubeJS-Mods/KubeJS#253]
Hello, is there a way to modify the hardness of the block?

The example on the wiki is :
onEvent('block.modification', event => {
  event.modify('minecraft:stone', block => {
    block.destroySpeed = 0.1
    block.hasCollision = false
  })
})

What is the meaning of block.destroySpeed ? Let the player dig slower or faster？But it does't work for "block.destroySpeed = 10".

I want to change the hardness of the block， I write as the below，but it does't work.
onEvent('block.modification', event => {
  event.modify('minecraft:stone', block => {
    block.hardness = 50
  })
})

**Comment by TheRealQuentin765** [comment]
ask on the discord if you want a higher chance of answers:
https://discord.gg/bPFfH6P
