### ISSUE TITLE
Add a warning/error when an unrecognized event is used in onEvent

### ISSUE THREAD

**Issue by ChiefArug** [KubeJS-Mods/KubeJS#259]
This would help a lot with debugging, especially with the change of quite a few event names in 1.18

**Comment by MaxNeedsSnacks** [comment]
I don't think this is feasible with how we set up events currently, we'd have to add some event registry and a special case to handle dynamic event names (like `ftbquests.completed.[object_id]`), and honestly, if we were to do that it'd be much more feasible to just rewrite the event system from the ground up

**Comment by ChiefArug** [comment]
Fair point
