### ISSUE TITLE
【BUG】New items cannot load textures

### ISSUE THREAD

**Issue by blood789** [KubeJS-Mods/KubeJS#265]
New items cannot load textures in my modpack.

If I disable all mods and run KUBEJS alone, the item textures load correctly.

I don't know which mod it is conflicting with, so I had to send it to you.

[Project Test-0.1.zip](https://github.com/KubeJS-Mods/KubeJS/files/7896723/Project.Test-0.1.zip)

Thanks.

**Comment by blood789** [comment]
I write as this :

onEvent('item.registry', event => {
  event.create('diamond_shard', item => {item.displayName('Diamond Shard')})
  event.create('emerald_shard', item => {item.displayName('Emerald Shard')})
  event.create('flint_shard', item => {item.displayName('Flint Shard')})
  event.create('obsidian_shard', item => {item.displayName('Obsidian Shard')})
  event.create('sinew', item => {item.displayName('Sinew')})
  event.create('flint_hatchet', item => {
    item.displayName('Flint Hatchet').type('axe').tier('wood').maxDamage(3).tooltip("Your first tool in this world!")
  })
  event.create('flint_axe', item => {
    item.displayName('Flint Axe').type('axe').tier('wood').maxDamage(12)
  })
  event.create('flint_shovel', item => {
    item.displayName('Flint Shovel').type('shovel').tier('wood').maxDamage(12)
  })
})

**Comment by blood789** [comment]
I found a solution, I added a resource pack named kubejs, including Including pictures, lang, models......

**Comment by TheRealQuentin765** [comment]
Please close the issue.
Next time post problems with kubejs mod packs in the discord: https://discord.gg/bPFfH6P
GitHub issues are meant for problems with KubeJS itself, not issues in its uses.
Also you will get much more support on the discord, where as no one but the devs really check the GitHub to help with problems such as these.
Also it will reduce the amount of time that the devs need to work on knowing which issues are their problems so they can fix bugs, such as the ones that have been troubling me, faster.
