### ISSUE TITLE
Add .getAllItems() in tag event

### ISSUE THREAD

**Issue by iglee42** [KubeJS-Mods/KubeJS#266]
Utility: retrieve all items with a specific tag

**Comment by ChiefArug** [comment]
While this is possible with items with `Ingredient.of('#tag').stacks` or `Ingredient.of('#tag').itemIds` it would be great for being able to do it with blocks and fluids to (and a more intuitive way to do it for items)

**Comment by ChiefArug** [comment]
1.18.2 has a lot of new tag types, will be good to get this in with compat for all of those too.
