### ISSUE TITLE
KubeJS just crashes

### ISSUE THREAD

**Issue by tebbbi** [KubeJS-Mods/KubeJS#268]
So i try and load:
architectury-1.28.48
fabric-api-0.42.0+1.16
kubejs-fabric-1605.3.19-build.229
rhino-fabric-1605.1.5-build.75

and: 
fabric-loader-0.12.10-1.16.5

and whenever i run it, it comes up with this:

 The game crashed whilst initializing game
Error: java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'kubejs'!
Exit Code: -1

Heres a pastebin to my lastest-log: https://pastebin.com/rfB25rL7

**Comment by tebbbi** [comment]
i have tried the lastest version of KubeJS and it does the same thing.

**Comment by Spiker985** [comment]
From your log it appears to be a mixin problem with Arch. Does this still happen in the most recent release build?

**Comment by isaaclepes** [comment]
I've been having a similar issue on 1.18.1.

Minecraft: 1.18.1
Forge. 39.00.66
KubeJS:  kubejs-forge-1801.4.2-build.298
Rhino: rhino-forge-1800.1.7-build.94
Architectury: architectury-3.6.16
debug.log: https://gist.github.com/isaaclepes/29c3c32bb0ead6ca9d67b77027d504a3
latest.log: https://gist.github.com/isaaclepes/9e12b72b5ae3834c98dd863b195ac682

**Comment by MaxNeedsSnacks** [comment]
@isaaclepes This crash is unrelated to the current issue, please update your Rhino jar and try again

**Comment by isaaclepes** [comment]
I am using the latest release version of Rhino, are you saying the beta is stable?
