### ISSUE TITLE
Add fluid without bucket and block

### ISSUE THREAD

**Issue by khjxiaogu** [KubeJS-Mods/KubeJS#269]
Sometimes I may want to add some unplacable fluids, or without bucket to make it only fits in some custom containers. However, this isn't possible with fluid register only.
Adding this feature would make fluid more customize, fulfill more needs.

**Comment by MaxNeedsSnacks** [comment]
Implemented in the 1.18.2 version of KubeJS, along with custom fluids for fabric ^^
