### ISSUE TITLE
is there a way to check if there is a specific item in the player's inventory?

### ISSUE THREAD

**Issue by SamukaDEV** [KubeJS-Mods/KubeJS#27]
![image](https://user-images.githubusercontent.com/13206430/93019624-886a3d80-f5ae-11ea-9a1e-b762073db673.png)

explaining: i want to access this items without open a chest to do it! 

![image](https://user-images.githubusercontent.com/13206430/93019651-b51e5500-f5ae-11ea-8c52-241531efe6bd.png)

i have accessed the ivnentory, but in a chest! i want to find items without open a chest, when i hit "E" or something like!

**Comment by SamukaDEV** [comment]
seria muito interessante uma documentação mais abrangente, nao consigo encontrar varias duvidas que encontro sobre metodos e propriedades de eventos e funções, gostaria demais de novos conteudos na documentação.

**Comment by andrewsf** [comment]
Use the [`player.inventory.xxxx` events](https://github.com/KubeJS-Mods/KubeJS/blob/369900dc7441c1d816aa706772e265bf74cc8809/src/main/java/dev/latvian/kubejs/KubeJSEvents.java#L85).

For the change event, [`entity` / `item` / `slot` will tell you about the change](https://github.com/KubeJS-Mods/KubeJS/blob/0ef36d79863828debc9700b85b5608c3bc5920b6/src/main/java/dev/latvian/kubejs/player/InventoryChangedEventJS.java#L24).

For opening or closing an inventory, [`entity` / `inventoryContainer`] are available. Keep in mind that `inventoryContainer` is not a KubeJS wrapper, so it could break in future Minecraft updates.

For better documentation, read the source code like this and update the wiki.

**Comment by andrewsf** [comment]
Actually, a better approach would be to call [`event`](https://github.com/KubeJS-Mods/KubeJS/blob/3e2b08196048cd2ba865addd862cf2b2efc4196d/src/main/java/dev/latvian/kubejs/player/InventoryEventJS.java) . [`player`](https://github.com/KubeJS-Mods/KubeJS/blob/3e2b08196048cd2ba865addd862cf2b2efc4196d/src/main/java/dev/latvian/kubejs/player/PlayerEventJS.java#L16) . [`inventory`](https://github.com/KubeJS-Mods/KubeJS/blob/3e2b08196048cd2ba865addd862cf2b2efc4196d/src/main/java/dev/latvian/kubejs/player/PlayerJS.java#L71) and then [do what you want](https://github.com/KubeJS-Mods/KubeJS/blob/3e2b08196048cd2ba865addd862cf2b2efc4196d/src/main/java/dev/latvian/kubejs/item/InventoryJS.java).
