### ISSUE TITLE
I cannot get stonecutting recipes to work.

### ISSUE THREAD

**Issue by damianjoakes** [KubeJS-Mods/KubeJS#272]
After reviewing documentation on the KubeJS website and over an hour of testing new ways of doing it, I cannot possibly find a way to add stonecutting recipes in. I'm not sure if this is a currently know issue or if it's something I'm doing wrong.

**Comment by ChiefArug** [comment]
Can you join the discord and ask for help in one of the dedicated support channels, making sure to post the code you tried using. The issue tracker isnt a place to ask for scripting help.

Discord: https://discord.gg/bPFfH6P

**Comment by damianjoakes** [comment]
I apologize, thank you.
