### ISSUE TITLE
Player speed cannot be changed.

### ISSUE THREAD

**Issue by The-Arcanian** [KubeJS-Mods/KubeJS#273]
Using the script:
```
var blockSpeeds = [
    {
        blocks: [
            'minecraft:sand',
            'minecraft:red_sand'
        ],
        speed: 0.000000001
    },
    {
        blocks: [
            'minecraft:gravel',
            'minecraft:cobblestone',
            'minecraft:mossy_cobblestone',
            'minecraft:stone_bricks',
            'minecraft:mossy_stone_bricks',
            'minecraft:cracked_stone_bricks'
        ],
        speed: 0.2
    }
]

var speedObject = {};

blockSpeeds.forEach(set => {
    set.blocks.forEach(block => {
        speedObject[block] = set.speed
    })
})

onEvent('player.tick', event => {
    if (speedObject[event.player.block.down.id]) {
        console.log(event.player.getMovementSpeed())
        console.log(`${event.player} is standing on ${event.player.block.down.id}, setting speed to ${speedObject[event.player.block.down.id]}.`)
        event.player.setMovementSpeed(speedObject[event.player.block.down.id])
        console.log(event.player.getMovementSpeed())
    } else {
        console.log(event.player.getMovementSpeed())
        console.log(`${event.player} not standing on specified block, setting speed to ${speedObject[event.player.block.down.id]}.`)
        event.player.setMovementSpeed(1.0)
        console.log(event.player.getMovementSpeed())
    }
})
```
gave the log:
```
[01:45:20] [Server thread/INFO] [KubeJS Server/]: server_scripts:arcETech/kubejs/base/entity/player.js:32: 0.10000000149011612
[01:45:20] [Server thread/INFO] [KubeJS Server/]: server_scripts:arcETech/kubejs/base/entity/player.js:33: The_Arcanian is standing on minecraft:gravel, setting speed to 0.2.
[01:45:20] [Server thread/INFO] [KubeJS Server/]: server_scripts:arcETech/kubejs/base/entity/player.js:35: 0.10000000149011612
```
Lines like `event.player.movementSpeed = speedObject[event.player.block.down.id]` did the same thing.

**Comment by LLytho** [comment]
PR through: https://github.com/KubeJS-Mods/KubeJS/pull/274

Some side note, if you just want to add a speed multiplier when touch a block, like soulsand does it. You can use `block.modification` event for `startup_scripts` and modify the `speedFactor` of a block.

This should work:
```js
onEvent('block.modification', event => {
  event.modify('minecraft:gravel', block => {
    block.speedFactor= 0.5;
  })
})
```

**Comment by The-Arcanian** [comment]
`speedFactor` was the first thing I tried. But it has some odd behavior like, `0.0` not completely stopping the player, values over 1.0 start to make the controls slippery, and values approaching 2.0 make even the slightest movement start to compound. I could not find enough documentation to figure out how it all worked. So someone on the discord segested changing movementSpeed instead.

Maybe I should also mention that I am using 1.16.5 so I would prefer it to be fixed on that version up.

**Comment by LLytho** [comment]
Are you sure you changed the `speedFactor` and not the `friction` of the block? Or maybe the speedFactor also controls the slippery together with friction. But not quite sure.

I will PR 1.16.5 changes later too then!

**Comment by The-Arcanian** [comment]
Absolutely sure. It seemed like `speedFactor` was affecting the player's current speed, not their movement speed. `speedFactor = 0.0` did slow the player, but did not stop them. Negative `speedFactor`s under `-2.0` (~`0.0`-`-2.0`) would cause wabbling, at least for values that would not imminently throw you out of my testing zone at the slightest movement, probably from constantly inventing current movement direction while slowly decreasing speed.

**Comment by LLytho** [comment]
Ignore what I said. It makes sense, that `speedFactor` works like this, because it handles the motion of the player. So yeah `0.0` would not stop the player immediately.
![image](https://user-images.githubusercontent.com/29131229/151400918-12b3fe6f-1334-42d4-bffb-5170751b6063.png)

**Comment by The-Arcanian** [comment]
Ya, delta, change over time.

**Comment by MaxNeedsSnacks** [comment]
Lat has since merged the relevant PR, so this should **hopefully** no longer be an issue

**Comment by andrewminer** [comment]
I was trying to do something similar, and Google directed me to this issue.  Things have changed a bit since 2022, so here's the code which worked for me as of MCv1.21.1, just in case anyone else wanders in...

```javascript
// The DefaultMovementSpeed uses 0.1 as the "normal" walking speed.
const BASE_SPEED = 0.1;

const PATH_SPEED = 1.10;
const ROAD_SPEED = 1.25;
const SAND_SPEED = 0.80;

// A mapping of block ID to the multiplier to use.
const SPEED_MAP = {
    "mcwpaths:stone_running_bond_path": ROAD_SPEED, // 3rd-party, partial block
    "mcwpaths:stone_running_bond": ROAD_SPEED, // 3rd-party, full-sized block
    "minecraft:dirt_path": PATH_SPEED, // vanilla, partial block
    "minecraft:sand": SAND_SPEED, // vanilla, full-sized block
};

PlayerEvents.tick(function(event) {
    let player = event.player;

    // If the block containing the player's feet is solid, then it's probably some partially solid
    // block (e.g., dirt path, stairs, slab, etc.), and it's the one we want to base our speed on.
    // Otherwise, if the player's feet are inside some non-solid block (e.g., air, flowers, etc.),
    // then we want the block below them.
    let block = player.block;
    if (!block.blockState.solid) {
        block = player.block.down;
    }

    // Check if they're standing on a block we've configured.
    let speed = SPEED_MAP[block.id];
    if (speed === undefined) {
        // Reset speed if they're on any block not specifically configured above.
        speed = 1.0;
    }

    player.setDefaultMovementSpeed(BASE_SPEED * speed);
});
```
