### ISSUE TITLE
[1.18] removing tags doesnt work

### ISSUE THREAD

**Issue by Chuunkyz** [KubeJS-Mods/KubeJS#277]

**Comment by LLytho** [comment]
Example code used: 
```js
onEvent('tags.items', event => {
	event.remove('c:iron_ingots', 'betternether:cincinnasite_ingot');
  	event.remove('c:shears', 'betternether:cincinnasite_shears');
})
```

and if I understand it correctly `#c:iron_ingots` and `#c:shears` does not exist at the moment where the tag event happens and the tag event creates a `TagWrapper` with an empty proxylist.

**Comment by edotenseilove** [comment]
I tried adding items to a tag and it also did not work. I even tried enabling the kubejs script.js example still with no change in game

**Comment by ChiefArug** [comment]
You need to use a datapack for that mod, and set the `replace` value to true so that it wipes the tag.
