### ISSUE TITLE
Failed to build

### ISSUE THREAD

**Issue by DoctorApparatus** [KubeJS-Mods/KubeJS#281]
When building the 1.18/main branch I get:
java.lang.UnsupportedClassVersionError: net/fabricmc/loom/bootstrap/LoomGradlePluginBootstrap has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0

**Comment by MaxNeedsSnacks** [comment]
Your Gradle JDK is set to Java version 8 (52), you should be using Java 11+ (55) to build using loom in general, and Java 17+ (61) to build for Minecraft 1.18

**Comment by Spiker985** [comment]
@DoctorApparatus Were you able to get 1.18 main to build, and can we close this issue?

**Comment by Spiker985** [comment]
Closing issue due to no response
