### ISSUE TITLE
unable to run kubejs on curseforge (1.18.1) 

### ISSUE THREAD

**Issue by MrBLaZe4** [KubeJS-Mods/KubeJS#282]
[latest.log](https://github.com/KubeJS-Mods/KubeJS/files/8021125/latest.log)

cannot launch an instance on curseforge with kubejs because it does not detect rhino, if I disable kubejs and rhino the instance launches fine.

P.S. there are 13 mods without counting kubejs and rhino

**Comment by Mktotoy** [comment]
Hi ! Got the same problem with KubeJS and Rhino with same errors in my latest.log file :)

**Comment by Spiker985** [comment]
@Mktotoy @MrBLaZe4 Can we consider this issue closed?

**Comment by MaxNeedsSnacks** [comment]
> @Mktotoy @MrBLaZe4 Can we consider this issue closed?

way ahead of you :p
