### ISSUE TITLE
Initializing game I java.lang.RuntimeException

### ISSUE THREAD

**Issue by TheButterbrotMan** [KubeJS-Mods/KubeJS#287]
### Minecraft Version

1.18.1

### KubeJS Version

1801.4.2-build.300

### Rhino Version

1801.1.8-build.102

### Architectury Version

3.7.22

### Forge/Fabric Version

Fabric 0.13.2

### Describe your issue

Is crashing at starting client

### Crash report/logs

https://bytebin.lucko.me/czxxAWnIDJ

**Comment by Spiker985** [comment]
Reminder: Beta releases are not meant for production, hence not being marked as a release build.

Can you confirm this problem still exists in [kubejs-fabric-1801.4.3-build.310.jar](https://www.curseforge.com/minecraft/mc-mods/kubejs-fabric/files/3670981)?

**Comment by MaxNeedsSnacks** [comment]
This issue seems to be unrelated to KubeJS, it's merely blamed by Fabric Loader here since it loads the class that iTNT fails to transform using mixin
