### ISSUE TITLE
Just some errors from other mods conflicting with your mod (still works)

### ISSUE THREAD

**Issue by entwinedent** [KubeJS-Mods/KubeJS#288]
### Minecraft Version

1.18.1

### KubeJS Version

kubejs-fabric-1801.4.2-build.300

### Rhino Version

rhino-fabric-1801.1.8-build.102

### Architectury Version

architectury-3.7.22

### Forge/Fabric Version

0.13.2

### Describe your issue

just some ---  Failed to parse recipe errors, with medievalweapons-1.1.8 , dimores-1.18-1.0.3,  Gobber2-Fabric-1.18.1-2.5.62 , everything works but some recipes failed to parse don't know if anyone can patch this just asking
[server.txt](https://github.com/KubeJS-Mods/KubeJS/files/8116229/server.txt)
.

**Comment by ChiefArug** [comment]
If you use just that mod those errors should still show up in the vanilla latest.log, it is probably a typo on the mods end and so you should test with just each of those mods and report it to them.

**Comment by Spiker985** [comment]
These are just recipes implemented by mods that contain invalid recipes, generally due to mod integrations, but without checking if the mod is loaded before trying to add the recipe.
