### ISSUE TITLE
Regex seems don't work to remove tag from item

### ISSUE THREAD

**Issue by Dovahkill** [KubeJS-Mods/KubeJS#291]
### Minecraft Version

1.16.5

### KubeJS Version

1605.3.19-build.299

### Rhino Version

1605.1.5-build.75

### Architectury Version

1.30.53

### Forge/Fabric Version

Forge - 36.2.29

### Describe your issue

Hello, 

I'm trying to remove a tag by regex, but it doesn't work.

```event.remove('mI try to remove a tag by regex, but it's don't work.inecraft:planks', /quark:vertical_(.*)_planks/)```
OR
```event.remove('minecraft:planks', [/quark:vertical_(.*)_planks/])```

Same regex syntax works perfectly for removing recipes by output
```event.remove({output: /quark:vertical_(.*)_planks/})```

Thank's for amazing KubeJs

**Comment by LLytho** [comment]
As c743fab658d3513687a0564c0ce547ae054c4a71 added the functionality to 1.18.2+. I assume this will not be done for 1.16 anymore right? @MaxNeedsSnacks

**Comment by MaxNeedsSnacks** [comment]
That's correct, this would be more of a hassle to do on the 1.16 side of things
