### ISSUE TITLE
Port to 1.18.2

### ISSUE THREAD

**Issue by JustFoxx** [KubeJS-Mods/KubeJS#295]
### Describe the feature

Port for fabric 1.18.2

**Comment by LLytho** [comment]
KubeJS will be ported to 1.18.2. There is already a [branch ](https://github.com/KubeJS-Mods/KubeJS/tree/1.18.2/dev) for it.

**Comment by MaxNeedsSnacks** [comment]
We are going to be releasing KubeJS for Forge and Fabric 1.18.2 at the same time, and will also be dropping support for 1.18.1 in the process. Please give it a couple more days though since Forge is currently having issues with their registry / tag system on 1.18.2
