### ISSUE TITLE
Mekanism Purifying Recipes Added by Kubejs use 10x too much gas

### ISSUE THREAD

**Issue by TheAmazingJeh** [KubeJS-Mods/KubeJS#296]
### Minecraft Version

1.16.5

### KubeJS Version

1605.3.19

### Rhino Version

1605.1.5

### Architectury Version

1.30.55 

### Forge/Fabric Version

36.2.21

### Describe your issue

I have the same problem described in [this](https://github.com/KubeJS-Mods/KubeJS/issues/43) post, however the link to the hastebin code link has expired. How do you change the fluid amount?

**Comment by Spiker985** [comment]
I do believe that Mechanism recipes use a multiplier, not a static fluid/gas amount unlike other recipe handlers.

Can you provide your recipe script, and a screenshot of the amount that is purported to be used in-game?

**Comment by MaxNeedsSnacks** [comment]
That's normal, the amount of gas used is multiplied with a set factor by mekanism, though that said, the factor should be 200 iirc so an amount of 1 would likely fix this
