### ISSUE TITLE
With REI, KubeJS hiding doesn't work if the item/block isn't in a creative tab

### ISSUE THREAD

**Issue by mosharky** [KubeJS-Mods/KubeJS#299]
### Minecraft Version

1.18.1

### KubeJS Version

1801.4.3-build.310

### Rhino Version

1801.1.8-build.104

### Architectury Version

3.7.33

### Forge/Fabric Version

Forge 39.1.2

### Describe your issue

I'm not sure if this is an issue with KubeJS or REI, but I assume it's the latter since REI imports items that aren't in creative tabs in an odd way? I don't know
```js
onEvent('rei.hide.items', rei => {
	rei.hide([
		// tables and beehives added by Compat O' Plenty aren't hidden by this?
		/(biomesoplenty|compatoplenty|decorative_compat|supplementaries):(.*magic.*|.*umbran.*|.*palm.*)/,
		// this works fine
		/refinedstorage:(?!red).+_(controller|creative_controller|grid|crafting_grid|pattern_grid|fluid_grid|network_receiver|network_transmitter|relay|wireless_transmitter|disk_manipulator|crafter|crafter_manager|crafting_monitor|security_manager|detector)/,
		// this doesn't work either
		/biomesoplenty:potted.*/,
		// lootr blocks aren't being hidden
		/lootr:(?!trophy).*/,
	])
})
```
all of the blocks that weren't hidden, as i commented, have one thing in common: they aren't in a creative tab. What's even more confusing is that [Compat O' Plenty does actually register beehives and tables into a creative mode tab](https://github.com/ManaStar/compat-o-plenty/blob/b2e5081fdfe6046ab05ecb00d7f72903a8abc461/src/main/java/seleneandmana/compatoplenty/core/registry/CompatBlocks.java#L38), but all tables and beehives aren't in creative mode tabs once I'm in-game, but I guess that's a bug with that mod, not REI/KJS.

My current assumption is that REI is implementing things that don't have a creative menu in a way that KubeJS can't handle with hiding. I wish I could give more information, but this is all I could do. It's reproduceable with modded blocks that aren't in creative tabs.

**Comment by MaxNeedsSnacks** [comment]
Merging this into #550 since it is on a later MC version, but thank you for the pointer!
