### ISSUE TITLE
[Question] listen to unlocking of achievements

### ISSUE THREAD

**Issue by JairoQuispe** [KubeJS-Mods/KubeJS#3]
If a player gets an achievement, for example "diamonds", is it possible listen to the unlocking of that event and run a script?

**Comment by MaxNeedsSnacks** [comment]
The event you're looking for is `player.advancement`, which returns a [PlayerAdvancementEventJS](https://github.com/KubeJS-Mods/KubeJS/blob/1.12/src/main/java/dev/latvian/kubejs/player/PlayerAdvancementEventJS.java).

From there, you can get the [advancement ](https://github.com/KubeJS-Mods/KubeJS/blob/1.12/src/main/java/dev/latvian/kubejs/player/AdvancementJS.java) with `event.advancement` as well as the [player](https://github.com/KubeJS-Mods/KubeJS/blob/1.12/src/main/java/dev/latvian/kubejs/player/PlayerJS.java) (or rather, [player entity](https://github.com/KubeJS-Mods/KubeJS/tree/1.12/src/main/java/dev/latvian/kubejs/entity)) with `event.entity`.

**Comment by JairoQuispe** [comment]
Thanks. I will try.

**Comment by JairoQuispe** [comment]
events.listen("player.advancement", function(event) {
  if(event.advancement.getDisplayText() == "[Diamonds!]"){
    event.player.give("minecraft:golden_apple");
  }
});

How can I give items with enchantments and low durability ?

**Comment by MaxNeedsSnacks** [comment]
From the official KubeJS wiki, here are a couple of examples on how to get items:

```javascript
// Pass item as a string. This uses the same syntax as /give commands would.
// If an oredict entry is supplied, the first item in that entry will be selected.
"minecraft:stone_sword" //Stone Sword
"minecraft:stone_sword 1 10" //Stone Sword with damage 10
"minecraft:apple 30" //30 Apples
"minecraft:compass {display:{Name:\"Spawn\"}}"

// Pass item as JS object. Additional keys are data, count, nbt, caps.
{item: "minecraft:stone_sword"}
{item: "minecraft:stone_sword", data: 10}
{item: "minecraft:apple", count: 30}
{item: "minecraft:compass", nbt: {display: {Name: "Spawn"}}}

// item.of() works with either of the above, but explicitly returns an ItemStackJS, so you can then chain functions to change the item further. (See ItemStackJS documentation for more info)
item.of("minecraft:stone_sword")
item.of("minecraft:stone_sword").data(10)
item.of("minecraft:apple").count(30)
item.of("minecraft:compass").name("Spawn")
item.of("minecraft:compass").name("Spawn").count(30)
```

in your case, i'd recommend either using the javascript object notation or using item.of(), depending on what you prefer, so for example, if you wanted to give someone a stone sword with 10 damage and sharpness 1, you should be able to do this:

```javascript
event.player.give({
  item: "minecraft:stone_sword",
  data: 10,
  nbt: {
    Enchantments:[
      { id:"minecraft:sharpness", lvl:1 }
    ]
  }
});
```
