### ISSUE TITLE
Scripts dont load on java 1.8.0_111

### ISSUE THREAD

**Issue by Colton-Slayden** [KubeJS-Mods/KubeJS#30]
I have been having issues with my server not have recipes made through kubejs through my own finding it does not work on java 1.8.0_111 I am not sure if this is an actual issue but it might help people that pay for hosting going crazy on why it works if you launch a server on your local machine and singleplayer and the recipes work

**Comment by LatvianModder** [comment]
MC version, KubeJS version, error logs

**Comment by Colton-Slayden** [comment]
MC: 1.16.3
KubeJS: 1603.2.8.73
I dont have crash report but in debug log around line 5660ish they errors are printed. Could also just search for kubejs https://drive.google.com/file/d/1nJ1GgIK7ym48LZ1lqQMCCzrEIOMZD0mH/view?usp=sharing
