### ISSUE TITLE
JEI doesn't update properly on reload - 1.18.1

### ISSUE THREAD

**Issue by Solarius66** [KubeJS-Mods/KubeJS#301]
Hello,
I'm currently working on some recipes, and the /reload command does not seem to work properly.

When I change a recipe in server_scripts/script.js, and then type /reload in minecraft tchat, KubeJS answers there is no error, but the recipe is not changed/removed/added.

Recipes are changed when I leave the map and log-in back.

**Comment by ChiefArug** [comment]
Please check if the recipes actually work, and its not just JEI bugging out (there have been reports of that happening).

**Comment by Solarius66** [comment]
The recipe is properly removed but remains on JEI yes.
Thank you for your answer, I'll look to those issues.

**Comment by ChiefArug** [comment]
Can you update your issue to reflect that? (There currently isn't an issue tracking it despite it being known)

**Comment by ChiefArug** [comment]
I meant edit the title and description to be JEI specific (Like "JEI doesnt update properly on reload"), not close it 🙂

**Comment by ChiefArug** [comment]
A temporary fix is to `F3` + `T` to force a resource reload, however this can take a while as it refreshes all textures,

**Comment by MaxNeedsSnacks** [comment]
I haven't heard any reports of this happening on later versions, so I'm assuming this was fixed on 1.18.2?
