### ISSUE TITLE
Document how to hide an entire category from JEI

### ISSUE THREAD

**Issue by artemisSystem** [KubeJS-Mods/KubeJS#302]
Would be nice if it was possible to hide a whole JEI category (e.g. create:compacting). I initially suggested it as a JEI option, but mezz said it is possible in CraftTweaker and would be a nice suggestion to kubejs: https://github.com/mezz/JustEnoughItems/issues/2776

**Comment by ChiefArug** [comment]
This is already possible using the `jei.remove.categories` event.
```js
//client script
onEvent('jei.remove.categories', event => {
  event.remove('create:compacting')
})
```

**Comment by artemisSystem** [comment]
Ah, thanks! I don't remember seeing this in the docs anywhere, is it documented?

**Comment by Spiker985** [comment]
@ChiefArug You have wiki edit access now, right? You mind adding that snippet?

https://mods.latvian.dev/books/kubejs/page/jei-integration
https://mods.latvian.dev/books/kubejs/page/rei-integration

**Comment by ChiefArug** [comment]
Done 👍
