### ISSUE TITLE
Crash when using /reload

### ISSUE THREAD

**Issue by Goldenlion5648** [KubeJS-Mods/KubeJS#31]
I used the /reload command and it worked fine. When using it again, the pack crashed. After reloading the game, the same world loaded fine. When I tried the reload command it did not work
[server_scripts.zip](https://github.com/KubeJS-Mods/KubeJS/files/5479388/server_scripts.zip)

[crash-2020-11-02_23.14.43-client.txt](https://github.com/KubeJS-Mods/KubeJS/files/5479359/crash-2020-11-02_23.14.43-client.txt)

Using kubejs-1603.2.8.73
1.16.3 Forge

**Comment by Goldenlion5648** [comment]
Never mind, was not being caused by KubeJS

**Comment by Unhook** [comment]
What was the cause then @Goldenlion5648 ?
