### ISSUE TITLE
Recipes changed with .replaceInput() don't load on startup

### ISSUE THREAD

**Issue by livewatch02** [KubeJS-Mods/KubeJS#313]
### Minecraft Version

1.18.2

### KubeJS Version

kubejs-forge-1802.5.1-build.340

### Rhino Version

rhino-forge-1801.1.9-build.135

### Architectury Version

 architectury-4.2.49

### Forge/Fabric Version

Forge - 40.0.54

### Describe your issue

As stated in the titel recpies changed with .replaceInput() don't load on startup. But once I do the /reload command they suddenly change.
The script I'm using:
```
onEvent('recipes', event => {
	
	//stone tools made from flint
	event.replaceInput({output: 'minecraft:stone_sword'}, 'minecraft:cobblestone', 'minecraft:flint')
	event.replaceInput({output: 'minecraft:stone_axe'}, 'minecraft:cobblestone', 'minecraft:flint')
	event.replaceInput({output: 'minecraft:stone_pickaxe'}, 'minecraft:cobblestone', 'minecraft:flint')
	event.replaceInput({output: 'minecraft:stone_shovel'}, 'minecraft:cobblestone', 'minecraft:flint')
	event.replaceInput({output: 'minecraft:stone_hoe'}, 'minecraft:cobblestone', 'minecraft:flint')
	event.replaceInput({output: 'minecraft:stone_swor'}, 'minecraft:cobblestone', 'minecraft:flint')
  
})
```

**Comment by Prunoideae** [comment]
Using cobblestone directly won't work here (actually I wonder why it works after /reload in your case), you need to write like this:

```js
onEvent("recipes", event => {
    event.replaceInput({ output: "minecraft:stone_sword" }, "#minecraft:stone_crafting_materials", "minecraft:flint")
})
```

**Comment by livewatch02** [comment]
After using the "#minecraft:stone_tool_materials" tag it worked for me. But I'm also wondering why /reload worked in the first example.

**Comment by livewatch02** [comment]
No, it's fixed.
