### ISSUE TITLE
Items being voided from RS, IE, ES upon a scheduled restart 

### ISSUE THREAD

**Issue by ShadowMagnus000** [KubeJS-Mods/KubeJS#315]
### Minecraft Version

1.18.2

### KubeJS Version

1802.5.1-build.340.jar

### Rhino Version

forge-1801.1.9-build.135.jar

### Architectury Version

4.2.49.jar

### Forge/Fabric Version

Forge 40.0.52

### Describe your issue

Upon a scheduled restart, any items that were in inventories from the following modded item have their items voided:

Immersive Engineering:

Engineer's Crafting Table 
Engineer's Workbench

Refined Storage:
Storage drives

Expanded Storage
all storage items 

All seem to be conflicts with kubejs from talking to each mod dev who suggested opening this issue for you to look up. Thanks and have a great day.

**Comment by MaxNeedsSnacks** [comment]
Do you have any references to those issues or logs that would corroborate this? This is the first time I'm hearing about this tbf :/

**Comment by ShadowMagnus000** [comment]
No logs, but upon testing without kubejs (turned off via gdlauncher), nothing got voided on Immersive's crafting table or workbench, also it affects the IE blueprints not showing any of the recipes. Looks like the main mod to be affected is Immersive Engineering with the others being random bugs(tested again, nothing was voided on refined or extended storages).

**Comment by MaxNeedsSnacks** [comment]
Have you updated Immersive within the last two weeks or so? The voiding issue should've gotten fixed in https://github.com/BluSunrize/ImmersiveEngineering/issues/5248

**Comment by ShadowMagnus000** [comment]
yes using latest IE 1.18.2-8.0.1-147.jar released 2 days ago

**Comment by Darkere** [comment]
Any chance you can you grab a latest.log from when it voids the items?

**Comment by ShadowMagnus000** [comment]
[latest.log](https://github.com/KubeJS-Mods/KubeJS/files/8507267/latest.log)

**Comment by Spiker985** [comment]
Seeing as it's been 2 months, with no other mention of this I'm going to close this. If it's still happening, feel free to reopen.
