### ISSUE TITLE
Painter API's texture feature does not work

### ISSUE THREAD

**Issue by ChiefArug** [KubeJS-Mods/KubeJS#316]
### Minecraft Version

1.18.2

### KubeJS Version

kubejs-forge-1802.5.1-build.335

### Rhino Version

rhino-forge-1801.1.9-build.135

### Architectury Version

architectury-4.2.49

### Forge/Fabric Version

40.0.52

### Describe your issue

When trying to specify a texture for a rectangle it just shows random characters.

Using the example script from the wiki simplified a bit.
```js
onEvent('player.logged_in', event => {
	event.player.paint({
		example_rectangle: {
			type: 'rectangle',
			x: 10,
			y: 10,
			w: 320,
			h: 320,
			texture: 'kubejs:textures/item/diamond_ore.png',
			draw: 'always'
		}
	})
})
```
I renamed the default item texture to `diamond_ore.png`
Results: 
![image](https://user-images.githubusercontent.com/73862885/163898068-c939c26d-9519-4434-b451-dc7e4028739f.png)

**Comment by MaxNeedsSnacks** [comment]
Is this still an issue or did Lat just forget to close this?

**Comment by ChiefArug** [comment]
Yep, Lat just forgot to close it.
