### ISSUE TITLE
Painter is broken in 1.18.2

### ISSUE THREAD

**Issue by amoooooo** [KubeJS-Mods/KubeJS#321]
### Minecraft Version

1.18.2

### KubeJS Version

1802.5.1-build.353

### Rhino Version

1801.1.9-build.135

### Architectury Version

4.2.50

### Forge/Fabric Version

Forge 40.1.0

### Describe your issue

Expanding upon #316, Painter seems to struggle drawing anything more than white text. Any rectangles drawn are black, textures seem to not work, and there is constant `Unknown Painter type: ` spam in the client log. The code that causes this can be seen [here](https://github.com/amoooooo/kjs-test/blob/main/kubejs/client_scripts/ui.js).

**Comment by MaxNeedsSnacks** [comment]
Are any of these issues still a thing?

**Comment by amoooooo** [comment]
Unknown painter type spam is still present last i checked. I get why it exists but... It has made my logs 1m+ lines long. Sure my code is probably the cause of the spam but _i dont think it should spam that much_

**Comment by MaxNeedsSnacks** [comment]
Much like #316, is this still an issue or did Lat just never close this?

**Comment by amoooooo** [comment]
was never closed
