### ISSUE TITLE
"Non [a-z0-9_.-] character in namespace of location" on armor render

### ISSUE THREAD

**Issue by Javiondox** [KubeJS-Mods/KubeJS#330]
### Minecraft Version

1.18.2

### KubeJS Version

kubejs-fabric-1802.5.1-build.363

### Rhino Version

rhino-fabric-1801.1.9-build.135

### Architectury Version

architectury-4.2.50

### Forge/Fabric Version

0.13.3 (FABRIC)

### Describe your issue

I was making a custom armor, with its own custom tier. The items get the item images correctly, but when you equip the armor and/or render the player/mob with that equipped, it crashes. I was redirected to open an issue here after asking on discord.

I attached the lastest.log, the startup script and image of the file structure.

> Non [a-z0-9_.-] character in namespace of location: textures/models/armor/kubejs:mokoko_helmet_layer_1.png

It seems like kubejs tries to add the namespace to the armor texture.

This could be related, as it is a render error that happens after joining the world with the armor equipped.

> Error executing task on Client
java.lang.NullPointerException: Cannot invoke "net.minecraft.class_1657.method_5667()" because "p0" is null

![2022-04-30_12-54](https://user-images.githubusercontent.com/57767414/166105562-23b536b5-4fd6-431e-965c-ffd10e130b6f.png)
```js
onEvent('item.registry.armor_tiers', event => {
  event.add('mokoko', tier => {
    tier.durabilityMultiplier = 15
    tier.slotProtections = [1, 3, 2, 1]
    tier.enchantmentValue = 25
    tier.equipSound = 'minecraft:item.armor.equip_leather'
    tier.repairIngredient = 'minecraft:leather'
    tier.toughness = 0.0
    tier.knockbackResistance = 0.0
  })
}) 

onEvent('item.registry', event => {
    event.create('mokoko_helmet','helmet').tier('mokoko').displayName('Mokoko hood')
    event.create('mokoko_chestplate', 'chestplate').tier('mokoko').displayName('Mokoko body')
    event.create('mokoko_leggings', 'leggings').tier('mokoko').displayName('Mokoko pants')
    event.create('mokoko_boots', 'boots').tier('mokoko').displayName('Mokoko boots')
})
```

Further testing has shown that changing the tier to 'iron' also crashes.

### Lastest.log
[latest.log](https://github.com/KubeJS-Mods/KubeJS/files/8596902/latest.log)

**Comment by MaxNeedsSnacks** [comment]
Fixed by #332, currently pending a dev build and will be merged in
to a release later
