### ISSUE TITLE
Custom Fluid failing to register Forge

### ISSUE THREAD

**Issue by Aspurgus** [KubeJS-Mods/KubeJS#333]
### Minecraft Version

1.18.2

### KubeJS Version

1802.5.1-build.372

### Rhino Version

1801.1.9

### Architectury Version

4.2.50

### Forge/Fabric Version

Forge 40.1.0

### Describe your issue

I wrote a short startup script to add custom fluids, but when I start the game they failed to load. I've tested it while using the example scripts on the wiki as well as the ones I wrote, which were just the same with a few name changes. In the game, I don't see the bucket items and can't use the fluid in recipes (ones that I wrote
[foodstuffs_fluid.txt](https://github.com/KubeJS-Mods/KubeJS/files/8597486/foodstuffs_fluid.txt)
) the file is saved as a .js

**Comment by Aspurgus** [comment]
This is the recipe file using kubejs create, 1802.2.1-build.16, I replaced "kubejs:dough" with "create:honey" to make sure it worked
[recipes.txt](https://github.com/KubeJS-Mods/KubeJS/files/8597491/recipes.txt)

**Comment by amoooooo** [comment]
It's different than the wiki, as it's outdated. Do it like this.
```js
event.create("Name")
            .displayName("Name")
            .thinTexture("Color")
            .bucketColor("Color")
```

**Comment by Aspurgus** [comment]
oh thanku thanku
