### ISSUE TITLE
Add a way to modify the ItemToolTip-border

### ISSUE THREAD

**Issue by 3x1t-5tyl3** [KubeJS-Mods/KubeJS#334]
### Describe the feature

This would be a way to colorize or add borders (according to a texture or similar) in order to prettify the border.

Especially due to the nature of KJS of being able to define everything via JS it would be amazing and the possibilites would be significantly higher in order to generate them instead of having to hardcore them.

### Additional info

Having a nice way to adjust the item border similar to https://www.curseforge.com/minecraft/mc-mods/legendary-tooltips I think would be a great addition to KubeJS.

The maintainer of LegendaryTooltips doesn't seem to be active anymore due to burn out tho.

I'm aware of the existance of it, but I personally think the possibilities especially for dynamically generating them would be amazing.

**Comment by Prunoideae** [comment]
Tooltip rendering is on Minecraft by default, altering such behavior will require a mixin. It is unlikely for KubeJS to implement such a feature by itself, at least it will not be at high priority.

**Comment by ChiefArug** [comment]
The best option would be talking to the author of that tooltip mod you mentioned and asking if they can add KubeJS support.

**Comment by ChiefArug** [comment]
I am going to close this as it is **very** unlikely for KubeJS to natively support this, it seems like the [Legendary tooltips](https://www.curseforge.com/minecraft/mc-mods/legendary-tooltips) mod that you mentioned has an extensive config that you could use, and some of the things it can base tooltips on can be modified with KubeJS (Nbt, Tooltip text), which could allow you to do some dynamic border changing.
