### ISSUE TITLE
[Windows Defender] Quarantining KubeJS on modpack downloads

### ISSUE THREAD

**Issue by itsdinkd** [KubeJS-Mods/KubeJS#336]
### Minecraft Version

1.18.2

### KubeJS Version

1802.5.1-build-357

### Rhino Version

1801.1.9

### Architectury Version

4.3.53

### Forge/Fabric Version

0.13.3

### Describe your issue

https://github.com/ShetiPhian/Localizations-and-Issues/issues/349

As mentioned to ShetiPhian, people who are downloading my modpack "Another Quality Modpack 2" are getting false negatives of viruses due to Windows Defender sucking ass. They download from CF, and if they have windows defender, 9/10 several mods are getting quarantined. 

I wanted to give you a heads up, as ShetiPhian also suggested. I will be reporting to the other mods that were falsely identified as a virus. 

![image](https://user-images.githubusercontent.com/35115304/166414505-bc95e9c5-2e4f-4542-8787-bd800a765b4d.png)

**Comment by MaxNeedsSnacks** [comment]
Yeah, a bunch of mods were false-flagged by Defender recently and we have no idea why that is; this should be fixed with the new virus definitions though, since I know people submitted samples to MS

**Comment by itsdinkd** [comment]
For anyone receiving the virus still 

![image](https://user-images.githubusercontent.com/35115304/167265859-d7ad7a85-a440-4a76-add0-9942ae41dea5.png)
