### ISSUE TITLE
[1.18.2] Integrated Dynamics squeezer recipes with tag inputs cannot be loaded 

### ISSUE THREAD

**Issue by TheLMiffy1111** [KubeJS-Mods/KubeJS#344]
### Minecraft Version

1.18.2

### KubeJS Version

kubejs-forge-1802.5.1-build.331

### Rhino Version

rhino-forge-1801.1.9-build.135

### Architectury Version

architectury-forge-4.1.41

### Forge/Fabric Version

forge-1.18.2-40.1.19

### Describe your issue

![image](https://user-images.githubusercontent.com/6522061/167310484-8f5f1966-1098-4fd6-84fe-b934e8db81fb.png)
Integrated Dynamics recipes that have their outputs described by tags are unable to be parsed by KubeJS and do not fallback to vanilla, therefore not being loaded. This seems to be caused by tags being empty during recipe loading in 1.18.2.

**Comment by MaxNeedsSnacks** [comment]
You're... pretty far behind on KubeJS versions here. I did my best at fixing tags inside of KubeJS in this commit https://github.com/KubeJS-Mods/KubeJS/commit/df20a5169f426099e2c062b5d2bcd78f776697ae (build.375), and in general, ID recipes have been a major pain point for a *while*, so I'd have to recheck whether things are still broken

**Comment by TheLMiffy1111** [comment]
will check with build.395

**Comment by TheLMiffy1111** [comment]
Issue persists with build.395

**Comment by MaxNeedsSnacks** [comment]
Hmm, could you give me some example recipe JSONs of squeezer recipes? I have a feeling ID's recipe structure may have changed significantly

**Comment by TheLMiffy1111** [comment]
https://github.com/CyclopsMC/IntegratedDynamics/blob/master-1.18/src/main/resources/data/integrateddynamics/recipes/squeezer/ore/raw_iron.json

**Comment by MaxNeedsSnacks** [comment]
Given that the tag context is technically ready before deserialisation, I could probably move that call up a little, let me test it out (also disregard that current "fix" commit it's mostly a refactor of ItemStackJS to account for result ingredients with chance)

**Comment by MaxNeedsSnacks** [comment]
^ That above commit should be ready to be downloaded off Maven in about 3-5 minutes, mind giving that a try when it's ready?

**Comment by MaxNeedsSnacks** [comment]
https://mvn.saps.dev/minecraft/dev/latvian/mods/kubejs-forge/1802.5.1-build.401/kubejs-forge-1802.5.1-build.401.jar here's the artifact link for reference ^^

**Comment by TheLMiffy1111** [comment]
https://github.com/KubeJS-Mods/KubeJS/commit/d91be7356b9c444d860c1a345be46239e3dbd231#diff-4a2d5685cbdaadb1d8342557be86efcffa2c61bf0deb3ba00655f21e73d44d44L482

The fix doesn't work yet as it seems like like this line was accidentally deleted

**Comment by TheLMiffy1111** [comment]
Issue is resolved in build.403
