### ISSUE TITLE
[bug] item.destroyed never firing when it should

### ISSUE THREAD

**Issue by AmmoniumX** [KubeJS-Mods/KubeJS#347]
### Minecraft Version

1.16.5

### KubeJS Version

1605.3.19-build.299

### Rhino Version

1605.1.5-build.75

### Architectury Version

1.31.60

### Forge/Fabric Version

Forge 36.2.34

### Describe your issue

Whenever trying to use `item.destroyed` in a file on \server-scripts\, the event never gets fired.

Example code:
```
onEvent("item.destroyed", event => {
	console.log('item death');    
})
```
"item death" will never get logged whenever destroying an item by explosion, cactus, fire, or natural despawning.

### Crash report/logs

No response

**Comment by MaxNeedsSnacks** [comment]
Not exactly a bug, this is more because the underlying Forge event, `PlayerDestroyItemEvent`, only triggers when a player uses up an item inside of a craft or consumes an item by using it on something else... (we might honestly have to remove that event since it seems rather unneccessary)
