### ISSUE TITLE
Crash at client start

### ISSUE THREAD

**Issue by TheButterbrotMan** [KubeJS-Mods/KubeJS#349]
### Minecraft Version

1.18.2

### KubeJS Version

1802.5.2-build.403.jar

### Rhino Version

1802.1.10-build.145.jar

### Architectury Version

4.4.59

### Forge/Fabric Version

0.13.3

### Describe your issue

Is crashing at start of client

### Crash report/logs

https://bytebin.lucko.me/iUUdTzdt7d

**Comment by MaxNeedsSnacks** [comment]
This seems not directly related to KubeJS, plus there is a mixin here `redirect$fhj000$redirectOnCreateLevel` which I can't identify unfortunately. Can you try loading in without DashLoader please?

**Comment by TheButterbrotMan** [comment]
https://github.com/qouteall/ImmersivePortalsMod/blob/e938cf6b51747deaed7e6b3bdf9fc46a55f09780/src/main/java/qouteall/imm_ptl/peripheral/mixin/client/altius_world/MixinCreateWorldScreen.java

https://github.com/qouteall/ImmersivePortalsModForForge/blob/11f4665ac1a56a01d5049aedcccdb45bd9abc7e8/src/main/java/com/qouteall/imm_ptl_peripheral/mixin/client/altius_world/MixinCreateWorldScreen.java

**Comment by TheButterbrotMan** [comment]
Maybe its this?

**Comment by TheButterbrotMan** [comment]
Removing my kubejs folder (with my custom scripts), seems to solve the problem. But it worked before the new update, so what could be wrong there?

[kubejs.zip](https://github.com/KubeJS-Mods/KubeJS/files/8655528/kubejs.zip)
