### ISSUE TITLE
Added shapeless recipes do not respect input items nbt

### ISSUE THREAD

**Issue by zigman32** [KubeJS-Mods/KubeJS#362]
### Minecraft Version

1.18.2

### KubeJS Version

1802.5.2-build.428

### Rhino Version

1802.1.12-build.171

### Architectury Version

4.4.60

### Forge/Fabric Version

Forge 40.1.14

### Describe your issue

When trying to create a shapeless recipe where one of the input items requires specific nbt, the recipe works regardless of weather or not the item has the specified nbt. Shaped recipes do not have this issue.

**Comment by MaxNeedsSnacks** [comment]
Can you provide the script snippet you used to create the recipe please? (the entire event handler)
