### ISSUE TITLE
Issue with /reload

### ISSUE THREAD

**Issue by taraxsmallboy** [KubeJS-Mods/KubeJS#373]
### Minecraft Version

1.18.2

### KubeJS Version

1802.5.4-build.480.jar

### Rhino Version

1802.1.13-build.175.jar

### Architectury Version

4.4.68.jar

### Forge/Fabric Version

40.1.45

### Describe your issue

When I typed /reload it didnt reload the recipes but it stayed the same until i restart minecraft

**Comment by ChiefArug** [comment]
This is very little to go off, can you provide the latest.log please?

**Comment by ChiefArug** [comment]
Closing due to no response
