### ISSUE TITLE
Recipes do not work, but other server scripts do

### ISSUE THREAD

**Issue by PseudonymousColby** [KubeJS-Mods/KubeJS#374]
### Minecraft Version

1.18.2

### KubeJS Version

1802.5.3-build.467

### Rhino Version

1802.1.13-build.175

### Architectury Version

4.4.68

### Forge/Fabric Version

40.1.30

### Describe your issue

Hello. I am having a strange issue that I have been pulling my hair out for a while over. For some reason, the recipes events in my server scripts folder and my scripts.js file do not work, but the starting inventory event does. Players load in with all the items they are supposed to, but custom recipes will not work. KubeJS reloads with no errors, and there is no indication anywhere that anything is wrong. Now, I will admit I am unfamiliar with the intricacies of KubeJS or JavaScript in general. I'm an amateur modpack maker doing it for my friends. However, I've used both these event types in the past with success, which is why I am so confused.

There is no urgency on fixing this, as the recipes are added bonuses but not necessary for gameplay. I'll paste below what my scripts.js from the server scripts folder looks like, hopefully someone can help me.

Cheers, and thanks in advance.

scripts.js:
https://pastebin.com/3dKshkW2

**Comment by PseudonymousColby** [comment]
@MaxNeedsSnacks I changed it to "output" as the wiki has it, but the recipes still do not work. What am I doing wrong?

**Comment by MaxNeedsSnacks** [comment]
I'd check your log files to see if anything else is up, I haven't checked your entire script for errors yet so there might be something else in there.

Also, as a general note, whenever you're asking script-related questions like this, our Discord is usually the place to go, feel free to join it here if you wanna: https://discord.gg/bPFfH6P

**Comment by PseudonymousColby** [comment]
Thanks, I will check it out
