### ISSUE TITLE
Crash on startup on Fabric

### ISSUE THREAD

**Issue by Vapaman** [KubeJS-Mods/KubeJS#375]
### Minecraft Version

1.18.2

### KubeJS Version

kubejs-fabric-1802.5.4-build.480

### Rhino Version

rhino-fabric-1802.1.13-build.179

### Architectury Version

architectury-4.4.70

### Forge/Fabric Version

0.14.7

### Describe your issue

Game crashes on startup. Crash report points to KubeJS.

### Crash report/logs

https://pastebin.com/0vKSET6e

**Comment by ChiefArug** [comment]
`There were startup script syntax errors! See logs/kubejs/startup.txt for more info`
Whoever made that pack needs to fix their scripts.

**Comment by Vapaman** [comment]
Ah S***

**Comment by Vapaman** [comment]
It was now twilight forest causing a crash
