### ISSUE TITLE
recipe replaceOutput when original is multiple items

### ISSUE THREAD

**Issue by BrewingCoder** [KubeJS-Mods/KubeJS#383]
### Minecraft Version

1.18.2

### KubeJS Version

1802.5.4-build.492

### Rhino Version

1802.1.14-build.182

### Architectury Version

4.5.74

### Forge/Fabric Version

Forge 1.18.2-40.1.51

### Describe your issue

Example of script to reduce # of torches:

`event.replaceOutput({},'4x minecraft:torch','minecraft:torch')`

Is it incorrect of me to assume that this would work?

**Comment by Spiker985** [comment]
replaceOutput, and replaceInput only replace the associated item - they do not replace the count of the item
