### ISSUE TITLE
Whenever chat is cancelled, the player chats a weird string

### ISSUE THREAD

**Issue by TheQKnight** [KubeJS-Mods/KubeJS#385]
### Minecraft Version

1.19

### KubeJS Version

kubejs-fabric-1900.5.5-build.12.jar

### Rhino Version

rhino-fabric-1802.1.14-build.182.jar

### Architectury Version

architectury-5.7.27-fabric.jar

### Forge/Fabric Version

0.14.7

### Describe your issue

Using a simple script to cancel user chat like so
`onEvent('player.chat', (event) => {
  event.cancel()
 })`

results in making the user say the following string every time chat is entered

![image](https://user-images.githubusercontent.com/17223871/174459176-a0d0ce29-85c1-45bc-a9d1-138e159f3702.png)

**Comment by ChiefArug** [comment]
This probably has something to do with Mojang now signing chat messages (as part of the ability to now report people).

**Comment by MaxNeedsSnacks** [comment]
lmao @shedaniel nice internal string you got here :p

**Comment by shedaniel** [comment]
shit

**Comment by MaxNeedsSnacks** [comment]
We.. should probably see if we can redo the chat event somehow I'm guessing? :P

**Comment by MaxNeedsSnacks** [comment]
Seeing as this is an Architectury issue, I'm going to be closing this on our end; a fix on their side should be coming soon

**Comment by ChiefArug** [comment]
Relevant PR in Arch: https://github.com/architectury/architectury-api/pull/299 (pretty sure)
