### ISSUE TITLE
[1.18.2] runCommandSilent seems to no longer works updating from 467 to 492

### ISSUE THREAD

**Issue by Raidobw2** [KubeJS-Mods/KubeJS#389]
### Minecraft Version

1.18.2

### KubeJS Version

1802.5.4-build.492

### Rhino Version

1802.1.14-build.186

### Architectury Version

4.5.74

### Forge/Fabric Version

Forge 40.1.51

### Describe your issue

I've updated from KJS build 467 to build 492 on 1.18.2 and the runCommandSilent (or something linked to it) seems to have stopped working.

Here's the logon script: https://paste.feed-the-beast.com/view/f6ec10da (FTB Plexiglass Mountain 1.1.0 in-dev)
![image](https://user-images.githubusercontent.com/17010632/174536373-69f469c5-9615-4726-a954-162bcdc9c2ea.png)
![image](https://user-images.githubusercontent.com/17010632/174536378-95dbfb17-9cc4-4ff4-800f-19187900e16e.png)
I have the starting items in 492, but nothing was sent to chat as you can see. Both are new worlds, each after a relaunch of the game.

Thanks for checking it out in advance

### Crash report/logs

https://paste.feed-the-beast.com/view/f6ec10da

**Comment by ChiefArug** [comment]
Make sure that the command isn't erroring by using runCommand instead of runCommandSilent. If it runCommand errors it shows up in the latest.log, if runCommandSilent errors it doesnt show up anywhere

**Comment by MaxNeedsSnacks** [comment]
EntityJS.getName returns a Component, not a String, please use EntityJS.toString or EntityJS.getName().getString()

**Comment by Raidobw2** [comment]
Worked, thanks!
