### ISSUE TITLE
Using Chest modify loot table method creates a new loot table.

### ISSUE THREAD

**Issue by FloridaMen** [KubeJS-Mods/KubeJS#394]
### Minecraft Version

1.18.2

### KubeJS Version

1802.5.4-build.502

### Rhino Version

1802.1.14-build.186

### Architectury Version

4.5.75

### Forge/Fabric Version

Fabric 0.14.8

### Describe your issue

When using the server script to modify chest loot tables, if the loot table address does not start with "modid:chest," then kubejs will automatically create a new loot address. Example:
My script is event.modify("betterdungeons:spider_dungeon/chests/egg_room", table => {})
This will not actually change the loot table at "betterdungeons:spider_dungeon/chests/egg_room" but create a new one with the modifications at "betterdungeons:chests/spider_dungeon/chests/egg_room". This means that upon world generation, only the original script will appear, unmodified.

**Comment by ChiefArug** [comment]
You need to use the generic loot table event if the mod does not use the same loot table path conventions that Minecraft uses.
