### ISSUE TITLE
Can't lock recipes behind stage

### ISSUE THREAD

**Issue by lamaprogramer** [KubeJS-Mods/KubeJS#396]
### Minecraft Version

1.18.2

### KubeJS Version

kubejs-fabric-1802.5.4-build.502

### Rhino Version

 rhino-fabric-1802.1.14-build.188

### Architectury Version

architectury-4.5.75-fabric

### Forge/Fabric Version

0.14.7

### Describe your issue

Using `.stage()` on recipes doesn't work, minimum code to reproduce:
```javascript 
onEvent('recipes', event => {
    event.shapless("minecraft:diamond", ['apple"]).stage("someRandomStage")
})
```

**Comment by MaxNeedsSnacks** [comment]
I doubt the recipe stages mod exists for Fabric, does it?
