### ISSUE TITLE
Custom Block Item Properties are not applied

### ISSUE THREAD

**Issue by LeftChaotix** [KubeJS-Mods/KubeJS#401]
### Minecraft Version

1.19

### KubeJS Version

kubejs-forge-1900.5.5-build.23

### Rhino Version

rhino-forge-1802.1.14-build.190

### Architectury Version

architectury-5.7.28-forge

### Forge/Fabric Version

Forge 41.0.45

### Describe your issue

inability to edit item properties for custom blocks. (.item method don't worky)

ex script (placed within startup folder) : 

`onEvent('block.registry', event => {
	event.create('report_block', 'basic')
		.material('stone')
		.hardness(6)
		.lightLevel(0.6)
		.resistance(1200)
		.tagBlock('minecraft:mineable/pickaxe')
		.item(item => {
			item.displayName('Item go brrr')
			item.group('tools')
			item.tooltip("I am an item. Wow.")
			console.log("haha item go BRRRRRRR");
		})
})`

**Comment by MaxNeedsSnacks** [comment]
Fixed on 1.18, and also going to be fixed in KubeJS 6.0 once that releases for 1.19 ^^
