### ISSUE TITLE
[Suggestion] Verbose output with "Skipping loading recipe"

### ISSUE THREAD

**Issue by Akaitatsu** [KubeJS-Mods/KubeJS#41]
I am building a mod pack and get a lot of "Skipping loading recipe" messages. Would it be possible to get the recipes in the output of this message so I can troubleshoot the reason they are being skipped?

Let me know if you need more details.

**Comment by LatvianModder** [comment]
[Latest update](https://jenkins.latmod.com/job/KubeJS-1.16.2/109/) (not on Curseforge right now due to it being down) has better messages. Usually skipped recipes because of conditions aren't an issue, they are just optional recipes. Failed to parse recipes will have the error printed

**Comment by Akaitatsu** [comment]
Will the 1.15.2 version be getting the update?

**Comment by LatvianModder** [comment]
Nope, 1.16 development only from now on, sorry

**Comment by Akaitatsu** [comment]
That's OK. That might be just what I need to abandon 1.15.2 and move on to the new hotness.

Thank you for your fine work!
