### ISSUE TITLE
make a thing that copy recipe ID made by kubejs 

### ISSUE THREAD

**Issue by Leclowndu93150** [KubeJS-Mods/KubeJS#410]
### Describe the feature

i'd like a command that copy the recipe ID of a recipe made by kubejs

example: imagine i change the recipe ID for an iron ingot and it give me something like minecraft:kjs_dfzeofgaehgiùehùaùega.

thats pretty annoying to copy so you can type the command /kubejs hand recipeid
and it gives you all the recipe ids of the item

**Comment by ChiefArug** [comment]
You cannot change the recipe id of a recipe, you can only remove one recipe and add back another.

When you make a recipe with KubeJS it gets an autogenerated id like you said, but you can override that by putting `.id('your/id_here')` after the last bracket of the recipe, like so: 
```js
event.shapeless('minecraft:diamond', [
  'minecraft:coal',
  'minecraft:charcoal'
]).id('coal_to_diamonds')
```
That will make a recipe with the id of `minecraft:coal_to_diamonds`. You can also specify a namespace if you want (like `epic_modpack:epic_recipe`).

Finally, if you use the mod REI (alternative to JEI) I believe it has a feature to allow you to copy any recipe id with a keyboard shortcut.

**Comment by Leclowndu93150** [comment]
this was for the recipe printer mod :(
