### ISSUE TITLE
KubeJS recipe errors due to tags not being loaded on initial worldgen using Terraforged

### ISSUE THREAD

**Issue by mobliano** [KubeJS-Mods/KubeJS#412]
### Minecraft Version

1.18.2

### KubeJS Version

1802.5.4-build.510

### Rhino Version

1802.1.14-build.190

### Architectury Version

4.5.76

### Forge/Fabric Version

Forge 40.1.54

### Describe your issue

When generating a world for the first time (locally not on server) and using Terraforged (world type = terraforged), I am receiving 198 recipe errors and all crafting recipes are missing. This only happens on initial worldgen.

- Logged errors are mostly related to immersiveengineering recipes, but there are also other mod recipes reporting errors.
- When looking at a recipe for any item (i.e. oak planks) via JEI, there are no recipes.
- If I leave the world/game and go back in, all recipes load correctly. (Only happens on initial worldgen)
- If I generate a new world using the default world generator there are no issues.
- If I generate a new world on a server there are no issues. (I have only tested this once and I have no idea why it worked).
- If I remove KubeJS there are no issues.
- This occurs with custom kubejs scripts, as well as with a freshly generated kubejs directory (no custom scripts).
- I can repro this every time using the attached CF profile for my modpack.

This appears to be related to initial world generation using terraforged and kubejs. I suspect there is an incompatibility with how terraforged uses tags and kubejs.

latest.log reporting the errors described above:
[latest.log](https://github.com/KubeJS-Mods/KubeJS/files/9074060/latest.log)

latest.log when kubejs has been removed:
[latest.log](https://github.com/KubeJS-Mods/KubeJS/files/9074067/latest.log)

Exported Curseforge profile:
[WhimsyhellDev-3.0b.zip](https://github.com/KubeJS-Mods/KubeJS/files/9074072/WhimsyhellDev-3.0b.zip)

**Comment by KangyKSLG** [comment]
I'm also getting this error, here is the output from /kubejs errors
[server.txt](https://github.com/KubeJS-Mods/KubeJS/files/9120481/server.txt)
