### ISSUE TITLE
Error occurred while handling event 'tags.items'

### ISSUE THREAD

**Issue by jbwincek** [KubeJS-Mods/KubeJS#414]
### Minecraft Version

1.18.2

### KubeJS Version

1802.5.4-build.492

### Rhino Version

1802.1.14-build.186

### Architectury Version

4.5.74-fabric

### Forge/Fabric Version

fabric-api-0.56.1+1.18.2

### Describe your issue

Running an All of Fabric 5 server, we just added Mining Dimensions Fabric mod and now we have this error message. 

During startup we get an error that says:
`[Server thread/INFO]: [1] Error occurred while handling event 'tags.items': Wrapped java.lang.IllegalArgumentException: message (server_scripts:unification/materials.js#93)`

in the server.log file it says: 

`[ERR  ] Error occurred while handling event 'tags.items': Wrapped java.lang.IllegalArgumentException: message (server_scripts:unification/materials.js#93)`

The server does start though, and seems to run fine. 

### Crash report/logs

https://pastebin.com/azMrCkZm

**Comment by MaxNeedsSnacks** [comment]
This is an issue with AOF5's unification script, not with KubeJS. Please talk to the AOF5 team to figure out how their scripts work :P
