### ISSUE TITLE
The game cannot be started

### ISSUE THREAD

**Issue by Epresin** [KubeJS-Mods/KubeJS#415]
### Minecraft Version

1.18.2

### KubeJS Version

1802.5.2-build.415

### Rhino Version

1802.1.13-build.175

### Architectury Version

4.5.76

### Forge/Fabric Version

Fabric 0.14.8

### Describe your issue

The game crashed at startup.
[latest.log](https://github.com/KubeJS-Mods/KubeJS/files/9078595/latest.log)
[crash-2022-07-10_14.52.03-client.txt](https://github.com/KubeJS-Mods/KubeJS/files/9078597/crash-2022-07-10_14.52.03-client.txt)
.

**Comment by Prunoideae** [comment]
Update both Rhino and KubeJS to latest first.
