### ISSUE TITLE
bug regarding renaming items using a lang file

### ISSUE THREAD

**Issue by DoneSoke** [KubeJS-Mods/KubeJS#422]
renaming an items with en_us will fail to work at all when around ~100 mods (or a select few) are added

i know this wasnt my fault because once i start disabling mods it began to work again yet when i reenable a couple it breaks again

**Comment by ChiefArug** [comment]
Can you please provide more information, such as the exact mod you found caused this?

Also, how on earth did you manage to bypass the issue template? There is quite a bit of info there that can help figure out an issue.

**Comment by DoneSoke** [comment]
i cant give an exact mod as it is not really one mod but i can export my pack so you can see for yourself

**Comment by DoneSoke** [comment]
https://drive.google.com/drive/folders/1n4o0cc-6j-fRNN6uRC5ZDaR2yA45CVA2?usp=sharing

**Comment by Spiker985** [comment]
@DoneSoke Can you provide any screenshots, logs, or errors?

Moreover, how in the world did you open an Issue without a template?

**Comment by DoneSoke** [comment]
uhhhhhhhhhhhhhhhhhhhhh i forgont

 but i fix so its good i just needed to type every mods name indvidually instead of just the modpack name
