### ISSUE TITLE
Create Mixing recipe fails despite correct syntax

### ISSUE THREAD

**Issue by kalkafox** [KubeJS-Mods/KubeJS#425]
### Minecraft Version

1.18.2

### KubeJS Version

1802.5.4-build.524

### Rhino Version

1802.1.14-build.206

### Architectury Version

4.6.77

### Forge/Fabric Version

40.1.68

### Describe your issue

On updating from 5.4.510 to 5.4.524, a new error relating to Create Mixing occurs as it prints a dubious error log relating to JSON parsing.

![Selection_040](https://user-images.githubusercontent.com/9144208/180575189-29007cdf-ce1d-4d53-ab4d-e4626b781101.png)

This recipe in particular has worked perfectly fine up until this version which was recently updated.

Also attached is a screenshot of the offending syntax, which to my understanding from the wiki, is correct.

![Selection_041](https://user-images.githubusercontent.com/9144208/180575586-43aa00f7-d322-4a5d-981e-5ff640a67278.png)\

Take care.

**Comment by MaxNeedsSnacks** [comment]
Can I get a full mod list on this please? You likely don't have KubeJS Create installed

**Comment by MaxNeedsSnacks** [comment]
Also, please do not upload screenshots or short snippets of errors scripts if possible, as it doesn't contain enough information to infer what the error may be

**Comment by kalkafox** [comment]
I appreciate your responsiveness. As it stands, it was completely erroneous on my part, and no longer warrants attention.

> please do not upload screenshots or short snippets of errors scripts if possible, as it doesn't contain enough information to infer what the error may be

Frankly, if it was an actual crash, I would have been inclined to include an actual crash log. I will not WOT this issue with multiple lines of irrelevant server output and is otherwise useless for the issue. A visual representation is good enough to be informative, it just needs a pair of eyes.
