### ISSUE TITLE
Unable to get player name

### ISSUE THREAD

**Issue by AweiDev** [KubeJS-Mods/KubeJS#430]
### Minecraft Version

1.18.2

### KubeJS Version

kubejs-fabric-1802.5.4-build.524

### Rhino Version

rhino-fabric-1802.1.14-build.206

### Architectury Version

4.6.77

### Forge/Fabric Version

Fabric 0.14.8

### Describe your issue

"event.player.name"
Unable to get player name
"event.server.tell([Text.blue('[A]').bold(), ` <${event.player.name}> ${event.message.trim();}`]); "
will output the following information
[A] <TextComponent{text='_Kasualix_', siblings=[], style=Style{ color=null, bold=null, italic=null, underlined=null, strikethrough=null, obfuscated=null, clickEvent=null, hoverEvent=null, insertion=null, font=minecraft:default}}> ???

JS : https://bytebin.lucko.me/TUC1dn9tIi

**Comment by MaxNeedsSnacks** [comment]
Use `event.player.name.string`, `event.player.name` returns a Component
