### ISSUE TITLE
Rei integration doesnt work

### ISSUE THREAD

**Issue by TheRobberPanda** [KubeJS-Mods/KubeJS#433]
### Minecraft Version

1.18.2

### KubeJS Version

kubejs-forge-1802.5.4-build.524

### Rhino Version

rhino-forge-1802.1.14-build.206

### Architectury Version

architectury-4.6.77-forge

### Forge/Fabric Version

forge 40.1.68

### Describe your issue

```
onEvent('rei.hide.items', event => {
  event.hide('beyond_earth:steel_ingot')
onEvent('rei.information.items', event => {
  event.add('beyond_earth:steel_ingot', 'NO FUNCIONA', ['NO FUNCIONA 1', 'NO FUNCIONA 2'])
  })
```
![image](https://user-images.githubusercontent.com/44844784/181068502-f400b343-1ac5-4919-9e1a-aec8222d22a1.png)
REI events do not work. The item still appears in the the REI interface and the item doesnt show extra information.

REI version: RoughlyEnoughItems-8.3.510

**Comment by MaxNeedsSnacks** [comment]
Your script as you posted it is incorrect.

```js
onEvent('rei.hide.items', event => {
  event.hide('beyond_earth:steel_ingot')
}) // end the block of the first event

onEvent('rei.information.items', event => {
  event.add('beyond_earth:steel_ingot', 'NO FUNCIONA', ['NO FUNCIONA 1', 'NO FUNCIONA 2'])
})
```

Also for script-related questions, please join our Discord as we're trying to keep GitHub strictly for bugs, poor mod interactions, and feature requests
