### ISSUE TITLE
Item registry .type() prevents further item registration

### ISSUE THREAD

**Issue by hotdog95** [KubeJS-Mods/KubeJS#434]
### Minecraft Version

1.18.2

### KubeJS Version

1802.5.4-build.524

### Rhino Version

1802.1.14-build.206

### Architectury Version

4.6.77

### Forge/Fabric Version

Forge 40.1.52

### Describe your issue

Kubejs Create Version: 1802.2.2-build.26

Any item registered in code after the use of .type('create:sequenced_assembly') does not get registered

**Comment by ChiefArug** [comment]
The format has changed and @LatvianModder still needs to update the KubeJS Create CurseForge page. The startup logs at `logs/kubejs/startup.txt` should have an error in them saying that `.type()` should no longer be used.

New format: 
```js
event.create('id', 'type').otherMethods()
```

**Comment by hotdog95** [comment]
Thanks Lat for not updating the CurseForge page ;D
