### ISSUE TITLE
Extreme Reactors' recpies don't get removed for some reason

### ISSUE THREAD

**Issue by MCEventHorizon** [KubeJS-Mods/KubeJS#44]
`events.listen('recipes', event => {

	event.remove({id: 'angelring:itemring'})
	event.remove({id: 'bigreactors:basic_reactorcasing'})
	event.remove({id: 'bigreactors:reinforced_reactorcasing'})
	event.shaped(Item.of('bigreactors:basic_reactorcasing', 2), [
		'IGI',
		'GCG',
		'IGI'
	  ], {
		I: '#forge:ingots/iron',
		G: '#forge:ingots/graphite',
		C: 'thermal:machine_frame'
	  })
	event.shaped(Item.of('angelring:itemring', 1), [
		'GHG',
		'UDM',
		'GNG'],
		{
			G: '#forge:ingots/gold',
			H: 'simplyjetpacks:jetpack_ie3',
			U: 'simplyjetpacks:jetpack_mek4',
			D: 'angelring:itemdiamondring',
			M: 'mekanism:jetpack_armored',
			N: 'minecraft:nether_star'
		}
	)
	event.shaped(Item.of('bigreactors:reinforced_reactorcasing', 2), [
		'SGS',
		'GCG',
		'SGS'
	  ], {
		S: '#forge:plates/steel',
		C: 'mekanism:steel_casing',
		G: '#forge:ingots/graphite'
	  })
})`

Rest of the recipes from here work normally, but Extreme Reactor recipes are still there:
![Screenshot_2](https://user-images.githubusercontent.com/15619786/103091250-e10c9600-45f3-11eb-8ed1-3fbffee52499.png)
![Screenshot_3](https://user-images.githubusercontent.com/15619786/103091254-e2d65980-45f3-11eb-9c76-d536f78e8321.png)

**Comment by MaxNeedsSnacks** [comment]
In `event.remove`, the `id` value refers to the **recipe id**, not the **id of the output item** (use `output` for that)

> ```js
event.remove({id: 'angelring:itemring'})
event.remove({id: 'bigreactors:basic_reactorcasing'})
event.remove({id: 'bigreactors:reinforced_reactorcasing'})
```
Either change all of these to "output" instead of "id" or get the individual recipe ids and remove them like that

**Comment by MCEventHorizon** [comment]
Alright, thank you, haven't been able to figure that out on my own.
