### ISSUE TITLE
Item duplication when specifying keepIngredient

### ISSUE THREAD

**Issue by OscarAblinger** [KubeJS-Mods/KubeJS#441]
### Minecraft Version

1.18.2

### KubeJS Version

1802.5.4-build.526

### Rhino Version

1802.1.14-build.206

### Architectury Version

4.7.78

### Forge/Fabric Version

Forge 40.1.60

### Describe your issue

When specifying `.keepIngredient` for an ingredient in a shapeless recipe, this will cause the "kept" ingredient to be duplicated if you use more than one stack of it.

To ensure that no other mod interferes, I made a quick modpack with only the above versions of the mods and JEI 1.18.2-9.7.1.232 and added the following script:

```js
// priority: 0

settings.logAddedRecipes = true
settings.logRemovedRecipes = true
settings.logSkippedRecipes = false
settings.logErroringRecipes = true

console.info('Hello, World! (You will see this line every time server resources reload)')

onEvent('recipes', event => {
	// Change recipes here
    event.shapeless('minecraft:flint', [ 'minecraft:flint', 'minecraft:diamond' ]).keepIngredient('minecraft:diamond')
})
```

It works correctly if you only put one of the kept item in, but when you put a stack of x in, it will add (x-1) to the stack on each crafting.

The logs are uneventful.

https://user-images.githubusercontent.com/25868587/182262055-424b92ed-04a3-4bb4-b154-a218718cf309.mp4

**Comment by ChiefArug** [comment]
Seems max forgot to actually close this, so will do now.
