### ISSUE TITLE
replace doesn't work

### ISSUE THREAD

**Issue by Dr-WeiAL** [KubeJS-Mods/KubeJS#445]
### Minecraft Version

1.18.2

### KubeJS Version

1802.5.4-build.533

### Rhino Version

1802.1.14-build.209

### Architectury Version

4.7.78

### Forge/Fabric Version

Forge 40.1.68

### Describe your issue

I tried using replaceOutput to replace the recipe but it doesn't work
![image](https://user-images.githubusercontent.com/47446553/183397350-4ba8342f-1f4b-4e5c-b107-61555c23dd7c.png)
![image](https://user-images.githubusercontent.com/47446553/183397799-5d63e1d1-eb6f-419b-8d2c-1cfeadd012c6.png)

**Comment by Prunoideae** [comment]
Do you have KubeJS Create installed?

**Comment by Dr-WeiAL** [comment]
Oh...my fault, I thought I didn't need to install, thanks for the reminder
