### ISSUE TITLE
The server and the client has the same version but i got report that they are not

### ISSUE THREAD

**Issue by LoliesHunter** [KubeJS-Mods/KubeJS#454]
### Minecraft Version

1.18.2

### KubeJS Version

1802.5.4-build.533

### Rhino Version

?

### Architectury Version

?

### Forge/Fabric Version

forge-40.1.68

### Describe your issue

![image](https://user-images.githubusercontent.com/111516920/185416610-f6d25757-c60f-4e86-ae94-0125efb7530f.png)

I just copied mods folder from server and iserted it into client mods folder

**Comment by ChiefArug** [comment]
You need to copy the config and kubejs folder over as well.
