### ISSUE TITLE
KubeJS randomly crashing when right-clicking an item or placing a block

### ISSUE THREAD

**Issue by fireheart3911** [KubeJS-Mods/KubeJS#461]
### Minecraft Version

1.19

### KubeJS Version

1900.5.5-build.27

### Rhino Version

1802.1.14-build.225

### Architectury Version

5.12.44

### Forge/Fabric Version

Forge 41.1.0

### Describe your issue

I am getting random crashes from what i think is KubeJS (I can't read stacktraces properly)
Those crashes all occured while either right clicking an item or placing any block.

### Crash report/logs

https://gist.github.com/fireheart3911/2bb48477316a316b093f956da7d6fe31

**Comment by ChiefArug** [comment]
Does it still happen on 1.19.2? I dont think 1.19 is getting any more updates.

**Comment by fireheart3911** [comment]
Yes, although it seems to be an compatability issue with [Apoli](https://github.com/apace100/apoli).

**Comment by ChiefArug** [comment]
How can you tell that? I can't see where in the log its mentioned as to being a contributor, and it seems very unlikely that a mod conflict could cause a NoSuchMethod error on a forge class.

**Comment by fireheart3911** [comment]
I can't reproduce the crash w/o Apoli in the modpack, thats why i assumed that.

**Comment by fireheart3911** [comment]
Even tho the game takes around 10 seconds to process right clicking if i only have KubeJS in the Modpack

**Comment by ChiefArug** [comment]
Ten seconds?? That is an awful long time.
Could you send a [gist](https://gist.github.com/) of any right click events you have when it takes 10 seconds?

**Comment by fireheart3911** [comment]
If you mean logs, there is nothing there (just me getting advancements), if you are referring to scripts, i did not change anything

**Comment by ChiefArug** [comment]
Can you run a [spark](https://www.curseforge.com/minecraft/mc-mods/spark) profile when you right click?

`/spark profiler`
right click a block
`/spark profiler --stop`

**Comment by fireheart3911** [comment]
I just realized that i forgot to update one of the dependencies, it works now. Sorry for kinda wasting your time!
