### ISSUE TITLE
[Crash]: Fabric 1.19.2

### ISSUE THREAD

**Issue by SpigotDE** [KubeJS-Mods/KubeJS#463]
### Minecraft Version

1.19.2

### KubeJS Version

5.5 build 27

### Rhino Version

1.14 build 225

### Architectury Version

6.2.43

### Forge/Fabric Version

Fabric 0.14.9

### Describe your issue

Crash on Startup with KubeJS & Rhino entires

### Crash report/logs

https://gist.github.com/SpigotDE/ae9ccabd3ad9153e5abace8cc40addc0

**Comment by SpigotDE** [comment]
I tryed it with KubeJS 6.0 build 55, with this version no crash , but the server_scripts are not working..

`onEvent('recipes', event => {
  event.remove({output: 'customportals:white_portal_catalyst'})
  event.remove({id: 'customportals:orange_portal_catalyst'})
  event.remove({id: 'customportals:magenta_portal_catalyst'})
  event.remove({id: 'customportals:light_blue_portal_catalyst'})
  event.remove({id: 'customportals:yellow_portal_catalyst'})
  event.remove({id: 'customportals:lime_portal_catalyst'})
  event.remove({id: 'customportals:pink_portal_catalyst'})
  event.remove({id: 'customportals:gray_portal_catalyst'})
  event.remove({id: 'customportals:light_gray_portal_catalyst'})
  event.remove({id: 'customportals:cyan_portal_catalyst'})
  event.remove({id: 'customportals:purple_portal_catalyst'})
  event.remove({id: 'customportals:blue_portal_catalyst'})
  event.remove({id: 'customportals:brown_portal_catalyst'})
  event.remove({id: 'customportals:green_portal_catalyst'})
  event.remove({id: 'customportals:red_portal_catalyst'})
  event.remove({id: 'customportals:black_portal_catalyst'})
  event.remove({id: 'customportals:haste_rune'})
  event.remove({id: 'customportals:gate_rune'})
  event.remove({id: 'customportals:weak_enhancer_rune'})
  event.remove({id: 'customportals:strong_enhancer_rune'})
  event.remove({id: 'customportals:infinity_rune'})
  event.remove({output: 'mcwbridges:iron_bridge'})
  event.remove({id: 'mcwbridges:iron_bridge_pier'})
  event.remove({id: 'mcwbridges:iron_bridge_stair'})
  event.remove({id: 'mcwdoors:metal_door'})
  event.remove({id: 'mcwdoors:metal_warning_door'})
  event.remove({id: 'mcwdoors:metal_hospital_door'})
  event.remove({id: 'mcwdoors:metal_reinforced_door'})
  event.remove({id: 'mcwdoors:metal_windowed_door'})
  event.remove({id: 'mcwdoors:jail_door'})
  event.remove({id: 'mcwdoors:garage_white_door'})
  event.remove({id: 'mcwdoors:garage_silver_door'})
  event.remove({id: 'mcwdoors:garage_gray_door'})
  event.remove({id: 'mcwdoors:garage_black_door'})
  event.remove({id: 'mcwtrpdoors:metal_trapdoor'})
  event.remove({id: 'mcwtrpdoors:metal_full_trapdoor'})
  event.remove({id: 'mcwtrpdoors:metal_warning_trapdoor'})
  event.remove({id: 'extraalchemy:empty_ring'})
})
`

**Comment by ChiefArug** [comment]
KubeJS 6 is a major rewrite, most (if not all) scripts will stop working.
I would reccomened not using it till there is a list of changes up about how it works.

**Comment by SpigotDE** [comment]
Oh good to know, thx

Is there a working version of 5.x for Fabric 1.19.2 somewhere?

**Comment by SpigotDE** [comment]
Alright , yeah it should be
