### ISSUE TITLE
items not showing

### ISSUE THREAD

**Issue by xX0Shadow0Xx** [KubeJS-Mods/KubeJS#466]
### Minecraft Version

1.18.2

### KubeJS Version

kubejs-forge-1802.5.4-build.510

### Rhino Version

rhino-forge-1802.1.14-build.225

### Architectury Version

architectury-4.9.83-forge

### Forge/Fabric Version

forge 40.1.73

### Describe your issue

![image](https://user-images.githubusercontent.com/89495658/186872487-0e27394a-3b5b-4c85-a0cf-8f6b31dc6b1b.png)
i downloaded kubejs create and kubejs thermal and its not showing anything help pls

**Comment by ChiefArug** [comment]
KubeJS does not add any items by default, you need to make scripts to add them yourself.

Check out this wiki page for how to make custom items: https://mods.latvian.dev/books/kubejs/page/custom-items
And you can join the discord if you need anymore help: https://discord.gg/bPFfH6P
