### ISSUE TITLE
Format Error  (localization)

### ISSUE THREAD

**Issue by BlackAures1** [KubeJS-Mods/KubeJS#468]
### Minecraft Version

1.18.2

### KubeJS Version

kubejs-forge-1802.5.4-build.533

### Rhino Version

rhino-forge-1802.1.14-build.209

### Architectury Version

architectury-4.9.83-forge

### Forge/Fabric Version

Curseforge Forge 40.1.73

### Describe your issue

Sometimes "Format Error" may appear during localization, but they do not affect anything but visuals. This happens because of some characters in other languages. Is there any way to remove this "Format Error" warning?

![image](https://user-images.githubusercontent.com/43911230/187027850-b57d76bf-ced2-4c23-b1fa-d7c98d89f794.png)

> "chapter.1.quest.1.description.1": "▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬\n■ Хочешь пройти по пути настоящих драконов? Тогда тебе сюда. Задания можно проходить в любом порядке. За многие из них вы будете получать награды, но самое важное это информация о модах и изменениях в них.\n▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬\n■ Полный список заданий можно найти в меню слева. Здесь только самые общие задания.\n▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬\n■ Для выполнения некоторых заданий требуется подтверждение прочтения. Для этого нужно просто нажать галочку слева от награды. Прежде чем забирать саму награду, обязательно освободите инвентарь.\n▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬\n■ Если вам что-то не нравится в каком-либо из модов, просто используйте конфиги. У Dragon Survival конфиг доступен без перезагрузки игры. Просто зайдите в инвентарь дракона и нажмите на шестерёнку справа внизу. Многие моды в модпаке являются настраиваемыми. Для этого откройте папку с модпаком (curseforge - minecraft - Instances - Play as Dragon) и найдите там папку config. С помощью Блокнот или Notepad++ откройте и изучите файл нужного вам мода.\n\n■ Не нашли нужную вам настройку? Возможно, она находится тут: Play as Dragon - saves - World Name - serverconfig\n▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬"

If it's important, modpack: https://www.curseforge.com/minecraft/modpacks/play-as-dragon
This mod was used to simplify the creation of localization keys (but it certainly can't have anything to do with the mod): https://www.curseforge.com/minecraft/mc-mods/ftb-quests-localization-keys

**Comment by ChiefArug** [comment]
Can you please provide the debug.log file on a paste site like https://gist.github.com please?

**Comment by BlackAures1** [comment]
Are you able to repeat this bug with my text? I can send you a debug, but there will be a lot of unnecessary stuff.
[server.txt](https://github.com/KubeJS-Mods/KubeJS/files/9499923/server.txt)
[latest.log](https://github.com/KubeJS-Mods/KubeJS/files/9499929/latest.log)
[debug-1.log.gz](https://github.com/KubeJS-Mods/KubeJS/files/9499932/debug-1.log.gz)
It should have everything you need. This error appeared on any startup at any time, so I don't think it makes much difference which debug to send, but here are a few. The first one is from the kubejs folder.

**Comment by ChiefArug** [comment]
```
Error during pre-loading phase
net.minecraftforge.fml.ModLoadingException: Mod bettervillage requires libraryferret3.0.0 or above
Currently, libraryferret is 2.5.1
```
As well as this error better fps is incompatible with whatever sodium port you have.
Can you fix those issues then send a new debug.log?

**Comment by BlackAures1** [comment]
I have always had the new version of libraryferret
![image](https://user-images.githubusercontent.com/43911230/190864940-827cdcc0-d78a-42c8-bb23-d7888b4c4621.png)

I apologize for the long response. Here is the new log without better fps:
[debug.log](https://github.com/KubeJS-Mods/KubeJS/files/9592054/debug.log)

**Comment by BlackAures1** [comment]
Opening quests with Format Error also causes a huge spam in the console. Is there any way to disable it so it doesn't clog the files?
![image](https://user-images.githubusercontent.com/43911230/190914980-039614cb-e967-461d-bf68-d9cb7861cb2c.png)

**Comment by BlackAures1** [comment]
This debug spam happens when I open any quest that says "Format error". When I wrote text directly in FTBQuests without localization keys this problem didn't happen and it appeared only after adding localization. I can find you specific quests in English in the modpack that have Format error, if you will deal with this problem.

Here is the structure of the quests and the localization files themselves, if it's important.
[kubejs.zip](https://github.com/KubeJS-Mods/KubeJS/files/9608389/kubejs.zip)

**Comment by ChiefArug** [comment]
Does it still happen if you load the translation file with a resouce pack instead of KubeJS' assets folder?

**Comment by BlackAures1** [comment]
I haven't tried that. Could it work?

**Comment by xMikux** [comment]
I have this problem too, and I load with resoucepack, still will appear the Format error message.

**Comment by BlackAures1** [comment]
Is there any chance this will be fixed?
 ftb-quests-forge-1902.4.16-build.235 + kubejs-forge-1902.6.0-build.142 still bugged

**Comment by ChiefArug** [comment]
This seems to not be an issue with KubeJS, as it still happens when using a resourcepack not loaded with KubeJS.
So I suspect it is either an issue with the addon or FTBQuests.

**Comment by BlackAures1** [comment]
Wait, what resource pack are you talking about? You yourself wrote about resource packs for testing to "fix" the problem, but another user confirmed that your "fix" doesn't work. I'm using your localization system (Instances\Play as Dragon Gothic Edition\kubejs\assets\kubejs\lang). If you need to duplicate this in FTB Quest, I can write them, but something tells me they will say you have the problem, because when I write the text directly in FTB Quest I do not get this error.
![image](https://github.com/KubeJS-Mods/KubeJS/assets/43911230/221ff347-bf6c-4beb-8cd1-1b385555c3f2)
![image](https://github.com/KubeJS-Mods/KubeJS/assets/43911230/9618cd3a-4e5d-4f07-afe4-ea426afcab44)

**Comment by ChiefArug** [comment]
KubeJS' localisation system is the same system as in a resource pack, just in a different folder.
Because the issue happens in a resource pack that is **not controlled by KubeJS** this is **not KubeJS' fault**. 
If I had to guess it is probably a bug in how FTBQuests handles localisation (specifically localisation, not all text).

**Comment by BlackAures1** [comment]
I forwarded them this error, hope it helps. Thank you for your time ^^
