### ISSUE TITLE
No item builder method to set fire resistance

### ISSUE THREAD

**Issue by saltyseadoggo** [KubeJS-Mods/KubeJS#475]
### Minecraft Version

1.18.2

### KubeJS Version

1802.5.4-build.533

### Rhino Version

1802.1.14-build.209

### Architectury Version

4.8.81

### Forge/Fabric Version

Forge 40.1.73

### Describe your issue

In the `item.registry` event, there is no method to set a custom item to be fire resistant, like netherite items in vanilla. Currently, to make a custom item fire resistant, you have to use item modification.

**Comment by ChiefArug** [comment]
#479 is now merged
