### ISSUE TITLE
Errors will not log and recipes will not load

### ISSUE THREAD

**Issue by squoshi** [KubeJS-Mods/KubeJS#476]
### Minecraft Version

1.18.2

### KubeJS Version

1802.5.5-build.546

### Rhino Version

1802.2.0-build.232

### Architectury Version

4.9.83

### Forge/Fabric Version

Forge 40.1.79

### Describe your issue

https://gnomebot.dev/paste/1017973785216962650
1. Recipes will not load in-game after multiple attempts to fix
2. Errors will not log. All it says is "0 recipes loaded"

### Crash report/logs

https://gnomebot.dev/paste/1017973784621351032

**Comment by ChiefArug** [comment]
Just because you haven't gotten an answer on the discord doesn't mean you should come here instead. 

If you believe this is a bug then please provide a smaller script to reproduce this, no one is going to debug a 400+ line script for you.

**Comment by squoshi** [comment]
That is not the entire reason. The reason is due to errors not logging. Not asking for a debug.

**Comment by ChiefArug** [comment]
For someone to work out why errors are not logging they would have to work out what is causing it (I call that debugging).
That process takes a lot longer when you have a 400 script taken out of a modpack compared to a 10 line script that only has the thing that causes the issue.
