### ISSUE TITLE
KubeJS not replacing outputs in Mystical Agriculture

### ISSUE THREAD

**Issue by AlluringEmerald** [KubeJS-Mods/KubeJS#48]
I've tried to make a script that unifies all ore outputs using tags and my preferred mod, however Mystical Agriculture is not playing nice with my script, outputting to whatever the mod outputs to by default. It unifies everything else in my modpack except for Mystical Agriculture outputs. Is this just not supported or is there an extra line of code I need so that it'll replace MA's recipe outputs?

[unify.zip](https://github.com/KubeJS-Mods/KubeJS/files/5754057/unify.zip)

**Comment by LatvianModder** [comment]
The way to handle MA recipes is using its config. The values are more or less hardcoded iirc, unless you want to change all recipes manually. I think in the config you can prioritize some mods over others
