### ISSUE TITLE
Issue with `ItemStackJS.getTags()` returning empty array when game is re-launched

### ISSUE THREAD

**Issue by FIREdog5** [KubeJS-Mods/KubeJS#482]
### Minecraft Version

1.18.2

### KubeJS Version

 kubejs-forge-1802.5.5-build.546.jar

### Rhino Version

rhino-forge-1802.2.0-build.232.jar

### Architectury Version

architectury-4.9.84-forge.jar

### Forge/Fabric Version

Forge 40.1.60

### Describe your issue

After re-launching the game, when then launching a world for the first time, `ItemStackJS.getTags()` always returns an empty array (in the recipes event). Subsequent times that worlds are opened, or that `/reload` is used, `ItemStackJS.getTags()` will function correctly. It will only break again when the game is re-launched.

**Comment by MaxNeedsSnacks** [comment]
Tags aren't bound yet during the recipe event, this is vanilla behaviour that we adhere to. The only way to "fix" this would be to resolve and bind tags early, which would likely break some behaviour in vanilla or another mod (especially whenever a reload "fails")
