### ISSUE TITLE
Version-specific documentation

### ISSUE THREAD

**Issue by 74HC14** [KubeJS-Mods/KubeJS#483]
### Describe the feature

For all major versions of KubeJS, but the oldest versions are the more pressing ones. Older game versions like 1.7.10 and 1.12.2 are still used for modding, mods like GregTech are still being updated for them, and I see this mod technically has versions available for them on Curseforge. Though the 1.7.10 releases go under the name "Command Scripts". I can't find any documentation for these versions and imagine things have changed quite a lot, both in terms of syntax and capability. Curseforge won't let me filter existing modpacks by both mods included and date or version, so I can't find any existing script files to learn from. Even the wayback machine doesn't cater to the Curseforge page back in 2015, so I'm stuck.

I can't even get the 1.7.10 version to boot without crashing (only it and "FTB Library" installed), and while I can get the 1.12.2 version to boot (only it installed) there isn't any example file generated for me like what you get in a mod like CoFH World.

**Comment by ChiefArug** [comment]
The 1.7.10 and 1.12.2 versions of KubeJS do not have the majority of features people use in modern versions, like recipe management.
Regardless, they are old and unsupported and will not be gettivg docs. If you really want to use them (don't, we reccomend CraftTweaker on those versions) then the branches with their code still exist and you can probably piece together a script from that, although you are on your own for all of that.

Regarding different doc pages for different (modern) versions, I believe KubeJS 6.0 on 1.19.2 will use a different documentation site, and hopefully something will be setup there for future versions too. 1.16 through to 1.19.1 are all very similar and most major differences are noted on the respective page, so I feel like they do not need different doc pages. (the docs for them are also woefully incomplete)
