### ISSUE TITLE
Music disc item builder 1.16.5

### ISSUE THREAD

**Issue by Dragsio** [KubeJS-Mods/KubeJS#491]
### Describe the feature

Can you add music_disc feature to mc version 1.16.5 like this [9dbe4e5](https://github.com/KubeJS-Mods/KubeJS/commit/9dbe4e580cf9c14e8e6b2df294e9a4b39afbc031) ?

**Comment by ChiefArug** [comment]
No, 1.16 is End Of Life and not getting any more new features.
