### ISSUE TITLE
Cannot make custom item lose durability in a crafting recipe

### ISSUE THREAD

**Issue by Abalieno** [KubeJS-Mods/KubeJS#492]
### Minecraft Version

1.18.2

### KubeJS Version

kubejs-fabric-1802.5.5-build.546

### Rhino Version

rhino-fabric-1802.2.0-build.232

### Architectury Version

architectury-4.9.84-fabric

### Forge/Fabric Version

fabric-api-0.59.0+1.18.2

### Describe your issue

![ruyk](https://user-images.githubusercontent.com/4656436/194041237-1529b761-0a3f-46f1-8770-13edcc3e6845.jpg)

The commented out code works, but I need this to be shapeless.

I've tried various combinations of the line below, none worked. The item always gets deleted.

I've tried with or without NBT, within and without the damageIngredient part. I've tried adding keepIngredient.

Even through lots of trial and error I still couldn't make it work as it should.

Also, when I commented out the shapeless recipe and added the shaped one, and reloaded through "/kubejs reload server_scripts" + "/reload"
the shapeless recipe would stay active, and the shaped one still disabled. Until I closed everything and restarted.

The item was created with a simple:
event.create('geggy:wooden_form', 'basic').displayName('Wooden Form').maxDamage(50);

**Comment by Abalieno** [comment]
I found another bug:

the following shaped recipe works as it should (the item is returned, durability decreased by 1):

![rtyjtyuj](https://user-images.githubusercontent.com/4656436/194059874-5aafa893-43d8-4cc2-8ced-187d51cde008.jpg)

But if I do the same in the character crafting slots, the mortar is deleted.

**Comment by Abalieno** [comment]
As further, even if pointless, reporting... replaceIngredient is also broken:

![iuliol](https://user-images.githubusercontent.com/4656436/194201428-f32ac30e-571e-4eeb-81b9-b937c2024e5a.jpg)

I tried different combinations, the items always get deleted and not replaced.

I replaced the custom mortar with minecraft:sticks and the command worked. So it's support for kubejs items that's completely broken.

**Comment by Abalieno** [comment]
Closing this myself, and adding a bandaid workaround in case someone else searches for a similar issue:

![ryhjy](https://user-images.githubusercontent.com/4656436/194443862-f9b3b7fe-367c-4242-a6a6-8c8318429f3d.png)

This has been tested and it works as it should.
It's done by adding crafttweaker and using its script. Not an elegant solution, but at least it works.

**Comment by ChiefArug** [comment]
Duplicate of https://github.com/KubeJS-Mods/KubeJS/issues/239
