### ISSUE TITLE
KubeJS crash everytime I close down

### ISSUE THREAD

**Issue by Caseclosedx3** [KubeJS-Mods/KubeJS#5]
https://paste.dimdev.org/edemekiyaz.mccrash

Hi, I've never had any issues until now with the pack FTB Academy
I have installed some other mods, but none that should be conflicting.
It does crash everytime i close it but it also saves regardless.
Is there a fix for this?

**Comment by LatvianModder** [comment]
Unfortunately this crash log says nothing useful, so I can't help here. Maybe a future academy update will have this fixed when all mods are updated
