### ISSUE TITLE
Crash on startup with Colormatic and TerraBlender

### ISSUE THREAD

**Issue by SplendidAlakey** [KubeJS-Mods/KubeJS#500]
### Minecraft Version

1.19.2

### KubeJS Version

1902.6.0-build.79

### Rhino Version

1902.2.1-build.242

### Architectury Version

6.2.46

### Forge/Fabric Version

API 0.62.0; loader 0.14.9

### Describe your issue

The game crashes on startup when KubeJS is installed together with [Colormatic](https://www.curseforge.com/minecraft/mc-mods/colormatic) and [TerraBlender](https://www.curseforge.com/minecraft/mc-mods/terrablender-fabric). Removing either of the 3 mods lets the game start. The issue happens on Fabric and Quilt.

### Crash report/logs

https://gist.github.com/SplendidAlakey/d60f5fc9d9bdd1f101c0041926f0ce9d

**Comment by ChiefArug** [comment]
Based on the fact that Terrablender is the only mod mentioned in the stacktrace this is probably on them like the author of Colormatic said.
