### ISSUE TITLE
java.lang.NullPointerException: Cannot read field "logErroringRecipes" because "dev.latvian.mods.kubejs.server.ServerSettings.instance" is null

### ISSUE THREAD

**Issue by otavio-silva** [KubeJS-Mods/KubeJS#504]
### Minecraft Version

1.19.2

### KubeJS Version

1902.6.0-build.86

### Rhino Version

1902.2.1-build.242

### Architectury Version

6.2.46

### Forge/Fabric Version

Fabric 0.14.9

### Describe your issue

When I try to create a new world, the game crashes.

### Crash report/logs

https://mclo.gs/Qdg6olb

**Comment by ChiefArug** [comment]
Duplicate of #501

**Comment by TheButterbrotMan** [comment]
@ChiefArug #501 seems to stopped existing

**Comment by ChiefArug** [comment]
#507 is now the issue for tracking this
