### ISSUE TITLE
KubeJS/Rhino preventing my game from loading

### ISSUE THREAD

**Issue by Druivenpasta** [KubeJS-Mods/KubeJS#510]
### Minecraft Version

1.18.2

### KubeJS Version

Latest build (think build 330)

### Rhino Version

Latest build (also 330)

### Architectury Version

Latest!

### Forge/Fabric Version

Forge 40.1.80

### Describe your issue

I tried disabling mods for a while, and the game only boots when I have disabled kubejs, downgrading doesnt seem to help.

### Crash report/logs

Logs didnt generate due to it happening during data freeze, and it not providing crashlogs afterwards.

**Comment by Filostorm** [comment]
Do you have any code written?

**Comment by Druivenpasta** [comment]
The thing I am guessing is that that is something in server or clients scripts which must not be there, Imma check now

**Comment by Druivenpasta** [comment]
> The thing I am guessing is that that is something in server or clients scripts which must not be there, Imma check now
Turns out that didnt work out, kubejs 6 isnt on 1.18 right?

**Comment by Druivenpasta** [comment]
So far I've seen- and disabling all my code- I have no preventing code in my game.

**Comment by ChiefArug** [comment]
Can you please provide actual version numbers, latest is not helpful because what is latest changes when new versions release, and going back to find what was latest when this issue was made is not nice.

**Comment by Druivenpasta** [comment]
Found em:
-kubejs build 330
-rhino build 240
-architectury version 4.9.84

**Comment by ChiefArug** [comment]
Can you provide full versions for KubeJS and Rhino?
While its unlikely that two could have the same build number, its technically not impossible.

**Comment by Druivenpasta** [comment]
> Can you provide full versions for KubeJS and Rhino? While its unlikely that two could have the same build number, its technically not impossible.

architectury-4.10.86-forge
kubejs-forge-1802.5.5-build.550
rhino-forge-1802.2.1-build.240
forge: 40.1.80
(sorry for the late response, was on a holiday)

**Comment by Shandoo94** [comment]
I have the same problem in my fabric mod pack with 
kubejs-fabric-1802.5.5-build.552
rhino-fabric-1802.2.1-build.240
architectury-4.10.86-fabric
Fabric - 0.14.9

The game loads normally with
kubejs-fabric-1802.5.4-build.535
rhino-fabric-1802.1.14-build.225

**Comment by Druivenpasta** [comment]
Well I managed to fix the issue, turns out there was a file in my KubeJS folder starting with a non-valid character.

**Comment by ChiefArug** [comment]
What was the name that prevented it loading?

**Comment by Druivenpasta** [comment]
I did not edit the name of a screenshot I saved in the assets for ftbquests. This way it started with a number.
