### ISSUE TITLE
Server Crash

### ISSUE THREAD

**Issue by MKr4zy** [KubeJS-Mods/KubeJS#518]
### Minecraft Version

1.19

### KubeJS Version

1900.5.5-build.27

### Rhino Version

1802.1.14-build.225

### Architectury Version

5.12.44

### Forge/Fabric Version

41.1.0

### Describe your issue

Whenever a Player tries to break something on the Server, it crashes.
I added the Crashlog.
I've tried downgrading one version, but I have really no clue whats happening..

This error has happened when a player tried to open a crafting table, or break something, as of now. 
We've suspended further testing..

### Crash report/logs

https://pastebin.com/N3MYv0jV

**Comment by ChiefArug** [comment]
Try update Forge

**Comment by MKr4zy** [comment]
Since I'm on MC 1.19 and not 1.19.1 / .2 theres no newer Version for me. And I cant downgrade from Forge 41.1.0 since other mods need this version.

**Comment by ChiefArug** [comment]
Oh, I thought forge had newer versions for 1.19.. They don't.

I don't think there is a solution for this, its caused by a forge update. KubeJS wont receive any updates for 1.19 to fix it, so your best option is to update to 1.19.2, though that may not be possible depending on other mods

**Comment by MKr4zy** [comment]
I'll Look into this, thanks.
