### ISSUE TITLE
Can't join server with a vanilla client (serverOnly is true)

### ISSUE THREAD

**Issue by elhertz** [KubeJS-Mods/KubeJS#520]
### Minecraft Version

1.19.2

### KubeJS Version

kubejs-fabric-1902.6.0-build.98

### Rhino Version

rhino-fabric-1902.2.1-build.242

### Architectury Version

architectury-6.3.49-fabric

### Forge/Fabric Version

Fabric 0.14.10 Server

### Describe your issue

Server log: https://pastes.dev/W8GGcPEvdj
This option is set to true:  `serverOnly=true`

Vanilla client log: https://pastes.dev/uExmpzY4zY
Vanilla client error:
![client error screenshot](https://user-images.githubusercontent.com/13700335/197441137-e7457ed9-fa17-4831-a67f-dd3c18f9ab98.png)

Modded client log: https://pastes.dev/6RJIctS0lE
Maybe this error could be helpful?
```
[Netty Client IO #1/WARN]: Configuration conflict: there is more than one oshi.architecture.properties file on the classpath
```
Modded client error:
![24-10-2022_00h-16m-14s_screenshot](https://user-images.githubusercontent.com/13700335/197442368-ccfe6518-ffe9-4dd7-8a4b-f5404620cdd3.png)

For the record, I can join the server just fine if I install the mods on my fabric modded client. I was expecting to be able to use the mod without installing it on the client-side.

**Comment by MaxNeedsSnacks** [comment]
The logs you sent on both the server and vanilla client are... incomplete unfortunately, for example, the only visible error in the vanilla log is that the narrator library couldn't be loaded.

**Comment by elhertz** [comment]
> The logs you sent on both the server and both clients are... incomplete unfortunately, for example, the only visible error in the vanilla log is that the narrator library couldn't be loaded. Can you try posting the debug log on a "pure" fabric install?

They are not incomplete? My logs display no visible errors when I join apart from client (vanilla and modded) showing a WARN when getting kicked out.

I turned on `debugInfo` & `serverOnly` in my server (fresh install - i don't have any scripts) and this is the log: https://pastes.dev/0mVbLRqal2
This is the fabric client's log (fresh install and kubejs isn't installed) https://pastes.dev/iGZgOMcLCs
As for the narrator errors, I get them on every instance and I think it has something to do with my windows installation (i don't think they have something to do with my problem).

**Comment by ChiefArug** [comment]
I can't reproduce this with just KubeJS in dev (forge or fabric), so I'm guessing it is a two way mod conflict of some sort
