### ISSUE TITLE
KubeJS Create and Ponder JS 1.19 Version 

### ISSUE THREAD

**Issue by alxandree2401** [KubeJS-Mods/KubeJS#522]
### Describe the feature

actually self-explanatory. I'd like to use both in 1.19.2

**Comment by Thollp** [comment]
I think thery're working on it already. Please be patient

**Comment by LLytho** [comment]
ponderjs is out for 1.19 Forge.
KubeJS Create will come out as soon Create Fabric 1.19 is released too.

**Comment by Abalieno** [comment]
the irony.
