### ISSUE TITLE
Kubejs don't work

### ISSUE THREAD

**Issue by Thollp** [KubeJS-Mods/KubeJS#528]
### Minecraft Version

1.19.2

### KubeJS Version

1902.6.0-build.101

### Rhino Version

1902.2.1-build.247

### Architectury Version

6.3.49

### Forge/Fabric Version

Forge 43.1.47

### Describe your issue

For some reason. Kubejs randomly stopped working (I mean, it works but not all the time like one for older MC version) and I still don't know why

### Crash report/logs

https://pastebin.com/xPjFTN7q

**Comment by ChiefArug** [comment]
The pastebin you linked is private. Can you try again?
Alternatively make a gist: https://gist.github.com/

**Comment by Thollp** [comment]
> 

Nope. Because I know the problem and it is because syntax is invalid so I'm gonna close this issue
