### ISSUE TITLE
Good Documentation

### ISSUE THREAD

**Issue by LatvianModder** [KubeJS-Mods/KubeJS#53]
Yeah like that's happening any time soon

**Comment by Aspyro** [comment]
Hi !
I'm actually looking to KubeJS (Forge 1.16.4), and being a novice, there is a lot that I don't understand in your documentation.
I hope this is the good place for this. I'll add a new comment each time I find something improvable.

On [RecipeEventJS](https://mods.latvian.dev/books/kubejs/page/recipeeventjs) page, you first talk about settings
```JavaScript
// Enable recipe logging, off by default
settings.logAddedRecipes = true
settings.logRemovedRecipes = true
// Enable skipped recipe logging, off by default
settings.logSkippedRecipes = true
// Enable erroring recipe logging, on by default, recommended to be kept to true
settings.logErroringRecipes = false
```
but my default lines are
```JavaScript
settings.logAddedRecipes = true
settings.logRemovedRecipes = true
settings.logSkippedRecipes = false
settings.logErroringRecipes = true
```
I believe the docs lack of `true = on` & `false = off` (or the opposite) line somewhere.

**Comment by MaxNeedsSnacks** [comment]
I'd like to merge this (and other documentation-related issues) into the discussion thread for documentation in KubeJS, feel free to contribute with your opinions there, as well!

 https://github.com/KubeJS-Mods/KubeJS/discussions/113
