### ISSUE TITLE
Can't remove stages with Game Stages, and those devs said KubeJS was breaking it

### ISSUE THREAD

**Issue by vizthex123** [KubeJS-Mods/KubeJS#533]
### Minecraft Version

1.19.2

### KubeJS Version

1902.6.0-build.101

### Rhino Version

1902.2.1-build.247

### Architectury Version

6.3.49

### Forge/Fabric Version

Forge 43.1.47

### Describe your issue

I can't run `/gamestages remove`, and adding stages only works about half the time. [Reported it to the game stages devs](https://github.com/Darkhax-Minecraft/Game-Stages/issues/74), and they said KubeJS was breaking it.

All I've done with KubeJS is add some items, so I don't know how that would break Game Stages.

Pastebin won't let me upload the log since it exceeds their file limit, so here it is:
[latest.log](https://github.com/KubeJS-Mods/KubeJS/files/9945045/latest.log)

**Comment by ChiefArug** [comment]
Do you have any KubeJS scripts that use gamestages?

**Comment by vizthex123** [comment]
> Do you have any KubeJS scripts that use gamestages?

No, I use CraftTweaker. Looks like it got fixed though, noice.
