### ISSUE TITLE
KubeJS event jei.hide not working with JEI 10 versions

### ISSUE THREAD

**Issue by DelviousCrafts** [KubeJS-Mods/KubeJS#536]
### Minecraft Version

1.18.2

### KubeJS Version

1802.5.5-build.554

### Rhino Version

1802.2.1-build.255

### Architectury Version

4.10.86-forge

### Forge/Fabric Version

Forge 40.1.84

### Describe your issue

Updating JEI to version 10.anything causes jei.hide.items/fluids to stop functioning. This is not an issue on any 9.anything iterations. 

As they are still working on the 9.anything versions of JEI and keeping them up to date this is a limited issue as you can simply use the 9.anything version of the update, however, better to get a jump start on the update than being left in the dust when they stop development on the 9.anything versions of the JEI.

**Comment by Sandriell** [comment]
Does not seem to be limited to just the 10 version, at least for me.

I am running jei-1.18.2-9.7.2.281 and Forge 40.1.85 here and unable to get anything to hide.

kubejs-forge-1802.5.5-build.556
rhino-forge-1802.2.1-build.255

**Comment by DelviousCrafts** [comment]
> Does not seem to be limited to just the 10 version, at least for me.
> 
> I am running jei-1.18.2-9.7.2.281 and Forge 40.1.85 here and unable to get anything to hide.
> 
> kubejs-forge-1802.5.5-build.556 rhino-forge-1802.2.1-build.255

A few things I've noticed that could be the issue for you as I'm still not having issues with version 9 using the same JEI version and builds you are. I've found that items should be appropriately hidden in JEI when you use /reload or reload the world, however fluids you have to restart the game entirely in order for it to recognize changes. 

Also, fluids must be placed in their own hide event and cannot be part of an array. This will not cause an error or warning, it simply just won't work.

Any item that even remotely have any NBT data when displayed in JEI must have the Item.of('item in question', 'NBT') added in order for it to hide. The easiest way of getting this is with "/kubsjs hand" command (no quotes). There's actually one particular item that I also can't get to hide in any way shape or form from Cyclic that can hold NBT, but doesn't innately have it in JEI and I don't know why it won't hide.

Hope some of that helps at least a little. 

Happy scripting.

**Comment by Sandriell** [comment]
> > Does not seem to be limited to just the 10 version, at least for me.
> > I am running jei-1.18.2-9.7.2.281 and Forge 40.1.85 here and unable to get anything to hide.
> > kubejs-forge-1802.5.5-build.556 rhino-forge-1802.2.1-build.255
> 
> A few things I've noticed that could be the issue for you as I'm still not having issues with version 9 using the same JEI version and builds you are. I've found that items should be appropriately hidden in JEI when you use /reload or reload the world, however fluids you have to restart the game entirely in order for it to recognize changes.
> 
> Also, fluids must be placed in their own hide event and cannot be part of an array. This will not cause an error or warning, it simply just won't work.
> 
> Any item that even remotely has any NBT data when displayed in JEI must have the Item.of('item in question', 'NBT') added in order for it to hide. The easiest way of getting this is with "/kubsjs hand" command (no quotes). There's actually one particular item that I also can't get to hide in any way shape or form from Cyclic that can hold NBT, but doesn't innately have it in JEI and I don't know why it won't hide.
> 
> Hope some of that helps at least a little.
> 
> Happy scripting.

Thanks, was in fact a badly formed item.of... breaking the script. Didn't realize that /kubejs hand would give the item.of code written out. So is in fact working for me, ignore me!
