### ISSUE TITLE
Crash on latest version of KubeJS

### ISSUE THREAD

**Issue by Cyranos** [KubeJS-Mods/KubeJS#540]
### Minecraft Version

1.19.2

### KubeJS Version

1902.6.0-build.119

### Rhino Version

1902.2.2-build.264

### Architectury Version

6.3.49

### Forge/Fabric Version

43.1.52

### Describe your issue

Updated my mods today, and now it crashes and when viewing the crash from Not Enough Crashes all I see is this
![image](https://user-images.githubusercontent.com/16463091/201992528-942c8b8f-ee26-4cb9-8d62-aca00a43c539.png)

### Crash report/logs

Crash Log; https://mclo.gs/nfnJtGv Latest Log; https://mclo.gs/rffV9ma

**Comment by MaxNeedsSnacks** [comment]
ProbeJS is not compatible with the current version of KubeJS, it seems. I suggest you remove it temporarily until the issue is fixed
