### ISSUE TITLE
Registry Remapping Failed: Received ID map for minecraft:item contains ID unknown to the receiver! - kubejs:aof_logo

### ISSUE THREAD

**Issue by Wolcub** [KubeJS-Mods/KubeJS#543]
### Minecraft Version

1.16.5

### KubeJS Version

1.16.5

### Rhino Version

1.16.5

### Architectury Version

1.16.5

### Forge/Fabric Version

Fabric - 0.12.12

### Describe your issue

For some reason when i try to join my friends multiplayer server with this mod installed it gives me this error and despite me trying to fix it by reinstalling it it wont fix itself. any help is appreciated!

**Comment by MaxNeedsSnacks** [comment]
This is an issue with the pack you're playing, not with KubeJS
