### ISSUE TITLE
Can't upgrade enchanted item in smithing table.

### ISSUE THREAD

**Issue by 4AC11** [KubeJS-Mods/KubeJS#557]
### Minecraft Version

1.18.2

### KubeJS Version

kubejs-forge-1802.5.5-build.562.jar

### Rhino Version

 rhino-forge-1802.2.1-build.255.jar

### Architectury Version

architectury-4.10.88-forge.jar

### Forge/Fabric Version

Forge 40.1.80

### Describe your issue

Title. Upgrading the item normally works just fine, but after enchanting it the smithing recipe simply doesn't work, despite JEI showing it as being an available recipe.

Video: https://medal.tv/games/minecraft/clips/NmbRus0yIddjC/d1337vfRvdPO?invite=cr-MSw1dlQsMjQ4MzA2MDgs

Script: 
onEvent('recipes', event => {

  event.smithing('kubejs:true_excalibur', 'kubejs:excalibur', 'kubejs:eternal_crystal')

});

**Comment by 4AC11** [comment]
It seems like this issue should be a kind of an urgent one, since the entire point of the smithing table is to preserve enchantments and as its stands I can't test anything relating to smithing.

**Comment by 4AC11** [comment]
This also seems to be happening to any item that has _EVER_ been enchanted, meaning that even if you use a grindstone and try to upgrade, it simply doesn't work unless you make a brand new item. This really is a game breaking bug for modpacks like mine that rely on many kubejs smithing recipes...

**Comment by ChiefArug** [comment]
You need to ignore NBT.
```js
onEvent('recipes', event => {
	event.smithing('kubejs:true_excalibur', Item.of('kubejs:excalibur').ignoreNBT(), 'kubejs:eternal_crystal')
})
```

**Comment by 4AC11** [comment]
Considering the entire point of the smithing table is to conserve enchantments, you'd think it would do that by default..... Thanks for the response though.

**Comment by squoshi** [comment]
Depends on what kind of recipe you're making.

**Comment by ChiefArug** [comment]
It does do that by default.
In 1.19, where development is focused on.

**Comment by 4AC11** [comment]
:|
