### ISSUE TITLE
Every reload crashed the game.

### ISSUE THREAD

**Issue by Druivenpasta** [KubeJS-Mods/KubeJS#558]
### Minecraft Version

1.18.2-forge

### KubeJS Version

1902.5.5-build.562

### Rhino Version

1802.2.1-build.255

### Architectury Version

4.10.88-forge

### Forge/Fabric Version

Forge 40.1.87

### Describe your issue

Everytime I reload the scripts, my instance closes and I get an error file. 
[crash-2022-12-23_22.13.07-client.txt](https://github.com/KubeJS-Mods/KubeJS/files/10297359/crash-2022-12-23_22.13.07-client.txt)
Refer to this crash report: 
ps. I do not have indepth studied the error file.
ps. II. I do not have acces to the discord server, so please don't refer to anything that happened in there.

### Crash report/logs

The files are included in the description.

**Comment by ChiefArug** [comment]
`java.lang.NoClassDefFoundError: com/blamejared/crafttweaker/api/util/GenericUtil`
You are in the entirely wrong repo. Recipe Stages wants CraftTweaker installed.

**Comment by MaxNeedsSnacks** [comment]
***Again?!***

**Comment by MaxNeedsSnacks** [comment]
False alarm, OP is using an out of date version of Recipe Stages...
