### ISSUE TITLE
Item and block types

### ISSUE THREAD

**Issue by LatvianModder** [KubeJS-Mods/KubeJS#56]
Block types:

~~- Slab~~
~~- Stairs~~
~~- Fence~~
~~- Fence Gate~~
~~- Wall~~
~~- Pressure Plate~~
~~- Button~~
- Door (?)
- Trapdoor (?)
- Pillar (like log, rotates X Y Z only)
- Omnidirectional (need better name, basically like piston/dispenser)
- Horizontal (like carved pumpkin)

~~Item types:~~ Done now

~~- Pickaxe~~
~~- Axe~~
~~- Shovel~~
~~- Hoe~~
~~- Sword~~
~~- Helmet~~
~~- Chestplate~~
~~- Leggings~~
~~- Boots~~
~~- Bow~~

**Comment by Royal-Jelly** [comment]
Not to push this or anything but I for one would gladly use block types in my modpack
