### ISSUE TITLE
Blocks don't register when I boot up my game

### ISSUE THREAD

**Issue by PuddingStone** [KubeJS-Mods/KubeJS#560]
### Minecraft Version

1.18.2

### KubeJS Version

1802.5.5-build.562

### Rhino Version

1802.2.1-build.255

### Architectury Version

4.10.88

### Forge/Fabric Version

Forge 40.1.85

### Describe your issue

I was trying to register some new blocks using 'block.registry'. I tried it with a single block and it worked perfectly fine, but after I made 3 more blocks and restarted my game it failed to register the new blocks and didn't update the original block which I had slightly changed. I've restarted my game lots of times but nothing changed.

This is my code:

![image](https://user-images.githubusercontent.com/54445142/209582657-988349da-ddc2-493b-87a2-7bfc402fb3ab.png)

Script Name is: "add_blocks.js"
Path is: `kubejs/startup_scripts/add_blocks.js`
Textures path is: `kubejs/assets/kubejs/textures/block/*.png`
Models path is: `kubejs/assets/kubejs/models/block/*.json`

If you want me to give any more information and/or screenshots I'm happy to provide them. Thank you a lot in advance!

**Comment by ChiefArug** [comment]
Please provide logs, both latest.log and startup.txt from logs/kubejs

**Comment by PuddingStone** [comment]
@ChiefArug Oh it completely slipped my mind checking the logs. I read the comment and found the issue instantly. Thanks for reminding me and sorry for this stupid waste of your time
Regardless here it is for anyone possibly having the same problem
I accidentally used "toolRequired()" which doesn't exist instead of "requiresTool()"
[startup.txt](https://github.com/KubeJS-Mods/KubeJS/files/10304844/startup.txt)

Again I am really sorry for wasting your time on this
Check your logs everyone, don't be like me
