### ISSUE TITLE
Kubejs has failed to launch correctly: java.lang.reflect.InvocationTargetException: null

### ISSUE THREAD

**Issue by HamishWHC** [KubeJS-Mods/KubeJS#564]
### Minecraft Version

1.18.2 (FTB Stoneblock 3)

### KubeJS Version

1802.5.5-build.562

### Rhino Version

1802.2.1-build.255

### Architectury Version

4.10.88

### Forge/Fabric Version

Forge 40.1.92

### Describe your issue

I'm using Prism Launcher on an M1 Macbook and am getting this error before I reach the main menu (but the Minecraft window does load). Not 100% that this is a kubejs issue, but the only other case I can find of this (#521) is due to a version mismatch, which is unlikely given this is in a widely played FTB pack.

I know this that there's a 99% chance this is because I'm playing on an M1 Mac, but I'm hoping this is a simple issue for you guys to solve, since I don't really have another option right now.

Thanks for your help.

Some extra info:
FTB Stoneblock 3 version 1.5.0, but I've also tried on 1.4.3 (thought it might be a latest version issue). Have also tried getting Prism Launcher to update what mods it could, but hasn't seemed to change anything.

### Crash report/logs

[crash-2023-01-07_17.14.46-fml.txt](https://github.com/KubeJS-Mods/KubeJS/files/10365622/crash-2023-01-07_17.14.46-fml.txt)

**Comment by ChiefArug** [comment]
`java.lang.RuntimeException: There were startup script syntax errors! See logs/kubejs/startup.txt for more info`

**Comment by HamishWHC** [comment]
Here's the content of that file: [startup.txt](https://github.com/KubeJS-Mods/KubeJS/files/10365634/startup.txt)
These are the default Stoneblock 3 scripts, some of which I think is here (I'm not familiar with kubejs so not certain of this): https://github.com/FTBTeam/FTB-StoneBlock-Companion/tree/main/src/main/resources

**Comment by HamishWHC** [comment]
And here are the scripts failing according to startup.txt (renamed to txt):
[forgevent.txt](https://github.com/KubeJS-Mods/KubeJS/files/10365644/forgevent.txt)
[sbd.txt](https://github.com/KubeJS-Mods/KubeJS/files/10365645/sbd.txt)

**Comment by HamishWHC** [comment]
Found https://github.com/FTBTeam/FTB-Modpack-Issues which seems like a better spot for this, since it seems to be issues with their scripts. If you have an idea for a quick fix lmk, but I'll close this. Thanks again for taking a look.
