### ISSUE TITLE
Crafting with Unbreakable Tinkers' Construct tools.

### ISSUE THREAD

**Issue by KodYazanDruid** [KubeJS-Mods/KubeJS#566]
### Minecraft Version

1.18.2

### KubeJS Version

kubejs-forge-1802.5.5-build.562

### Rhino Version

rhino-forge-1802.2.1-build.255

### Architectury Version

architectury-4.10.88-forge

### Forge/Fabric Version

Forge - 40.2.0

### Describe your issue

.damageIngredient() function can damage Tinkers' Construct Unbreakable tools.

This is the recipe script.
![image](https://user-images.githubusercontent.com/45048634/211620572-bed14c13-4650-4098-a290-35f130140817.png)

And this is after crafting.
![image](https://user-images.githubusercontent.com/45048634/211620951-990f1717-56f2-465c-8d2e-9b7a812a3e47.png)

**Comment by ChiefArug** [comment]
I believe this on how Tinkers implements their unbreaking.
They still allow some things to damage it, like pig irons tasty trait, so they don't just block all damage.

Best solution would probably to make a customIngredientAction and check the tool for unbreaking before damaging.

**Comment by ChiefArug** [comment]
Having a look at the code, it doesn't look like it is possible to not damage tinkers tools without explicit tinkers support, which would belong in an addon.
