### ISSUE TITLE
All the Mods 8 1.0.9 - startup script syntax error

### ISSUE THREAD

**Issue by caelansimms** [KubeJS-Mods/KubeJS#574]
### Minecraft Version

1.19.2

### KubeJS Version

kubejs-forge-1902.6.0-build.140.jar

### Rhino Version

rhino-forge-1902.2.2-build.264.jar

### Architectury Version

architectury-6.4.62-forge.jar

### Forge/Fabric Version

Forge 43.2.3

### Describe your issue

> KubeJS encountered an error during the complete event phase
java.lang.RuntimeException: There were KubeJS startup script syntax errors! 

This happened with the previous version of the modpack, 1.0.8, and have been uninstalling/reinstalling it to see if that would hel but alas it does not. Placing both the crash report and latest log inside here.

[crash-2023-01-28_14.58.58-fml.txt](https://github.com/KubeJS-Mods/KubeJS/files/10528489/crash-2023-01-28_14.58.58-fml.txt)

[latest.log](https://github.com/KubeJS-Mods/KubeJS/files/10528491/latest.log)

### Crash report/logs

https://github.com/KubeJS-Mods/KubeJS/files/10528491/latest.log

**Comment by ChiefArug** [comment]
This is an issue with the modpacks scripts. It looks like some of their event handlers are duplicated.
