### ISSUE TITLE
Modify existing blocks and items

### ISSUE THREAD

**Issue by LatvianModder** [KubeJS-Mods/KubeJS#58]
Block properties:

- material
- materialColor
- hasCollision
- lightEmission
- explosionResistance
- destroyTime
- requiresCorrectToolForDrops
- isRandomlyTicking (?)
- friction
- speedFactor
- jumpFactor
- canOcclude (?)
- isAir (?)
- isValidSpawn (?)
- isRedstoneConductor (?)
- isSuffocating (?)
- isViewBlocking (?)
- hasPostProcess (?)
- emissiveRendering (?)

Item properties:

- category
- rarity
- craftingRemainingItem
- maxDamage
- maxStackSize
- food (?)
- isFireResistant

**Comment by Nick-McKay** [comment]
What about attack_damage, attack_speed, armor, and armor_toughness from https://minecraft.gamepedia.com/Attribute ?

**Comment by Nick-McKay** [comment]
Is this still on the backburner?

**Comment by MaxNeedsSnacks** [comment]
This is done, actually, see

https://github.com/KubeJS-Mods/KubeJS/blob/master/common/src/main/java/dev/latvian/kubejs/item/ItemModificationEventJS.java

and

https://github.com/KubeJS-Mods/KubeJS/blob/master/common/src/main/java/dev/latvian/kubejs/block/BlockModificationEventJS.java

Event IDs are `item.modification` and `block.modification` ^^

**Comment by MaxNeedsSnacks** [comment]
> What about attack_damage, attack_speed, armor, and armor_toughness from https://minecraft.gamepedia.com/Attribute ?

I'd recommend opening another issue for this, as these attributes are separate from these other properties, and in some cases dictated by the Item's `Tier` (which KubeJS *does* have a wrapper for)
