### ISSUE TITLE
Block Loot Tables Aren't Working?

### ISSUE THREAD

**Issue by AnAwesomGuy** [KubeJS-Mods/KubeJS#586]
### Minecraft Version

1.18.2

### KubeJS Version

1802.5.5-build.569

### Rhino Version

1802.2.1-build.255

### Architectury Version

4.11.89

### Forge/Fabric Version

Fabric 0.14.14

### Describe your issue

// priority: 0

settings.logAddedRecipes = true
settings.logRemovedRecipes = true
settings.logSkippedRecipes = false
settings.logErroringRecipes = true

onEvent('block.loot_tables', event => {
	event.addSimpleBlock('minecraft:dirt', 'minecraft:red_sand')
  })

This is script.js in kubejs\server_scripts.

video in discord: https://discord.com/channels/166630061217153024/166630061217153024/1076789590926557204

**Comment by SuperStormer** [comment]
Fixed video link: 

https://user-images.githubusercontent.com/41648788/219939309-6723c1f2-1d67-4271-9ada-7615645c26f6.mp4

**Comment by AnAwesomGuy** [comment]
ok thx i couldnt upload it for some reason
modlist in case it helps,
[modlist.txt](https://github.com/KubeJS-Mods/KubeJS/files/10776534/n.txt)

**Comment by AnAwesomGuy** [comment]
nvm it works now wtf
