### ISSUE TITLE
JS files in datapacks don't load

### ISSUE THREAD

**Issue by tizu69** [KubeJS-Mods/KubeJS#589]
### Minecraft Version

1.19.2

### KubeJS Version

1902.6.0-build.142

### Rhino Version

1902.2.2-build.264

### Architectury Version

6.5.69

### Forge/Fabric Version

Forge 43.2.4

### Describe your issue

[I was told](https://discord.com/channels/303440391124942858/1070460284994584717) that JS files placed in datapacks act like server scripts. However, I can't seem to get this working. The datpack is loaded (`/datapack list`) and datapack functions work fine too. I tried placing my scripts in `[pack]/data/kubejs/server_scripts`, `[pack]/data/minecraft/tags`, `[pack]/data/minecraft/functions`.

**Comment by tizu69** [comment]
as I just sent in the discord thread:
>nevermind
I figured it out by accident lol
The files have to be placed in [pack_root]/data/server_scripts/[...].js
I am so happy rn

**Comment by tizu69** [comment]
nevermind

**Comment by Linguardium** [comment]
looks like, from the code, it is looking for files of resource type "kubejs" ending with ".js"
`/data/<namespace>/<type>/` 
`/data/minecraft/tags/` contains tags type resources
`/data/kubejs/server_scripts/` would be showing `server_scripts` type resources, which still dont match the `kubejs` type search

so it _should_ load something from `data/minecraft/kubejs/server_script.js` for instance, but normally the namespace used would be unique to the pack.

I cant test at the moment but this may have been your issue
