### ISSUE TITLE
All The Mods 8 - KubeJS encountered an error during the complete event Phase

### ISSUE THREAD

**Issue by RLChristof** [KubeJS-Mods/KubeJS#593]
### Minecraft Version

1.19.2

### KubeJS Version

KubeJS Forge 1902.6.0-build.142

### Rhino Version

rhino-forge-1902.2.2-build.264.jar

### Architectury Version

architectury-6.5.69-forge.jar

### Forge/Fabric Version

Forge 43.2.6

### Describe your issue

Receiving an "Error loading mods" error in Minecraft 1.19.2 ATM8

Latest.log: https://pastebin.com/Wy7trpCq
Crash log: https://pastebin.com/NZeebQVv
KubeJS startup.txt: https://pastebin.com/tdwEayHr

![image](https://user-images.githubusercontent.com/45082454/224082461-f8391aa9-2b18-4be1-8077-a49f1353d131.png)

Picture of the error.
Already installed fresh JARs of the mods above, reinstalled Forge 1.19.2, only thing I haven't done is a fresh Minecraft install.

**Comment by squoshi** [comment]
That's probably an issue on ATM8's side, unless you edited their scripts. I'd report to them if you didn't mess with any scripts, and if you did, please ask for support in the Discord server instead.

**Comment by ChiefArug** [comment]
According to the error its trying to load 1.18 or 1.16 scripts.
What have you done to ATM8???

**Comment by RLChristof** [comment]
@ChiefArug To be honest, unsure. I'll go ahead and wipe the folder and see if that fixes it

**Comment by squoshi** [comment]
> @ChiefArug To be honest, unsure. I'll go ahead and wipe the folder and see if that fixes it

That's not a good idea unless you know what you are doing. ATM8 is almost entirely based off of these scripts.

**Comment by ChiefArug** [comment]
@RLChristof where did you get with this?

**Comment by RLChristof** [comment]
@ChiefArug Sorry for the super delay. I ended up deleting the root folder of minecraft, let it rebuild, and then pushed over a fresh install of ATM8. I'm not sure what happened or for what reason but that fixed the issues
