### ISSUE TITLE
Crash Can't access other Client players

### ISSUE THREAD

**Issue by Darkere** [KubeJS-Mods/KubeJS#6]
https://hatebin.com/lniezejcqm

Was moving around another player. I don't remember interacting with anything either.

Pack: Enigmatica 4 0.3.2 Dev said he has yet to add any KubeJS code. 

Forge 28.1.103
KubeJS: kubejs-forge-1.14.4-2.1.0.18

**Comment by NillerMedDild** [comment]
Here are all the KubeJS files for Enigmatica 4 0.3.2, just in case. I just doubled checked to make sure I hadn't added anything - I pretty much just outcommented the deafult console.logs, and changed a few filenames.
[kubejs.zip](https://github.com/KubeJS-Mods/KubeJS/files/3951901/kubejs.zip)

**Comment by LatvianModder** [comment]
Fixed again
