### ISSUE TITLE
[1.16.4] FML crash on every version after .144

### ISSUE THREAD

**Issue by bessiq** [KubeJS-Mods/KubeJS#60]
kubejs-1604.3.4.145+
Forge: 35.1.7
Crash report: https://hatebin.com/laiklngjqb
latest.log: https://hatebin.com/gaqskpbffe

It's probably a conflict with some other dumb mod I am using, but I can't figure it out. Reverting KubeJS to .144 resolves the issue. Thanks for any help you can provide.

**Comment by shedaniel** [comment]
Outdated rhino

**Comment by bessiq** [comment]
Thanks. Any chance of getting Rhino tagged for Forge in Curseforge so launchers pick up updates?

**Comment by shedaniel** [comment]
The rhino file also works for fabric, blame your launcher instead.

**Comment by bessiq** [comment]
Ok, sorry.
