### ISSUE TITLE
KubeJs has failed to load correctly  java.lang.reflect.InvocationTargetExpection: null

### ISSUE THREAD

**Issue by hapsurantospa** [KubeJS-Mods/KubeJS#605]
### Minecraft Version

1.18.2

### KubeJS Version

kubejs-forge-1802.5.5-build.569

### Rhino Version

rhino-forge-1802.2.1-build.255

### Architectury Version

architectury-4.11.91-forge

### Forge/Fabric Version

1.18.2-forge-40.2.1

### Describe your issue

![Screenshot_3255](https://user-images.githubusercontent.com/73561441/230714269-fe0d23e3-54a5-4cb4-bfd9-df784fdbe7e8.png)
![Screenshot_3256](https://user-images.githubusercontent.com/73561441/230714272-0c5ed0d8-273c-4479-b1ef-3fe07e3c8ae5.png)

**Comment by ChiefArug** [comment]
Can't do anything with logs.
But chances are, its a problem with your scripts. Check logs/kubejs/startup.txt

**Comment by hapsurantospa** [comment]
> Can't do anything with logs.
> But chances are, its a problem with your scripts. Check logs/kubejs/startup.txt

**Comment by hapsurantospa** [comment]
> Can't do anything with logs. But chances are, its a problem with your scripts. Check logs/kubejs/startup.txt

[12:26:45] [INFO ] Hello, World! (You will only see this line once in console, during startup)
[12:26:45] [ERR  ] Error loading KubeJS script: ReferenceError: "StartupEvents" is not defined. (startup_scripts:script.js#5)
[12:26:45] [INFO ] Loaded 0/1 KubeJS startup scripts in 2.414 s

**Comment by MichaelHillcox** [comment]
Attach your script

**Comment by hapsurantospa** [comment]
[12:26:45] [INFO ] Hello, World! (You will only see this line once in console, during startup)
[12:26:45] [ERR  ] Error loading KubeJS script: ReferenceError: "StartupEvents" is not defined. (startup_scripts:script.js#5)
[12:26:45] [INFO ] Loaded 0/1 KubeJS startup scripts in 2.414 s

**Comment by ChiefArug** [comment]
You are trying to use 1.19 syntax on 1.18, which doesn't work. Make sure you are using the legacy wiki for 1.18, not the normal wiki, which is 1.19+ only

**Comment by hapsurantospa** [comment]
Mod List: 
		client-1.18.2-20220404.173914-srg.jar             |Minecraft                     |minecraft                     |1.18.2              |COMMON_SET|Manifest: a1:d4:5e:04:4f:d3:d6:e0:7b:37:97:cf:77:b0:de:ad:4a:47:ce:8c:96:49:5f:0a:cf:8c:ae:b2:6d:4b:8a:3f
		rhino-forge-1802.2.1-build.255.jar                |Rhino                         |rhino                         |1802.2.1-build.255  |COMMON_SET|Manifest: NOSIGNATURE
		createbigcannons-1.18.2-beta-0.5.b.jar            |Create Big Cannons            |createbigcannons              |1.18.2-beta-0.5.b   |COMMON_SET|Manifest: NOSIGNATURE
		create_misc_and_things_1.18.2_2.0.jar             |create: things and misc       |create_things_and_misc        |1.0.0               |COMMON_SET|Manifest: NOSIGNATURE
		create_brass_coated-0.2.2.1-1.18.2.jar            |Create: Brass Coated          |create_brass_coated           |0.2.2.1-1.18.2      |COMMON_SET|Manifest: NOSIGNATURE
		open-parties-and-claims-forge-1.18.2-0.17.2.jar   |Open Parties and Claims       |openpartiesandclaims          |0.17.2              |COMMON_SET|Manifest: NOSIGNATURE
		Create+Deco+Casing+2.0.0+1.18.jar                 |Create Deco Casing            |create_deco_casing            |2.0.0               |COMMON_SET|Manifest: NOSIGNATURE
		kffmod-3.11.0.jar                                 |Kotlin For Forge              |kotlinforforge                |3.11.0              |COMMON_SET|Manifest: NOSIGNATURE
		flywheel-forge-1.18.2-0.6.8.a.jar                 |Flywheel                      |flywheel                      |0.6.8.a             |COMMON_SET|Manifest: NOSIGNATURE
		create-stuff-additions1.18.2_v2.0.2b.jar          |Create Stuff & Additions      |create_sa                     |2.0.2               |COMMON_SET|Manifest: NOSIGNATURE
		architectury-4.11.90-forge.jar                    |Architectury                  |architectury                  |4.11.90             |COMMON_SET|Manifest: NOSIGNATURE
		kubejs-forge-1802.5.5-build.569.jar               |KubeJS                        |kubejs                        |1802.5.5-build.569  |ERROR     |Manifest: NOSIGNATURE
		Steam_Rails-1.2.0+forge-mc1.18.2-build.7.jar      |Create: Steam 'n Rails        |railways                      |1.2.0+forge-mc1.18.2|COMMON_SET|Manifest: NOSIGNATURE
		extendedflywheels-1.2.5-1.18.2-0.5.e.jar          |Extended Flywheels            |extendedflywheels             |1.2.5-1.18.2-0.5.e  |COMMON_SET|Manifest: NOSIGNATURE
		create-1.18.2-0.5.0.i.jar                         |Create                        |create                        |0.5.0.i             |COMMON_SET|Manifest: NOSIGNATURE
		createdeco-1.3.0-1.18.2.jar                       |Create Deco                   |createdeco                    |1.3.0-1.18.2        |COMMON_SET|Manifest: NOSIGNATURE
		CreateCasing-1.18.2-1.1.1-hotfix-1.jar            |Create : Encased              |createcasing                  |1.18.2-1.1.1-hotfix-|COMMON_SET|Manifest: NOSIGNATURE
		kubejs-create-forge-1802.2.2-build.28.jar         |KubeJS Create                 |kubejs_create                 |1802.2.2-build.28   |COMMON_SET|Manifest: NOSIGNATURE
		valkyrienskies-118-2.1.0-beta.10.jar              |Valkyrien Skies 2             |valkyrienskies                |2.1.0-beta.10       |COMMON_SET|Manifest: NOSIGNATURE
		cloth-config-forge-6.3.81.jar                     |Cloth Config v4 API           |cloth_config                  |6.3.81              |COMMON_SET|Manifest: NOSIGNATURE
		forge-1.18.2-40.2.1-universal.jar                 |Forge                         |forge                         |40.2.1              |COMMON_SET|Manifest: 84:ce:76:e8:45:35:e4:0e:63:86:df:47:59:80:0f:67:6c:c1:5f:6e:5f:4d:b3:54:47:1a:9f:7f:ed:5e:f2:90
		creategearaddon-1.18.2+v2.0.jar                   |Create gear addon             |creategearaddon               |1.18.2 v2.0         |COMMON_SET|Manifest: NOSIGNATURE
		createaddition-1.18.2-20230404a.jar               |Create Crafts & Additions     |createaddition                |1.18.2-20230404a    |COMMON_SET|Manifest: NOSIGNATURE

**Comment by hapsurantospa** [comment]
> Attach your script

How can I do it?

**Comment by ChiefArug** [comment]
Have a look at the legacy wiki, available here: https://wiki.latvian.dev/books/kubejs-legacy
If you have further questions please use a discussion (not an issue), or ask in the Discord server: https://discord.gg/latviandev
