### ISSUE TITLE
Any clue on this crash?

### ISSUE THREAD

**Issue by TheWitherlord** [KubeJS-Mods/KubeJS#61]
Using a version of my custom pack that hasn't been released yet and I am just wondering after updating kubejs from
144 to 148 I am getting this loading error/crash.
https://gist.github.com/TheWitherlord/29fcf05377b80712c8308c701c0953d9

![we](https://user-images.githubusercontent.com/15508917/104981485-53438100-59ce-11eb-8e52-c9ac79a4bf1d.PNG)

**Comment by TheWitherlord** [comment]
DEBUG and LOG should be in that Gist too.

**Comment by ClaudiusMinimus** [comment]
Same with my pack using 1605.3.4.151
[crash-2021-01-20_09.33.47-fml.txt](https://github.com/KubeJS-Mods/KubeJS/files/5843871/crash-2021-01-20_09.33.47-fml.txt)

**Comment by LatvianModder** [comment]
You need to update Rhino. I will change required version in mod file
