### ISSUE TITLE
KubeJS does not read the singularity NBTtag from Avaritia

### ISSUE THREAD

**Issue by CalibryTeam** [KubeJS-Mods/KubeJS#611]
### Minecraft Version

1.19.2

### KubeJS Version

1902.6.0-build.142

### Rhino Version

1902.2.2-build.268

### Architectury Version

6.5.77

### Forge/Fabric Version

Forge 43.2.8

### Describe your issue

KubeJS does not read the singularity tag from Avaritia.
We have tried many solutions to this problem, nothing helps, there is an option to do it through data, but this complicates the development of doing everything through data
![image](https://user-images.githubusercontent.com/99535321/235313381-d9e5de12-6d31-42ef-99a8-390739ad0361.png)
![image](https://user-images.githubusercontent.com/99535321/235313402-99794704-a50e-4ebf-b8cf-bbc1f15926ba.png)
[shaped_extreme_craft.txt](https://github.com/KubeJS-Mods/KubeJS/files/11359639/shaped_extreme_craft.txt)

**Comment by ChiefArug** [comment]
You need to tell KubeJS to keep the NBT.
`Item.of('mod:item', '{ID: "avartia:iron"}').weakNBT()`
