### ISSUE TITLE
Changing mod display name not working

### ISSUE THREAD

**Issue by TheStaticVoid** [KubeJS-Mods/KubeJS#619]
### Minecraft Version

1.19.2

### KubeJS Version

1902.6.0-build.142

### Rhino Version

1902.2.2-build.268

### Architectury Version

6.5.77

### Forge/Fabric Version

Fabric 0.14.19

### Describe your issue

The mod display renaming in the documentation [here](https://wiki.latvian.dev/books/kubejs/page/changing-mod-display-names) does not appear to be working for me. Here's my startup script:
```js
Platform.mods.kubejs.name = 'My Modpack Name';

StartupEvents.registry('item', e => {
    e.create('example_item').displayName('Example');
});
```

Modlist:
- Architectury v6.5.77
- Cloth Config v8.2.88
- Fabric API 0.76.0+1.19.2
- KubeJS 1902.6.0-build.142
- Rhino 1902.2.2-build.268
- Roughly Enough Items 9.1.595

What I see in REI:
![image](https://cdn.discordapp.com/attachments/1102720910357704796/1102720910571622470/image.png)

### Crash report/logs

[latest.log](https://pastebin.com/Gz5sXnGq)

**Comment by Abalieno** [comment]
It seems to be working fine with other mods, and kubejs standard, but cannot be used to redefine custom names for kubejs-created custom items.

```
TypeError: Cannot set property "name" of undefined to "Geghilarity"
```

Of course you can set the name to what you want, already, but I wanted to use this so that I could do proper capitalization on the first letter, or deal with spaces as well.

**Comment by ChiefArug** [comment]
That is because to change the name associated with a modid, a mod needs to exist for that modid.
Just specifying a custom namespace when adding something doesnt create a mod.

**Comment by Abalieno** [comment]
I moved it down the file, but it didn't change much.

I guess it depends when these things are set up.

**Comment by ChiefArug** [comment]
Where it is in the file doesn't matter. At no point (currently) will KubeJS just create a virtual mod, which would be what is required to change the name of a custom namespace that doesnt belong to an existing mod.

If you look at what the code is doing, it is getting a list of mods, then changing properties for that mod. The error you got is saying that the mod you specified doesn't exist.
