### ISSUE TITLE
Kubejs will prioritize native custom textures over resource pack textures

### ISSUE THREAD

**Issue by Huetete** [KubeJS-Mods/KubeJS#623]
### Minecraft Version

1.19.2

### KubeJS Version

1902.6.0-build.142

### Rhino Version

1902.2.2-build.268

### Architectury Version

6.3.49

### Forge/Fabric Version

Fabric 0.14.17

### Describe your issue

You can create a custom item with Kubejs. You can create its texture as well, which will be stored in the assets folder and so on that is inside the KubeJS folder in .minecraft.

If you try to replace that custom texture through a resource pack, it won't make the swap. It seems that KubeJS is prioritizing the native folder over the resource packs one. If you remove the native custom texture, but you keep its resource pack version in the minecraft's resource pack folder, then that texture will be assumed.

**Comment by crispytwig** [comment]
Can confirm - tested it myself when they had the thread going. It doesn't matter if you have a file path or not, and removing the texture from your KubeJS folder will allow the resource pack to use its texture which verifies that KubeJS is overriding resource packs.

**Comment by ChiefArug** [comment]
This was fixed a while ago in https://github.com/KubeJS-Mods/KubeJS/commit/29728c38b602cda3e361cd1a27041a0cf28bcd78
