### ISSUE TITLE
Update to 1.19.4

### ISSUE THREAD

**Issue by Merith-TK** [KubeJS-Mods/KubeJS#624]
### Describe the feature

I run a few servers with mods that only exist on 1.19.4, or are only maintained on 1.19.4, 

I would love to be able to use kubejs on this version due to its flexibility

**Comment by MaxNeedsSnacks** [comment]
Not happening with 1.20.1 being out already, sorry (to be honest, 1.19.4 was kind of dead from the start)

**Comment by Merith-TK** [comment]
Even with it being dead, there were still alot of mods that updated from 1.18.x to 1.19.3/4, and never went to 1.19.2, leading to several modded servers being 1.19.4 out of nessecity in order to maintain an modlist such as ComputerCraft with its security updates

but yeah I feel that with 1.20.1
