### ISSUE TITLE
Kube JS will not load

### ISSUE THREAD

**Issue by Wizard-pope** [KubeJS-Mods/KubeJS#634]
### Minecraft Version

1.18.2

### KubeJS Version

1802.5.5-build.569

### Rhino Version

1802.2.1-build.255

### Architectury Version

4.11.93

### Forge/Fabric Version

forge 40.2.4

### Describe your issue

Kube JS does not want to load and spits out an error. I have no idea what causes this
[crash-2023-06-11_17.49.25-fml.txt](https://github.com/KubeJS-Mods/KubeJS/files/11715069/crash-2023-06-11_17.49.25-fml.txt)
[latest.log](https://github.com/KubeJS-Mods/KubeJS/files/11715070/latest.log)

**Comment by ChiefArug** [comment]
KubeJS Create does not support the latest version of Create.
Remove KJS Create or downgrade Create to 0.5.0

**Comment by Wizard-pope** [comment]
Thank you very much

**Comment by Padra50** [comment]
when will it be updated?

**Comment by CelestialAbyss** [comment]
KubeJS Create **_for Forge_** already has support for Create 0.5.1 as of June 13, 2023 for both 1.19.2 and 1.18.2.
