### ISSUE TITLE
Click machine

### ISSUE THREAD

**Issue by SkyderWasTaken** [KubeJS-Mods/KubeJS#635]
### Minecraft Version

1.18.2

### KubeJS Version

1802.5.5-build.569

### Rhino Version

1802.2.1-build.255

### Architectury Version

4.11.93

### Forge/Fabric Version

Forge 40.2.9

### Describe your issue

I am unable to change the recipe for the click machine mod, I am trying to make a modpack but I would like to do this do balance progression, please help

**Comment by ChiefArug** [comment]
Closing this due to lack of response and information.
