### ISSUE TITLE
BootstrapMethodError: call site initialization exception [1.16.5]

### ISSUE THREAD

**Issue by lays24mc** [KubeJS-Mods/KubeJS#64]
Hi,

the client crashed with this message (see more details in the crash log). Installed is:

Architectury 1.4.96
KubeJS 1605.3.4.151
Rhino 1.7.13.10
Forge 36.0.1

However, when I switch to Architectury 1.4.94, there is no problem.

Crashlog: https://pastebin.com/Ffg46jms

**Comment by shedaniel** [comment]
Update to Architectury 1.4.97

**Comment by lays24mc** [comment]
Works fine for me. Thank you :)
