### ISSUE TITLE
input filter causing error on first world load

### ISSUE THREAD

**Issue by Shipmans-AGLA** [KubeJS-Mods/KubeJS#641]
### Minecraft Version

1.19.2

### KubeJS Version

1902.6.0-build.142

### Rhino Version

1902.2.2-build.268

### Architectury Version

6.5.85

### Forge/Fabric Version

Fabric 0.14.21

### Describe your issue

When loading a world for the first time on a session, an error appears and some recipe edits i have do not apply. using /reload or reloading the world without changing the script does not cause the error. commenting out lines with an input filter and restarting minecraft causes the error not to happen. I have been told in the kubejs discord this is related to create in some way.

### Crash report/logs

https://pastebin.com/KCsbj1BL

**Comment by ChiefArug** [comment]
Does this still happen with 6.1?
If not, please provide the script that causes it.

**Comment by ChiefArug** [comment]
Closing this due to lack of response. The cause is likely a broken recipe from Create/one of its addons, or something that was fixed in 6.1.
