### ISSUE TITLE
The game crashed whilst initializing game Error: java.lang. IncompatibleClassChangeError: class net.coderbot.iris.gui.option

### ISSUE THREAD

**Issue by 91leMAC** [KubeJS-Mods/KubeJS#643]
### Minecraft Version

1.19.2

### KubeJS Version

1902.6.0-build.142

### Rhino Version

1902.2.2-build.268

### Architectury Version

6.5.85-forge

### Forge/Fabric Version

Forge-43.2.6

### Describe your issue

I was unifying my ores and I have trouble with hiding items with jei and KubeJS so I install the Almost Unified mod. And then my game crash. I disactivate them and the game keep crashing.

### Crash report/logs

https://mclo.gs/DzkL3VE

**Comment by ChiefArug** [comment]
This looks to be an issue with Oculus, not KubeJS. Go report the issue to them.

**Comment by 91leMAC** [comment]
Okay
