### ISSUE TITLE
ArmorFeatureRenderer mixin duplicated in Fabric API

### ISSUE THREAD

**Issue by Linguardium** [KubeJS-Mods/KubeJS#655]
### Describe the feature

https://github.com/KubeJS-Mods/KubeJS/blob/e6d386751d247b4631969424afb8c718270422aa/fabric/src/main/java/dev/latvian/mods/kubejs/core/mixin/fabric/HumanoidArmorLayerMixin.java#L22C1-L36

this mixin is logically identical to the one in Fabric API (added 4 months after yours). Since (at least 1902) requires fabric api already, the mixin can now be removed.

Fabric API mixin below:

https://github.com/FabricMC/fabric/blob/982df14ab93552feac25b597792ae73f4f670555/fabric-rendering-v1/src/client/java/net/fabricmc/fabric/mixin/client/rendering/ArmorFeatureRendererMixin.java#L66-L78

### Additional info

While this mixin shouldn't cause any harm, it also is now just bloat to the class it modifies. As it is a modification to vanilla code, It would also require re-evaluation by development at each Minecraft update.

**Comment by MaxNeedsSnacks** [comment]
Thanks for informing us about this, I've removed the mixin in the latest commit ^^
