### ISSUE TITLE
Staged Recipe does not work

### ISSUE THREAD

**Issue by Prunoideae** [KubeJS-Mods/KubeJS#667]
### Minecraft Version

1.19.2

### KubeJS Version

1902.6.1-build.327

### Rhino Version

1902.2.2-build.268

### Architectury Version

6.5.82

### Forge/Fabric Version

Forge 43.2.11

### Describe your issue

Current staged recipe depends on this to detect player crafting:
```java
var player = RecipePlatformHelper.get().getCraftingPlayer();
```
Which is implemented as this in Forge:
```java
@Override
@Nullable
public Player getCraftingPlayer() {
	return ForgeHooks.getCraftingPlayer();
}
```

However, for unknown reasons, `ForgeHooks.getCraftingPlayer()` always return `null` when called on the server side, and unfortunately, `assemble` is called only on the server side too.

This makes recipes always return `ItemStack.EMPTY` when a player tries to craft a staged recipe. Making the staged recipe completely not usable.

**Comment by LatvianModder** [comment]
That sounds like a Forge bug but I guess we cab patch that outselves

**Comment by MaxNeedsSnacks** [comment]
Already done indev, will be released with the next public build
