### ISSUE TITLE
Enhancement: custom brewing stand recipes

### ISSUE THREAD

**Issue by sciguyryan** [KubeJS-Mods/KubeJS#68]
This is following on from the discussion on Discord.

It would be nice if there were were a means to add custom brewing stand recipes via KubeJS. This functionality was once available via CraftTweaker back in 1.12 as documented here:

https://docs.blamejared.com/1.12/fr/Vanilla/Recipes/Recipes_Brewing_Stand/

From what I can dig up this was added in the following (messy) commit: https://github.com/CraftTweaker/CraftTweaker/commit/d065dcae72de7394f73b83f0fa4a60a7e040e7b0

This functionality does not exist in 1.16 as far as I can see.

This is a pretty niche enhancement but I would appreciate it if this is something that you might consider implementing. I plan on making use of something like this for the modpack that I am currently building.

Thanks for taking the time to read and consider this request, and for the fantastic mod. I haven't been using KubeJS for long but it is simple and easy to use.

**Comment by MaxNeedsSnacks** [comment]
God, this will be a pain to implement, but yes, this should be planned for the future (although it's definitely on the backburner)

**Comment by elhertz** [comment]
I could use this to remove brewing recipes from mods that do not offer config to do so.

**Comment by superon** [comment]
me <3 +1

**Comment by MaxNeedsSnacks** [comment]
This has been implemented in AlmostReliable's [MoreJS](https://www.curseforge.com/minecraft/mc-mods/morejs) (on 1.18 and 1.19), and because we don't want to reinvent the wheel here, it likely won't be part of KubeJS itself anytime soon, so I'm going to be closing this for now ^^
