### ISSUE TITLE
IE Crash: Server Tick Loop

### ISSUE THREAD

**Issue by FooterMan15** [KubeJS-Mods/KubeJS#683]
### Minecraft Version

1.19.2

### KubeJS Version

build.337

### Rhino Version

build.268

### Architectury Version

6.5.85

### Forge/Fabric Version

🔨 43.2.21

### Describe your issue

IE Crashes on **World Load**, showing either errors:
``` java.lang.RuntimeException: Empty array ```
``` java.lang.ArrayIndexOutOfBoundsException: Index 0 out of bounds for length 0 ```

The World is generated just fine, you can load into it after reloading the game.
I confirmed this is an interaction with IE and Kube, as disabling Kube stops the error.

### Crash report/logs

https://gist.github.com/FooterMan15/87caf2e3fa4009c2f621716c9f844869

**Comment by adamico** [comment]
I had a similar issue and found out these mods are conflicting in some obscure way:

- KubeJS
- YeetusExperimentus
- SkyblockBuilder
- ImmersiveEngineering

I see in your logs you have these three mods as well.

Removing YeetusExperimentus was the least hurting solution for my modpack.

**Comment by FooterMan15** [comment]
I don't work on my instance that had the issue anymore, so I'll just keep this in mind if I have the issue again on another instance I work on.
