### ISSUE TITLE
'minecraft:mineable/pickaxe' tag not working in game

### ISSUE THREAD

**Issue by supermagic1** [KubeJS-Mods/KubeJS#690]
### Minecraft Version

1.18.2

### KubeJS Version

KubeJS Forge 1802.5.5-build.569

### Rhino Version

Rhino Forge 1802.2.1-build.255

### Architectury Version

[Forge 1.18.2] v4.11.93

### Forge/Fabric Version

Forge 40.2.10

### Describe your issue

I can't mine the block with my diamond pickaxe. When I go into the game to look at the tags, it doesn't show the `'minecraft:mineable/pickaxe'` tag.

code:
`event.create('my_block').displayName('My Block').material('stone').tagBlock('minecraft:needs_diamond_tool').requiresTool(true).hardness(4.5).tagBlock('minecraft:mineable/pickaxe')`

**Comment by ChiefArug** [comment]
Does it work for the `needs_diamond_tool` tag?
Also, please provide your logs. They have a lot of useful information in them that is pretty essential to solving most issues, this one included.

**Comment by ChiefArug** [comment]
Chances are it is another mod breaking the tag (so nothing in your modpack will be able to be mined by a pickaxe) by trying to add a non-existant block to the tag. The logs can confirm that though, and will say which mod is doing it.

**Comment by supermagic1** [comment]
Log: https://mclo.gs/Rhr8hj5

`[08:23:49] [Worker-Main3/ERROR] [minecraft/TagLoader]: Couldn't load tag minecraft:mineable/pickaxe as it is missing following references: excavated_variants:red_sandstone_nitre_ore (from dynamic_asset_generator:data), `
could be the issue

**Comment by ChiefArug** [comment]
It will be that causing it. Report the issue to excavated variants.
