### ISSUE TITLE
Crash on Singleplayer Select

### ISSUE THREAD

**Issue by Afrocntrik** [KubeJS-Mods/KubeJS#691]
### Minecraft Version

1.20.1

### KubeJS Version

2001.6.2-build.8

### Rhino Version

2001.2.2-build.4

### Architectury Version

9.1.12

### Forge/Fabric Version

Fabric Loader 0.14.22

### Describe your issue

Game crashes when clicking the singleplayer select screen.

### Crash report/logs

https://gist.github.com/Afrocntrik/e292241690341962659e4ea525b483e8

**Comment by ChiefArug** [comment]
Please send the full log file, that crash report is not enough.

**Comment by Afrocntrik** [comment]
[latest.log](https://github.com/KubeJS-Mods/KubeJS/files/12444323/latest.log)

**Comment by ChiefArug** [comment]
Gregtech is having issues
`Unknown registry key in ResourceKey[minecraft:root / minecraft:worldgen/placement_modifier_type]: gtceu:biome_placement`
I dont think KubeJS has anything to do with this.
