### ISSUE TITLE
InvalidMixinException: Found a remappable @Shadow annotation on children

### ISSUE THREAD

**Issue by andriihorpenko** [KubeJS-Mods/KubeJS#693]
### Minecraft Version

1.19.2

### KubeJS Version

1902.6.1-build.364

### Rhino Version

1902.2.2-build.272

### Architectury Version

6.5.85

### Forge/Fabric Version

Forge 43.2.21

### Describe your issue

The exception is thrown on server startup. Servers keeps starting up, though this exact mixin is having troubles loading.
Attached the exception from the log below.

### Crash report/logs

https://bytebin.lucko.me/Fovq7x9BhK

**Comment by MaxNeedsSnacks** [comment]
Fixed indev, thanks for the report!

**Comment by RonaldReagan-byte** [comment]
I'm still having the same issue
