### ISSUE TITLE
When present concurrently with gtceu, it will result in dispatching CONSTRUCT.

### ISSUE THREAD

**Issue by Tki-sor** [KubeJS-Mods/KubeJS#699]
### Minecraft Version

1.20.1

### KubeJS Version

2001.6.3-build.23

### Rhino Version

2001.2.2-build.6

### Architectury Version

9.1.12

### Forge/Fabric Version

forge 47.1.75

### Describe your issue

The loading progress is stuck at 'dispatching CONSTRUCT'. 
<img width="429" alt="{5D10C4FF-6A73-448a-8A06-EC50A8E9BE88}" src="https://github.com/KubeJS-Mods/KubeJS/assets/78548154/bf0f93ce-49db-4009-aded-0b53365d1648">

**Comment by screret** [comment]
Already fixed.

**Comment by JuiceyBeans** [comment]
Is this an issue with Kube or GT? Can reproduce
