### ISSUE TITLE
Crash after Saving and Quitting World

### ISSUE THREAD

**Issue by NillerMedDild** [KubeJS-Mods/KubeJS#7]
The game crashes every time I press Save and Quit World, when the world is Open to LAN.
[Crash report](https://gist.github.com/NillerMedDild/f4340862052c26c003146f9c82218505)

### Version
- kubejs-2.3.3.2
- Forge-1.15.2-31.1.0

**Comment by Kamefrede** [comment]
Can confirm that it's still happening on latest KubeJS version ( 2.3.3.5 )

**Comment by Naxanria** [comment]
Can confirm this works. Server closed and got a crash. 
[crash-2020-03-06_20.36.53-client.txt](https://github.com/KubeJS-Mods/KubeJS/files/4300132/crash-2020-03-06_20.36.53-client.txt)

**Comment by LatvianModder** [comment]
Should be fixed in https://jenkins.latmod.com/job/KubeJS/18/
