### ISSUE TITLE
Error with using `DustParticleOptions` class

### ISSUE THREAD

**Issue by Kardane** [KubeJS-Mods/KubeJS#700]
### Minecraft Version

1.20.1

### KubeJS Version

kubejs-fabric-2001.6.3-build.37

### Rhino Version

rhino-fabric-2001.2.2-build.6

### Architectury Version

architectury-9.1.12-fabric

### Forge/Fabric Version

Fabric 0.14.22

### Describe your issue

```js
let DustOption = Java.loadClass("net.minecraft.core.particles.DustParticleOptions");
let Vector3f = Java.loadClass("net.minecraft.world.phys.Vec3");

ServerEvents.customCommand(event=>{
  if(event.id == 'a') {
    let p = event.player
    event.level.sendParticles(DustOption(Vector3f(1,1,1),1.0),p.x,p.y,p.z, 10, 0.5,0,0.5, 1)
  }
})
```
This gives following error: Error occurred while handling event 'ServerEvents.customCommand': Java constructor for "net.minecraft.class_2390" with arguments "net.minecraft.class_243,number" not found.

**Comment by ChiefArug** [comment]
Wrong vector class, it needs `org.joml.Vector3f` not Minecraft's Vector3f.
