### ISSUE TITLE
mystical agriculture nbt not working

### ISSUE THREAD

**Issue by TomChelsea08** [KubeJS-Mods/KubeJS#702]
### Minecraft Version

1.19.2

### KubeJS Version

kubejs-forge-1902.6.2-build.15.jar

### Rhino Version

rhino-forge-1902.2.2-build.272.jar

### Architectury Version

 architectury-6.5.85-forge.jar

### Forge/Fabric Version

forge 43.2.8

### Describe your issue

so im trying to make a custom recipe for creeper seeds  from mystical agriculture and im having trouble setting the soul jar as it has an nbt and i cant seem to get it to work. im trying to do this in mechanical crafters using the latest version of kubejs create and it doesnt seem to work. here is my script for it. any help?

  e.recipes.create.mechanical_crafting('mysticalagriculture:creeper_seeds', [
    'AADDAA',
    'AADDAA',
    'DDBBDD',
    'DDBBDD',
    'AADDAA',
    'AADDAA'
  ], {
    A: Item.of('mysticalagriculture:soul_jar', '{Souls:10.0d,Type:"mysticalagriculture:creeper"}'),
    D: '#forge:storage_blocks/tertium_essence',
    B: 'mysticalagriculture:soulium_seed_base'
  })

**Comment by CelestialAbyss** [comment]
`Item.of()` ignores NBT by default in KJS 6.0+.

Try this:
```js
A: Item.of('mysticalagriculture:soul_jar', '{Souls:10.0d,Type:"mysticalagriculture:creeper"}').weakNBT(),
```

**Comment by TomChelsea08** [comment]
> `Item.of()` ignores NBT by default *for ingredients in KJS 6.0+.
> 
> Try this:
> 
> ```js
> A: Item.of('mysticalagriculture:soul_jar', '{Souls:10.0d,Type:"mysticalagriculture:creeper"}').weakNBT(),
> ```

You legend, works perfectly. Thanks very much.

**Comment by CelestialAbyss** [comment]
Don't forget to close this issue.
