### ISSUE TITLE
Game crashes when entering world creation menu [1.19.2 Forge]

### ISSUE THREAD

**Issue by Zelta-Deluxe** [KubeJS-Mods/KubeJS#704]
### Minecraft Version

1.19.2

### KubeJS Version

1902.6.2-build.3

### Rhino Version

1902.2.2-build.272

### Architectury Version

6.5.85

### Forge/Fabric Version

Forge 43.2.23

### Describe your issue

When I go into the world creation menu the game crashes. It does the same when joining a world.

### Crash report/logs

https://github.com/KubeJS-Mods/KubeJS/files/12569870/latest.log

**Comment by Donaldino7712** [comment]
uninstall hammerlib
