### ISSUE TITLE
Block/ore breaking

### ISSUE THREAD

**Issue by imbrunao** [KubeJS-Mods/KubeJS#707]
### Minecraft Version

1.16.5

### KubeJS Version

1605.3.19-build.299

### Rhino Version

1605.1.5-build.75

### Architectury Version

1.32.68

### Forge/Fabric Version

forge-36.2.35

### Describe your issue

Look at this code:
"onEvent("block.registry", (event) => {
    event.create("copper_ore")
    .displayName("Copper Ore")
    .material("rock")
    .hardness(4.4)
    .resistance(1.0)
    .requiresTool(true)
    .tagBlock("mineable/pickaxe")
    .tagBlock('minecraft:needs_iron_tool')
})". Even if I enter this code, when entering the world, I can still break the Copper Ore with a wooden or stone pickaxe, but how? Because I set it to break only if you are using at least an iron pickaxe. Anyway, can anyone help me solve this? Remembering that I'm using version 1.16.5 of Minecraft!!!!

**Comment by ChiefArug** [comment]
1.16 does not use tags to determine how blocks are mined.

Instead you use [harvestTool(tool, level)](https://wiki.latvian.dev/books/kubejs-legacy/page/custom-blocks#:~:text=harvestTool(%27tool%27%2C%20level)%C2%A0).
