### ISSUE TITLE
KubeJs Requires Rhino

### ISSUE THREAD

**Issue by djhajjar** [KubeJS-Mods/KubeJS#71]
![image](https://user-images.githubusercontent.com/35077250/106224835-a1fcd200-61a9-11eb-84d2-a9abe9a146fc.png)
MC 1.16.4
Forge 35.1.37
KubeJS-1605.3.5-build.155-forge.jar
rhino 1.7.13-build.12

Might just be the version looking for a rhino version without "-build"

**Comment by MzzVixen** [comment]
I'm getting this error too,

**Comment by LatvianModder** [comment]
Should be fixed in latest update
