### ISSUE TITLE
Random Crash

### ISSUE THREAD

**Issue by lightningwolfblade** [KubeJS-Mods/KubeJS#712]
### Minecraft Version

1.19.2

### KubeJS Version

kubejs-forge-1902.6.2-build.3

### Rhino Version

rhino-forge-1902.2.2-build.272

### Architectury Version

architectury-6.5.85-forge

### Forge/Fabric Version

Forge - 43.3.0

### Describe your issue

Whenever I install KubeJS, my game crashes. Ive gone through older versions of Rhino and KubeJS. So far i cant find any issues other than it just crashing. For some reason I am not getting a crash report, so ill give the launcher log.
[2023-09-28-1.log.gz](https://github.com/KubeJS-Mods/KubeJS/files/12751104/2023-09-28-1.log.gz)

**Comment by ChiefArug** [comment]
That isn't a launcher log. Its an archive of the latest.log that says you need a specific version of Create
```
Missing or unsupported mandatory dependencies:
	Mod ID: 'create', Requested by: 'create_mechanical_extruder', Expected range: '[0.5.1.e,)', Actual version: '0.5.1.b'
```
