### ISSUE TITLE
Loaded Mods Check

### ISSUE THREAD

**Issue by pjlasl** [KubeJS-Mods/KubeJS#72]
Is there an event that can be accessed to check if a particular mod is loaded?

I have recipes I would like loaded only if the mod is present.

**Comment by MaxNeedsSnacks** [comment]
you can use `Platform.isLoaded(modid)` at any point in your script to see whether a mod is currently loaded or not

**Comment by pjlasl** [comment]
Worked Perfectly! I looked thru the documentation and couldn't find anything.

**Comment by LatvianModder** [comment]
`if (Platform.mods.modidhere)` also works
