### ISSUE TITLE
Crash with applied Applied Energistics 2

### ISSUE THREAD

**Issue by sevenninesixthree** [KubeJS-Mods/KubeJS#720]
### Minecraft Version

1.20.1

### KubeJS Version

nope

### Rhino Version

nope

### Architectury Version

9.1.12

### Forge/Fabric Version

forge 47.2.1

### Describe your issue

When I open any _ME Terminal_, the game will crash.
[latest.log](https://github.com/KubeJS-Mods/KubeJS/files/12858909/latest.log)

**Comment by Donaldino7712** [comment]
it's erroring about some rei class not being found - this is not related to kubejs
