### ISSUE TITLE
Cannot connect to server: Unknown Serializer type 111

### ISSUE THREAD

**Issue by Donokami** [KubeJS-Mods/KubeJS#721]
### Minecraft Version

1.19.2

### KubeJS Version

1902.6.2-build.15

### Rhino Version

1902.2.2-build.272

### Architectury Version

6.5.85

### Forge/Fabric Version

Quilt 0.21.0

### Describe your issue

When playing on a quilt server with my friends, after 15-50 mins of gameplay (it is random, and independent for each player), the client disconnects from the server with the error `Connection Lost` - `Internal Exception: io.netty.handler.codec.DecoderException: Unknown serializer type 111`.
It was hard to debug as my modpack has 200 mods, but finally removing KubeJS (I did it on both server and client) was the solution to let people connect to the server.
There is nothing relevant in the server logs except this:
```
mc-server  | [10:27:15] [Server thread/INFO]: [Kiyoshi: Set the time to 1000]
mc-server  | [10:27:19] [Server thread/INFO]: [Kiyoshi: Set own game mode to Survival Mode]
mc-server  | [10:27:20] [Server thread/INFO]: [Kiyoshi: Set own game mode to Creative Mode]
mc-server  | [10:27:22] [Server thread/INFO]: [Kiyoshi: Set own game mode to Spectator Mode]
mc-server  | [10:27:26] [Netty Epoll Play IO Thread #0/ERROR]: Exception occurred in netty pipeline
mc-server  | io.netty.channel.unix.Errors$NativeIoException: readAddress(..) failed: Connection reset by peer
mc-server  | [10:27:26] [Server thread/INFO]: Kiyoshi lost connection: Disconnected
mc-server  | [10:27:26] [Server thread/INFO]: Kiyoshi left the game
```
[The modlist is available here](https://github.com/Donokami/the-adventurers-journey/tree/f70076ce5287bea993fc20b180bd0859978a4080#projects-bundled-in-this-modpack).

## Solutions tried

- Removing the `world/playerdata/<uuid.dat>` enables temporary a user to log on the server, but the issue comes back in less than 5 minutes (without any specific action from the user)
- I parsed the above NBT file between a file that doesn't let the player log and one where the player is still working in the server. No interesting difference, both data are similar
- Before removing KubeJS, I tried to remove Krypton, Charm, VeryManyPlayer, Fabric Carpet, Bobby, REI (and Create Fabric REI fix), ShulkerBoxTooltip and Fabric Seasons. It didn't change anything
- Removing KubeJS, KubeJS Create and PonderJS. It finally did the job!

### Crash report/logs

https://mclo.gs/1NrqOEw (client)

**Comment by ChiefArug** [comment]
What scripts (if any) do you have?
Notably do you have any that use `player.persistentData` or `player.sendData`?

**Comment by Donokami** [comment]
I'm really sorry.
Wrong assumption: I wasn't reproducing the bug after removing KubeJS for a long time so I though it was KubeJS fault.
But after a while, even without KubeJS it was happening (more rarely, but the bug is so random that I can't say that KubeJS has an effect on it). 
The fault is either on Fabric Carpet, Debugify or Very Many Players!
