### ISSUE TITLE
Crash from mod menu

### ISSUE THREAD

**Issue by Quantarious** [KubeJS-Mods/KubeJS#723]
### Minecraft Version

1.19.2

### KubeJS Version

1902.6.2-build.15

### Rhino Version

1902.2.2-build.272

### Architectury Version

6.5.85

### Forge/Fabric Version

Forge 1.19.2-43.3.2

### Describe your issue

Clicking KubeJs mod menu causes crash.

[crash-2023-10-13_13.11.21-client.txt](https://github.com/KubeJS-Mods/KubeJS/files/12900274/crash-2023-10-13_13.11.21-client.txt)
[debug.log](https://github.com/KubeJS-Mods/KubeJS/files/12900285/debug.log)

https://github.com/KubeJS-Mods/KubeJS/assets/17300639/3aeacf96-16ab-4453-9953-c2a4432e509c

**Comment by ChiefArug** [comment]
Probably caused by this option having folders in it: https://github.com/KubeJS-Mods/KubeJS/blob/1902/forge/src/main/resources/META-INF/mods.toml#L14
