### ISSUE TITLE
Enhancement: the ability to use Forge biome categories in worldgen.add

### ISSUE THREAD

**Issue by sciguyryan** [KubeJS-Mods/KubeJS#73]
This is a follow-up from the discussion on Discord.

I am requesting the ability to use the forge biome categories (see below) for the biomes.value property.

The logic for this request being that some mods might add their own categories and this would allow supporting those directly in KubeJS. It also makes sense to be able to use them as mods will be using the Forge tags, making things more consistent.

I would propose a prefix (such as $ or %) for this so as to not confuse them with the tags already implemented.

The list of the vanilla biome categories can be found here: https://github.com/MinecraftForge/MinecraftForge/blob/53eedb0f102bb1d8cf9432fae891730481206bce/src/main/java/net/minecraftforge/common/BiomeDictionary.java#L286

**Comment by MaxNeedsSnacks** [comment]
This has been implemented in 1.18.1, though that said BiomeDictionary will soon be removed from Forge due to the introduction of biome tags (and removal of BiomeCategory in 1.19)
