### ISSUE TITLE
Wrong amount of fluid in recipe

### ISSUE THREAD

**Issue by TaraDaReal** [KubeJS-Mods/KubeJS#733]
### Minecraft Version

1.20.1

### KubeJS Version

2001.2.2-build.73

### Rhino Version

2001.2.2-build.11

### Architectury Version

9.1.12

### Forge/Fabric Version

Fabric 0.14.22

### Describe your issue

I make a custom fluid and a recipe with it and JEI shows that it uses 2mb of that fluid but in the code i specified 200mb.

serverscript
``
// Mod Shortcuts

let MOD = (domain, id, x) => (x ? `${x}x ` : "") + (id.startsWith('#') ? '#' : "") + domain + ":" + id.replace('#', '')
let KJ = (id, x) => MOD('kubejs', id, x)
let F = (id, x) => MOD('forge', id, x)
let MC = (id, x) => MOD('minecraft', id, x)

ServerEvents.recipes(e => {
    e.recipes.create.pressing(["kubejs:empty_tray", "kubejs:meth"], "kubejs:meth_tray")
    e.recipes.create.filling("kubejs:meth_tray", [Fluid.of("kubejs:liquid_meth", 200), KJ('empty_tray')])
})
``

clientscript
``
StartupEvents.registry('item', e => {
    e.create('meth').displayName("Meth Powder").food(food => {
        food
        .hunger(0)
        .saturation(0)
        .effect('haste', 100, 2, 100)
        .alwaysEdible()
        .fastToEat()
        .eaten(ctx => global.methMsg(ctx))
    })

    e.create('empty_tray')
    .unstackable()
    .displayName("Empty Tray")

    e.create('meth_tray')
    .unstackable()
    .displayName("Meth Tray")
})

global.methMsg = ctx => {
    ctx.player.tell("You feel energetic...")
}

StartupEvents.registry('fluid', e => {
    e.create('liquid_meth')
        .thinTexture(Color.WHITE)
        .displayName("Liquid Meth")
})
``

**Comment by Notenoughmail** [comment]
Fabric uses droplets instead of mB for its fluid amounts, there are 81,000 droplets per bucket

**Comment by MaxNeedsSnacks** [comment]
^ Use the FluidAmounts wrapper (for example `FluidAmounts.BUCKET` or `420 * FluidAmounts.MB`) or multiply your current values by 81, this is not a KubeJS decision
