### ISSUE TITLE
[Request] Improved Client Reload

### ISSUE THREAD

**Issue by Brittank88** [KubeJS-Mods/KubeJS#74]
Hoping for a clientside reloading command that allows you to **control** whether the textures/sound engine are reloaded. Sometimes we do want to reload textures, sometimes we only want to reload say, JEI.

In a way, the more granular this command can be in terms of what is actually reloaded, the better!

**Comment by Spiker985** [comment]
@MaxNeedsSnacks Is this still planned? Perhaps, something like `/kubejs reload x` where x is the subsystem?

**Comment by MaxNeedsSnacks** [comment]
Already done iirc
