### ISSUE TITLE
Quality of Life repo settings

### ISSUE THREAD

**Issue by Anoyomouse** [KubeJS-Mods/KubeJS#740]
### Describe the feature

Hi
Today i realized some items in my playthough of the DW20 1.20 pack get a tag that says { Picked: 1b }, and i searched my MC folder and found that your mod matched that statement, however, if i came to your repository, i cannot use GitHub's code search feature as your default branch is your workflows branch, and GitHub only allows you to search the default branch

Could i encourage you to change your default branch to the latest version of minecraft so that GitHub's code search feature would work on your mod (at least for the latest version), so we can search for things without needing to clone the code locally?

Also, thanks for the great mod :)

### Additional info

In order to code search the repo you have to clone it locally and then do the code search.

GitHub's reference search and powerful code features don't work well without this default branch being set

**Comment by Anoyomouse** [comment]
Just as an aside, it's not your mod that's adding the "Picked" tag, i was trying to verify it when i discovered this "issue" :)

**Comment by ChiefArug** [comment]
KubeJS supports multiple minecraft versions and keeps a branch for each. KubeJS also uses GitHub Actions to build and publish.
GitHub Actions works off configuration files located in the default branch of your repository. Actions can affect any branch, but are only read from the default one.
By having a workflows branch as the default, all the different versions building and publishing Actions are kept in one place that makes more sense (well more sense than a newer MC version).
The workflows branch also has things like issue/pr templates and the readme.

Lat (owner) has said that he will make an external site for looking at code to solve this issue, but I haven't heard of any progress on that.

(I do agree that it should be set up with an actual branch as default, as contributions are also only counted to the default branch. I'm just explaining whats been explained to me)

**Comment by Anoyomouse** [comment]
Aah, thank you for explaining, I was assuming there was something like that, however I did not know the reason.

It sucks that GitHub actions are based off the default branch, that makes things more difficult

Assuming this issue will get closed then, maybe after a comment about the code search alternative

**Comment by pietro-lopes** [comment]
> Aah, thank you for explaining, I was assuming there was something like that, however I did not know the reason.
> 
> It sucks that GitHub actions are based off the default branch, that makes things more difficult
> 
> Assuming this issue will get closed then, maybe after a comment about the code search alternative

here is what I do, I just add to the github url 1s, so it will be 
https://github1s.com/KubeJS-Mods/

it will open up some sort of VScode

you can also just press `.` to open github dev.

and than use the search there

**Comment by MaxNeedsSnacks** [comment]
Gonna take care of this eventually once we (inevitably) switch to better CI, but for now this isn't gonna change, sorry ^^;
