### ISSUE TITLE
Enhancement: allow ore generation to use either range or depth average.

### ISSUE THREAD

**Issue by sciguyryan** [KubeJS-Mods/KubeJS#75]
Hi.

Following on from the discussion on Discord, I am requesting the ability to be able to configure the ore generation via worldgen.add to use either range or depth average.

Depth average is used to generate lapis and everything else is generated via range, in vanilla generation.

The link to the discussion is as follows: https://discord.com/channels/303440391124942858/615627049637380144/805811248230957168

Cheers!

**Comment by Spiker985** [comment]
Closing, since 1.16 is feature-complete, and this has been superseded/implemented in 1.18 (see https://github.com/KubeJS-Mods/KubeJS/pull/149#issuecomment-1024502210)
