### ISSUE TITLE
Script is grabbing the wrong array on launch, but works properly on reload

### ISSUE THREAD

**Issue by aaronhowser1** [KubeJS-Mods/KubeJS#752]
### Minecraft Version

1.19.2

### KubeJS Version

kubejs-forge-1902.6.2-build.45

### Rhino Version

rhino-forge-1902.2.2-build.280

### Architectury Version

architectury-6.5.85-forge

### Forge/Fabric Version

Forge 43.3.5

### Describe your issue

So I have a [lists.js](https://gist.github.com/aaronhowser1/1c4f02b225222cfebf1ce23e8a8f4bb0) that has the arrays `customItems`, `jeiOnlyItems`, `jeiItems`, and `itemsToRemove`.

The script [emi.js](https://gist.github.com/aaronhowser1/f065d1e395f29b04015d810c21f9773b) makes a json file for use with the mod EMI. The json is output to the [client.log](https://gist.github.com/aaronhowser1/31df3d690c0eb1116de39100eb519c81) for testing purposes.

![image](https://github.com/KubeJS-Mods/KubeJS/assets/15698722/09f6af65-a9b1-48c3-9607-a7fdabb1c899)

That's definitely not right. Even aside from the fact that everything has repeating NBT and is *air* for some reason, all of those have the nbt `hone/gild_5`.

The thing is, that's in the *added* section of the json. That part of the json only gets things added to it via an iterator on customItems in emi.js. customItems doesn't HAVE anything with the nbt `hone/gild_5` in it. `jeiOnlyItems` does. That array is never even LOADED by emi.js.

After doing F3+T however, [it works fine](https://gist.github.com/aaronhowser1/53d66f1f9b89593df1c2b309d7b978d3)! What gives?
![image](https://github.com/KubeJS-Mods/KubeJS/assets/15698722/f5623813-2f05-4743-b0f4-130b6d206dd0)

**Comment by pietro-lopes** [comment]
Those consts are outside any event and it is too soon for modded items, hence why only Minecraft items shows up.
You need to load it lazily or come up with some function to load those variable just before you use them

**Comment by aaronhowser1** [comment]
Would replacing `const thing = []` with `function getThing() { return [] }` work?

**Comment by ChiefArug** [comment]
KubeJS should log a warning about getting an ingredient before all items are registered.
This is the second issue where this happened

**Comment by aaronhowser1** [comment]
Technically isn't the NBT thing still an issue though? There's no reason it should have the gild whatever nbt in the add place since no item with that is in the list being iterated over for the add place

**Comment by ChiefArug** [comment]
I suspect that might be a mod mistakenly attaching nbt to empty items.

**Comment by aaronhowser1** [comment]
That specific NBT is the NBT of one of the items in the other list, though. It's not just some arbitrary random NBT, it's a direct match

**Comment by ChiefArug** [comment]
Probably something being cached weirdly then. I don't think its much of an issue unless you can reproduce it in more normal circumstances.
