### ISSUE TITLE
[INVALID: User error] Specifying a custom model for a custom block with new textures errors out with Minecraft expecting it to be included in a texture atlas

### ISSUE THREAD

**Issue by MCAlexisYT** [KubeJS-Mods/KubeJS#755]
### Minecraft Version

1.20.1

### KubeJS Version

2001.6.4-build.111

### Rhino Version

2001.2.2-build.18

### Architectury Version

9.1.12

### Forge/Fabric Version

Fabric 0.15.1

### Describe your issue

Its basically all described in the title, however, I want to make a clarification: By "errors out", I mean "textures won't load".
The message left in the logs reads as follows: `Missing textures in model kubejs:lapis_bricks#inventory:minecraft:textures/atlas/blocks.png:kubejs:block/lapis_bricks`
Despite the fact that the path of the texture in the model being `kubejs:block/bricks/lapis`, it tried to load `kubejs:block/lapis_bricks`, which doesn't exist.

**Comment by ChiefArug** [comment]
This sounds like your custom model isn't being loaded.
Can you provide the script you are using to change the model, or the model json **and** the full file path of it relative to the `kubejs` folder?

**Comment by MCAlexisYT** [comment]
@ChiefArug I put the model file directly in the `models` folder, while the script specifies `kubejs:block/lapis_bricks`. An invalid model reference in the `"parent"` tag in the model file is better than the model file itself not loading at all. I made the mistake of referencing a nonexistent model "_located_" at `minecraft:cube_all` instead of `minecraft:block/cube_all`.

**Comment by ChiefArug** [comment]
Ah, yeah. Common mistake to make.
Good to know you managed to figure it out!
