### ISSUE TITLE
Burntimes for ItemBuilder

### ISSUE THREAD

**Issue by WhitePhant0m** [KubeJS-Mods/KubeJS#76]
I want my tiny coal without a separate mod for it

**Comment by MaxNeedsSnacks** [comment]
Due to the way vanilla does burntime (and how Forge and Fabric change it, respectively), this will require an update to Architectury API, feel free to track https://github.com/architectury/architectury-api/issues/37 for updates, but it's rather low-priority for now

**Comment by MaxNeedsSnacks** [comment]
An update on this: https://github.com/architectury/architectury-api/pull/81 is about to merged, so this will *probably* be added soon ^^

**Comment by MaxNeedsSnacks** [comment]
Should be implemented in the newest build, use `item.burnTime(Number)` during registry / modification ^^
