### ISSUE TITLE
Not using system language by default when used with Language Reload

### ISSUE THREAD

**Issue by Rad586** [KubeJS-Mods/KubeJS#764]
### Minecraft Version

1.19.2

### KubeJS Version

1902.6.2-build.45

### Rhino Version

1902.2.2-build.280

### Architectury Version

6.5.85

### Forge/Fabric Version

0.14.24(fabric)

### Describe your issue

❌ With only fabric api installed, the game won't use system language by default(vanilla does, though). 
✔ However, when installed language reload mod(ver 1.5.10), it follows system language. 
✔ Adding rhino or architectury turns out fine. 
❌ But after adding kubejs, the game is not using system language(it uses en_us) like before. 

I tried reversing all kjs config options, but it doesn't work. 

**Impact:** 
This affects non-English speakers, which can cause some confusion when playing modpacks, and becames critical if they don't use English at all, or the language button is hidden. 

**Steps to reproduce:** 
1. Change your system language to something **not** `en_us`(for me, it's zh_cn). 
2. Install the mod mentioned above **except** kubejs(fabric api, language reload). 
3. Launch the game, let it generate `options.txt`(game using system language now), then close it. 
4. Delete `options.txt`.
5. Install kubejs(and its dependencies). 
6. Launch the game again(game using `en_us`, not `system language`).

**Comment by Jerozgen** [comment]
Removing [this line](https://github.com/KubeJS-Mods/KubeJS/blob/3117d8c35b0551bce217db09e5ac9f11b62842df/common/src/main/java/dev/latvian/mods/kubejs/KubeJS.java#L89) fixes the issue

**Comment by MaxNeedsSnacks** [comment]
I think I removed this line a while ago, just forgot to close the issue, whoops!
