### ISSUE TITLE
Ability to add the "flavor text" to custom upgrade/trim templates

### ISSUE THREAD

**Issue by generikb** [KubeJS-Mods/KubeJS#767]
### Describe the feature

Hello!

Would be great to be able to add the "Applies To", "Ingredients", "Title", "Base Slot", and "Additions Slot" descriptions to custom upgrade/trim template items.  (see screenshot below)

![image](https://github.com/KubeJS-Mods/KubeJS/assets/41623747/6de0962f-db72-4653-b96e-0e51c2bb0ea7)

thanks!

**Comment by Gcat101** [comment]
Can’t you just use the `ItemEvents.tooltip` event?

correct me if I’m wrong I don’t know shit about 1.20 :hih:

**Comment by ChiefArug** [comment]
Yes, you could just use the tooltip event, however having an item type would make it easier to match the formatting and in the case a mod uses instanceof SmithingTemplateItem to determine something then custom smithing templates would support that.

**Comment by ChiefArug** [comment]
After working on this I have also realised that the tooltip event doesn't allow you to set the custom text and icons in the smithing table. There may be a way to work around that, but a smithing template item type is the easiest way to add that behaviour.

**Comment by MaxNeedsSnacks** [comment]
Implemented by @ChiefArug in #768 \o/

**Comment by generikb** [comment]
Nice! Thanks all!
