### ISSUE TITLE
JEIEvents.removeCategories not working with EMI installed

### ISSUE THREAD

**Issue by SpeeeDCraft** [KubeJS-Mods/KubeJS#771]
### Minecraft Version

1.20.1

### KubeJS Version

kubejs-forge-2001.6.4-build.120

### Rhino Version

rhino-forge-2001.2.2-build.18

### Architectury Version

architectury-9.1.12-forge

### Forge/Fabric Version

Forge 47.2.6

### Describe your issue

Run the game with the mods installed and try to hide the categories, voila, nothing works.

Modlist:
1. jei-1.20.1-forge-15.2.0.27
2. emi-1.0.30+1.20.1+forge
3. KJS
4. Rhino
5. Architectury

Then try to hide, for example, `'minecraft:campfire_cooking'`
See nothing works

My script:
![image](https://github.com/KubeJS-Mods/KubeJS/assets/52341158/481c1721-0acb-45e1-94e2-0f858bd66236)

**Comment by FooterMan15** [comment]
JEI Events don't properly work when EMI is installed. Check if they're removed without EMI.

**Comment by SpeeeDCraft** [comment]
> JEI Events don't properly work when EMI is installed. Check if they're removed without EMI.

Still not, maybe I'm idiot, but :(
![image](https://github.com/KubeJS-Mods/KubeJS/assets/52341158/f1d4ecbb-befb-4a5a-b111-ca9fb4b3f226)

**Comment by FooterMan15** [comment]
The campfire category id is `minecraft:campfire`, that is your issue.

**Comment by SpeeeDCraft** [comment]
In any case, the problem with hiding categories with emi installed has not been fixed

**Comment by ChiefArug** [comment]
This might be on EMI's end, if they don't check for if a category is hidden.

**Comment by ChiefArug** [comment]
Actually, can you test with a non vanilla category, like one added by a mod?

**Comment by SpeeeDCraft** [comment]
Closed, because EMI adds own methods to hide/add items/categories and etc
