### ISSUE TITLE
Spawner argument in EntityEvents.CHECK_SPAWN

### ISSUE THREAD

**Issue by bloodsbro** [KubeJS-Mods/KubeJS#772]
### Describe the feature

For the system I want to implement, I need to know from which spawner the mob wants to appear in the CheckLivingEntitySpawnEventJS event

### Additional info

https://github.com/KubeJS-Mods/KubeJS/blob/2004/src/main/java/dev/latvian/mods/kubejs/entity/KubeJSEntityEventHandler.java#L23

**Comment by liopyu** [comment]
![image](https://github.com/KubeJS-Mods/KubeJS/assets/130418550/8134e7a2-b9e8-4bdd-97c2-72f783227120)

**Comment by liopyu** [comment]
![image](https://github.com/KubeJS-Mods/KubeJS/assets/130418550/aacc6332-1641-40f6-bece-19473979321d)

**Comment by liopyu** [comment]
this is from probejs addon mod, highly recommended

**Comment by bloodsbro** [comment]
I know this addon, and I even have it installed, maybe you misunderstood me, I need to find out in the event EntityEvents.checkSpawn from which spawner (minecraft:spawner) is trying to spawn mob

**Comment by liopyu** [comment]
did you check the first picture i sent you where it shows exactly what the "checkspawn" does?

**Comment by liopyu** [comment]
honestly this would be a lot easier to troubleshoot if you just joined the discord and opened up an actual support ticket

**Comment by MaxNeedsSnacks** [comment]
lio, the spawner argument isn't passed to the KubeJS-facing event, that's what they're asking for...

**Comment by liopyu** [comment]
oh i see, seems i misunderstood the question then

**Comment by MaxNeedsSnacks** [comment]
Added \o/
