### ISSUE TITLE
Add UtilsWrapper.parseBlockState(), delegating to the same method in UtilsJS

### ISSUE THREAD

**Issue by mikerooni** [KubeJS-Mods/KubeJS#776]
### Describe the feature

`UtilsJS.parseBlockState()` isn't exposed through `UtilsWrapper` right now.

It would be good to either have this method in `UtilsWrapper` as well, or a type wrapper for `BlockState`s.

**Comment by pietro-lopes** [comment]
We have:
`BlockStatePredicate`
For example, testing if you are stepping on grass block with snow
`BlockStatePredicate.of("minecraft:grass_block[snowy=true]").test(event.player.blockStateOn)`

what are your use cases?

**Comment by mikerooni** [comment]
I need to specifically supply a blockstate to a method call, so a predicate won't do unfortunately

**Comment by MaxNeedsSnacks** [comment]
Added in recent builds
