### ISSUE TITLE
When item id contains a /, .displayName doesn't work

### ISSUE THREAD

**Issue by DUDEbehindDUDE** [KubeJS-Mods/KubeJS#780]
### Minecraft Version

1.20.1

### KubeJS Version

2001.2.5-build.2

### Rhino Version

2001.2.2-build.18

### Architectury Version

9.1.12

### Forge/Fabric Version

Forge 47.2.17

### Describe your issue

When you are setting a displayName of an item made in KubeJS for an item that has a / in the name (say, "kubejs:metal/ingot/cobalt"), .displayName() property does not work at all.
Examples:
```js
// Fluid registry
e.create("nether_sludge")
    .stillTexture("tfc:block/molten_still")
    .flowingTexture("tfc:block/molten_flow")
    .color(0x434127)
    .displayName("Nether Sludge") // works!
    .noBlock();
    
e.create("metal/cobalt")
    .stillTexture("tfc:block/molten_still")
    .flowingTexture("tfc:block/molten_flow")
    .color(0x07276f)
    .displayName("Cobalt") // does not work
    .noBlock();
```
```js
// Item registry
e.create("metal/ingot/cobalt").displayName("Cobalt Ingot");
```

![image](https://github.com/KubeJS-Mods/KubeJS/assets/66212375/f76553a9-52f8-4549-bf5f-a4b41d746231)
![image](https://github.com/KubeJS-Mods/KubeJS/assets/66212375/167661ab-b210-46bb-8617-ef0cab582c1f)
![image](https://github.com/KubeJS-Mods/KubeJS/assets/66212375/a217c102-734b-4f6f-b36f-9ec8ef2e8cbb)

If I were to take a guess, the issue is likely that KubeJS treats this in the language file as "fluid.kubejs.metal/cobalt" instead of "fluid.kubejs.metal.cobalt"; this should be as simple as replacing any / with a . if this is the case.

**Comment by EvanHsieh0415** [comment]
![圖片](https://github.com/KubeJS-Mods/KubeJS/assets/74277414/60d15425-94ff-48f8-90e0-03c45956710e)
![圖片](https://github.com/KubeJS-Mods/KubeJS/assets/74277414/33e12d3c-e3e7-498a-bc47-5cdbfa33dc7a)
![圖片](https://github.com/KubeJS-Mods/KubeJS/assets/74277414/47672550-e16d-4611-892d-b74e133a58c7)
While `.displayName` doesn't work, KubeJS doesn't auto-generate the name either.

**Comment by MaxNeedsSnacks** [comment]
Should be fixed with https://github.com/KubeJS-Mods/KubeJS/commit/3b7d06b2cbc8cad1d1d094fd8b42da37154c8241?
