### ISSUE TITLE
kubejs has failed to load correctly

### ISSUE THREAD

**Issue by pingju555** [KubeJS-Mods/KubeJS#781]
### Minecraft Version

1.19.2

### KubeJS Version

1902.6.2-build.15

### Rhino Version

1902.2.3-build.284

### Architectury Version

6.5.90

### Forge/Fabric Version

Forge 43.3.0

### Describe your issue

A modpack Trying to mix Gregtech and Create
with these mod:Gregtech,Greate,Create,and Kubejs,Kubejs-create.

But, Continous Crush.
[crash-2024-02-07_00.34.12-fml.txt](https://github.com/KubeJS-Mods/KubeJS/files/14183725/crash-2024-02-07_00.34.12-fml.txt)

Anonther mod is mainly realted to Create;and some of botania,biome,terrian.
By the way ,a lot of resource-getting mod is also added.

### Crash report/logs

https://github.com/KubeJS-Mods/KubeJS/files/14183557/crash-2024-02-07_00.34.12-fml.txt

**Comment by FooterMan15** [comment]
Update all your mods, your Kube jar appears to be several versions behind. See what happens then.

**Comment by pingju555** [comment]
Saddly,I tried the Newest Version(1902.62.2-build 58),my launcher even dosen't recognize it.

**Comment by FooterMan15** [comment]
It appears you have Create Sifter. Try removing it.

**Comment by pingju555** [comment]
Here are the modlist
Curseforge Pattern.

[Create Goggles (Create Plus) (by Robocraft999)](https://www.curseforge.com/minecraft/mc-mods/create-goggles)
[Create: Connected (by Lysine)](https://www.curseforge.com/minecraft/mc-mods/create-connected)
[Botany Trees (by DarkhaxDev)](https://www.curseforge.com/minecraft/mc-mods/botany-trees)
[Rechiseled: Create (by SuperMartijn642)](https://www.curseforge.com/minecraft/mc-mods/rechiseled-create)
[Blueprint (by TeamAbnormals)](https://www.curseforge.com/minecraft/mc-mods/blueprint)
[Botany Pots Tiers (by Ultramegaaa)](https://www.curseforge.com/minecraft/mc-mods/botany-pots-tiers)
[Create Decoration Casing (by TheLynkYT)](https://www.curseforge.com/minecraft/mc-mods/create-decoration-casing)
[HardRock Tools & Materials (by sir_Robson)](https://www.curseforge.com/minecraft/mc-mods/hardrock-tools-materials)
[Create: More Automation (by Snakeypro)](https://www.curseforge.com/minecraft/mc-mods/create-more-automation)
[[BPOP]Botany Pots Ore Planting (by mango_buff)](https://www.curseforge.com/minecraft/mc-mods/botany-pots-ore-planting)
[Pam's HarvestCraft 2 - Food Core (by pamharvestcraft)](https://www.curseforge.com/minecraft/mc-mods/pams-harvestcraft-2-food-core)
[Create Hand Crafting (by sir_Robson)](https://www.curseforge.com/minecraft/mc-mods/create-hand-crafting)
[Configuration [Fabric | Forge] (by Toma)](https://www.curseforge.com/minecraft/mc-mods/configuration)
[Create: Factory (by antopfr90)](https://www.curseforge.com/minecraft/mc-mods/create-factory)
[Serene Seasons - Pam's HarvestCraft 2: Crops Compat (by Darkorg69)](https://www.curseforge.com/minecraft/mc-mods/serene-seasons-pams-harvestcraft-2-crops-compat)
[Create: Tipsy n' Dizzy (by MilkyFur)](https://www.curseforge.com/minecraft/mc-mods/create-tipsy-n-dizzy)
[Chunk By Chunk (by dividesBy0)](https://www.curseforge.com/minecraft/mc-mods/chunk-by-chunk)
[Curios API (Forge/NeoForge) (by TheIllusiveC4)](https://www.curseforge.com/minecraft/mc-mods/curios)
[Create Gourmet (by SilverGoId)](https://www.curseforge.com/minecraft/mc-mods/create-gourmet)
[Serene Seasons Fix (by Or_OS)](https://www.curseforge.com/minecraft/mc-mods/serene-seasons-fix)
[Create Utilities (Fabric/Forge) (by duquee___)](https://www.curseforge.com/minecraft/mc-mods/createutilities)
[Rubidium (by Asek3)](https://www.curseforge.com/minecraft/mc-mods/rubidium)
[Create: Bells & Whistles (by sudolev)](https://www.curseforge.com/minecraft/mc-mods/bellsandwhistles)
[Create: Estrogen (by Mayaqq)](https://www.curseforge.com/minecraft/mc-mods/estrogen)
[MythicBotany (by noeppinoeppi)](https://www.curseforge.com/minecraft/mc-mods/mythicbotany)
[KubeJS (by LatvianModder)](https://www.curseforge.com/minecraft/mc-mods/kubejs)
[Rechiseled (by SuperMartijn642)](https://www.curseforge.com/minecraft/mc-mods/rechiseled)
[Create: Easy Structures (by M_Productions)](https://www.curseforge.com/minecraft/mc-mods/create-easy-structures)
[Create: The Factory Must Grow (by Dr_Mango_Tea)](https://www.curseforge.com/minecraft/mc-mods/create-industry)
[Sand Box (by noeppinoeppi)](https://www.curseforge.com/minecraft/mc-mods/sand_box)
[Botania (by Vazkii)](https://www.curseforge.com/minecraft/mc-mods/botania)
[Mekanism Tools (by bradyaidanc)](https://www.curseforge.com/minecraft/mc-mods/mekanism-tools)
[Simple Metals: Tin (by pablonm7)](https://www.curseforge.com/minecraft/mc-mods/simplemetals-tin)
[Environmental (by TeamAbnormals)](https://www.curseforge.com/minecraft/mc-mods/environmental)
[Autumnity (by TeamAbnormals)](https://www.curseforge.com/minecraft/mc-mods/autumnity)
[Create: Liquid Fuel (by Forsteri123)](https://www.curseforge.com/minecraft/mc-mods/create-liquid-fuel)
[Create: Modern Train Parts (by dugske)](https://www.curseforge.com/minecraft/mc-mods/create-modern-train-parts)
[LibX (by noeppinoeppi)](https://www.curseforge.com/minecraft/mc-mods/libx)
[Create: Components and Additions (by StormDragon_64)](https://www.curseforge.com/minecraft/mc-mods/create-ca)
[Biomes O' Plenty (by Forstride)](https://www.curseforge.com/minecraft/mc-mods/biomes-o-plenty)
[Create: Biomimicry (by WitherTM)](https://www.curseforge.com/minecraft/mc-mods/biomimicry)
[Botanical Machinery (by MelanX)](https://www.curseforge.com/minecraft/mc-mods/botanical-machinery)
[Fruit Stack (by Mango_pill)](https://www.curseforge.com/minecraft/mc-mods/fruit-stack)
[GregTechCEu Modern (by KilaBash)](https://www.curseforge.com/minecraft/mc-mods/gregtechceu-modern)
[Mekanism (by bradyaidanc)](https://www.curseforge.com/minecraft/mc-mods/mekanism)
[Create: Design n' Decor (by MilkyFur)](https://www.curseforge.com/minecraft/mc-mods/create-design-n-decor)
[Create Enchantment Industry (by DragonsPlus)](https://www.curseforge.com/minecraft/mc-mods/create-enchantment-industry)
[Atmospheric (by TeamAbnormals)](https://www.curseforge.com/minecraft/mc-mods/atmospheric)
[Create Confectionery (by Furti_Two)](https://www.curseforge.com/minecraft/mc-mods/create-confectionery)
[Create Recycle Everything (by nocubeyt)](https://www.curseforge.com/minecraft/mc-mods/create-recycle-everything)
[project-871698 (by FusionSwarly)](https://www.curseforge.com/minecraft/mc-mods/project-871698)
[Kiwi 🥝 (Forge) (by Snownee)](https://www.curseforge.com/minecraft/mc-mods/kiwi)
[Rhino (by LatvianModder)](https://www.curseforge.com/minecraft/mc-mods/rhino)
[Neapolitan (by TeamAbnormals)](https://www.curseforge.com/minecraft/mc-mods/neapolitan)
[Botany Pots (by DarkhaxDev)](https://www.curseforge.com/minecraft/mc-mods/botany-pots)
[Create: Bitterballen (by pyzpre)](https://www.curseforge.com/minecraft/mc-mods/create-bitterballen)
[Create: Alloyed (by MythrilBagels)](https://www.curseforge.com/minecraft/mc-mods/create-alloyed)
[GeckoLib (by Gecko)](https://www.curseforge.com/minecraft/mc-mods/geckolib)
[Create Crafts & Additions (by MRHminer)](https://www.curseforge.com/minecraft/mc-mods/createaddition)
[Create Encased (by iglee42)](https://www.curseforge.com/minecraft/mc-mods/create-encased)
[Oculus (by Asek3)](https://www.curseforge.com/minecraft/mc-mods/oculus)
[Create Compact Exp (by nocubeyt)](https://www.curseforge.com/minecraft/mc-mods/create-compact-exp)
[Create: Electric Trains (by Pancake_01_)](https://www.curseforge.com/minecraft/mc-mods/create-electric-trains)
[Create Paper Line (by oierbravo_mc)](https://www.curseforge.com/minecraft/mc-mods/create-paper-line)
[MomentariyModder'Applications (by MomentariyModder)](https://www.curseforge.com/minecraft/mc-mods/momentariycore)
[Pam's HarvestCraft 2 - Food Extended (by pamharvestcraft)](https://www.curseforge.com/minecraft/mc-mods/pams-harvestcraft-2-food-extended)
[Create Jetpack (by possible_triangle)](https://www.curseforge.com/minecraft/mc-mods/create-jetpack)
[Fruitful Fun 🍊 (by Snownee)](https://www.curseforge.com/minecraft/mc-mods/fruit-trees)
[Create: Tweaked Controllers (by getItemFromBlock)](https://www.curseforge.com/minecraft/mc-mods/create-tweaked-controllers)
[Create : Creating Space (by RealAntEngineer)](https://www.curseforge.com/minecraft/mc-mods/create-creating-space)
[TerraBlender (Forge) (by TheAdubbz)](https://www.curseforge.com/minecraft/mc-mods/terrablender)
[Create: Unbreakable Tools (by anvian)](https://www.curseforge.com/minecraft/mc-mods/create-unbreakable-tools)
[Immersive Engineering (by BluSunrize)](https://www.curseforge.com/minecraft/mc-mods/immersive-engineering)
[Fruitstack Jei Support (by Mango_pill)](https://www.curseforge.com/minecraft/mc-mods/fruitstack-jei-support)
[Pam's HarvestCraft 2 - Crops (by pamharvestcraft)](https://www.curseforge.com/minecraft/mc-mods/pams-harvestcraft-2-crops)
[Create: Vintage Improvements (by Negodya1)](https://www.curseforge.com/minecraft/mc-mods/create-vintage-improvements)
[Create: Dreams & Desires (by Luna)](https://www.curseforge.com/minecraft/mc-mods/create-dreams-desires)
[Create Compression (by flipperpanda706)](https://www.curseforge.com/minecraft/mc-mods/create-compression)
[Create: Drinks (by Sietse)](https://www.curseforge.com/minecraft/mc-mods/create-drinks)
[Entity Culling Fabric/Forge (by tr7zw)](https://www.curseforge.com/minecraft/mc-mods/entityculling)
[Create: Netherless (by DariusZeBaguette)](https://www.curseforge.com/minecraft/mc-mods/create-netherless)
[Create Slime Craft (by Alex_ytLives)](https://www.curseforge.com/minecraft/mc-mods/create-slime-craft)
[Create (by simibubi)](https://www.curseforge.com/minecraft/mc-mods/create)
[TIS-3D (by Sangar_)](https://www.curseforge.com/minecraft/mc-mods/tis-3d)
[TIS-Create (by PwnagePineapple)](https://www.curseforge.com/minecraft/mc-mods/tis-create)
[Auto Third Person (by quat)](https://www.curseforge.com/minecraft/mc-mods/auto-third-person)
[FerriteCore ((Neo)Forge) (by malte0811)](https://www.curseforge.com/minecraft/mc-mods/ferritecore)
[Croptopia (by thethonk)](https://www.curseforge.com/minecraft/mc-mods/croptopia)
[Fusion (Connected Textures) (by SuperMartijn642)](https://www.curseforge.com/minecraft/mc-mods/fusion-connected-textures)
[SuperMartijn642's Config Lib (by SuperMartijn642)](https://www.curseforge.com/minecraft/mc-mods/supermartijn642s-config-lib)
[Create: Balanced Flight (Angel Ring) (by Anthxny)](https://www.curseforge.com/minecraft/mc-mods/create-balanced-flight)
[Mekanism Additions (by bradyaidanc)](https://www.curseforge.com/minecraft/mc-mods/mekanism-additions)
[Kotlin for Forge (by thedarkcolour)](https://www.curseforge.com/minecraft/mc-mods/kotlin-for-forge)
[Mekanism Generators (by bradyaidanc)](https://www.curseforge.com/minecraft/mc-mods/mekanism-generators)
[SuperMartijn642's Core Lib (by SuperMartijn642)](https://www.curseforge.com/minecraft/mc-mods/supermartijn642s-core-lib)
[Patchouli (by Vazkii)](https://www.curseforge.com/minecraft/mc-mods/patchouli)
[Craftable Create Casings (Forge/Fabric) (by Lord_Of_Crumbs)](https://www.curseforge.com/minecraft/mc-mods/craftable-create-casings)
[Bookshelf (by DarkhaxDev)](https://www.curseforge.com/minecraft/mc-mods/bookshelf)
[Create Train Additions (by M_Productions)](https://www.curseforge.com/minecraft/mc-mods/create-train-additions)
[Create: Bronze Age (by Raeeeee)](https://www.curseforge.com/minecraft/mc-mods/create-bronze-age)
[Create: Dynamic Village (by sudolev)](https://www.curseforge.com/minecraft/mc-mods/dynamic-village)
[Create Stuff & Additions (by Furti_Two)](https://www.curseforge.com/minecraft/mc-mods/create-stuff-additions)
[Just Enough Items (JEI) (by mezz)](https://www.curseforge.com/minecraft/mc-mods/jei)
[Create Mechanical Extruder (by oierbravo_mc)](https://www.curseforge.com/minecraft/mc-mods/create-mechanical-extruder)
[Farmer's Delight (by vectorwing)](https://www.curseforge.com/minecraft/mc-mods/farmers-delight)
[Create: Steam 'n' Rails (by mattentosh)](https://www.curseforge.com/minecraft/mc-mods/create-steam-n-rails)
[Create Central Kitchen (by DragonsPlus)](https://www.curseforge.com/minecraft/mc-mods/create-central-kitchen)
[ModernFix (by embeddedt)](https://www.curseforge.com/minecraft/mc-mods/modernfix)
[Polymorph (Fabric/Forge/Quilt) (by TheIllusiveC4)](https://www.curseforge.com/minecraft/mc-mods/polymorph)
[Create Cafe (by Myst)](https://www.curseforge.com/minecraft/mc-mods/create-cafe)
[Create Slice & Dice (by possible_triangle)](https://www.curseforge.com/minecraft/mc-mods/slice-and-dice)
[Architectury API (Fabric/Forge/NeoForge) (by shedaniel)](https://www.curseforge.com/minecraft/mc-mods/architectury-api)
[Create: Tweaky Trinkets (by Riin1120)](https://www.curseforge.com/minecraft/mc-mods/create-tweaky-trinkets)
[KubeJS Create (by LatvianModder)](https://www.curseforge.com/minecraft/mc-mods/kubejs-create)
[Created Music Discs (by MomentariyModder)](https://www.curseforge.com/minecraft/mc-mods/created-music-discs-forge)
[Create: Frozen Flavors (by Chilllliii)](https://www.curseforge.com/minecraft/mc-mods/create-frozen-flavors)
[Freeze Create (by bagu_chan500)](https://www.curseforge.com/minecraft/mc-mods/freeze-create)
[Create Deco (by talrey)](https://www.curseforge.com/minecraft/mc-mods/create-deco)
[Pam's HarvestCraft 2 - Trees (by pamharvestcraft)](https://www.curseforge.com/minecraft/mc-mods/pams-harvestcraft-2-trees)
[Create:Automated Gems (by mattbv32)](https://www.curseforge.com/minecraft/mc-mods/create-automated-gems)
[Serene Seasons - Pam's HarvestCraft 2: Trees Compat (by Darkorg69)](https://www.curseforge.com/minecraft/mc-mods/serene-seasons-pams-harvestcraft-2-trees-compat)
[Create: Interiors (by sudolev)](https://www.curseforge.com/minecraft/mc-mods/interiors)
[Serene Seasons (by TheAdubbz)](https://www.curseforge.com/minecraft/mc-mods/serene-seasons)
[Create : Misc & Things (by to0pa_fr)](https://www.curseforge.com/minecraft/mc-mods/create-misc-and-things)

**Comment by pingju555** [comment]
> It appears you have Create Sifter. Try removing it.

Question solved.
