### ISSUE TITLE
problem mod pack

### ISSUE THREAD

**Issue by alexkrut2012** [KubeJS-Mods/KubeJS#783]
### Minecraft Version

1.20.1

### KubeJS Version

2001.6.4-build

### Rhino Version

2001.2.2-build

### Architectury Version

9.1.13-forge

### Forge/Fabric Version

forge 48.1.0

### Describe your issue

[startup.log](https://github.com/KubeJS-Mods/KubeJS/files/14195927/startup.log)
modpack ATM(all the mod) 9

### Crash report/logs

https://github.com/KubeJS-Mods/KubeJS/files/14195927/startup.log

**Comment by Donaldino7712** [comment]
this is an issue with the ATM pack itself and not KubeJS, you should report this to the ATM team instead

**Comment by ChiefArug** [comment]
As donald said this is an issue with the ATM modpack, or your installation of that modpack (try reinstall).
