### ISSUE TITLE
kubejs not working

### ISSUE THREAD

**Issue by Stobine** [KubeJS-Mods/KubeJS#787]
### Minecraft Version

1.18.2

### KubeJS Version

1802.5.5-build.569

### Rhino Version

1802.2.1-build.255

### Architectury Version

4.11.93

### Forge/Fabric Version

40.2.7

### Describe your issue

as I understand it, this is completely kubejs error because this is the only mod in the modpack. I just want to get the no crash version kubejs.

### Crash report/logs
https://paste.ee/p/2DOh7

**Comment by FooterMan15** [comment]
That log is completely unrelated to KubeJS.

**Comment by Stobine** [comment]
Im sorry https://paste.ee/p/2DOh7

**Comment by FooterMan15** [comment]
You have syntax error(s) in your Startup scripts. That is the cause of your crash.
For more information, consult the Startup log: `/instance/logs/kubejs/startup.txt`

**Comment by Stobine** [comment]
Thank you!
