### ISSUE TITLE
[Bug] Kubejs Stages are changeable without OP Permissions

### ISSUE THREAD

**Issue by TheonlyTazz** [KubeJS-Mods/KubeJS#826]
### Minecraft Version

1.18.2+

### KubeJS Version

1802.5.5-build.569

### Rhino Version

rhino-forge-1802.2.1-build.255

### Architectury Version

architectury-4.11.93

### Forge/Fabric Version

forge 40.2.10

### Describe your issue

Kubejs Stages are used quite often in Modpack Development to handle behind the scene mechanics (ex locking dimensions behind a certain stage)

![image](https://github.com/KubeJS-Mods/KubeJS/assets/3908847/fca27fda-f8e9-4d9b-96ba-34e388a5c129)

This seems unintended behaviour and one would assume that only OPs can add/remove stages.

Tested this on both 1.18.2 and 1.20.1 but i assume this is something that is on all versions

[FTB Modpack Issue](https://github.com/FTBTeam/FTB-Modpack-Issues/issues/4584)

**Comment by pietro-lopes** [comment]
This was fixed on latest MC versions, but not backported

* https://github.com/KubeJS-Mods/KubeJS/commit/b5af686742bc6628453bab5844cb3e2d076c926c
