### ISSUE TITLE
support for protected and private method and fields in java

### ISSUE THREAD

**Issue by gjmhmm8** [KubeJS-Mods/KubeJS#827]
### Describe the feature

support for protected and private method and fields in java

**Comment by pietro-lopes** [comment]
You are free to use reflection if you need

**Comment by gjmhmm8** [comment]
Why not make it the default option? Secondary reflection can lead to reduced efficiency.

**Comment by pietro-lopes** [comment]
you would be surprised with the amount of reflection Rhino does...

**Comment by gjmhmm8** [comment]
> you would be surprised with the amount of reflection Rhino does...

？

**Comment by pietro-lopes** [comment]
everything you write on scripts and make a call gets throw this reflection stuff

<https://github.com/KubeJS-Mods/Rhino/blob/bc5f50bf9e3f5279502d81ea93c45718c3694c24/common/src/main/java/dev/latvian/mods/rhino/MemberBox.java#L149>
