### ISSUE TITLE
Cannot access files in the kubejs/config directory

### ISSUE THREAD

**Issue by VariableVixen** [KubeJS-Mods/KubeJS#829]
### Minecraft Version

1.20.1

### KubeJS Version

2001.6.5-build.7

### Rhino Version

2001.2.2-build.18

### Architectury Version

9.2.14

### Forge/Fabric Version

Forge 47.2.21

### Describe your issue

The [`kubejs.bindings.UtilsWrapper` class](https://github.com/KubeJS-Mods/KubeJS/blob/d337e6dcb0bd377e5c408df20b4dfc7b704ed626/src/main/java/dev/latvian/mods/kubejs/bindings/UtilsWrapper.java) does not contain any bindings for the [`kubejs.utils.UtilJS.getPath()` method](https://github.com/KubeJS-Mods/KubeJS/blob/d337e6dcb0bd377e5c408df20b4dfc7b704ed626/src/main/java/dev/latvian/mods/kubejs/util/UtilsJS.java#L224), which makes it impossible to access any files whatsoever within the game directory. This makes it impossible to provide a configuration file for scripts, or to store persistent state information via [`JsonIO.readJson()`](https://github.com/KubeJS-Mods/KubeJS/blob/d337e6dcb0bd377e5c408df20b4dfc7b704ed626/src/main/java/dev/latvian/mods/kubejs/util/JsonIO.java#L105) and [`JsonIO.write()`](https://github.com/KubeJS-Mods/KubeJS/blob/d337e6dcb0bd377e5c408df20b4dfc7b704ed626/src/main/java/dev/latvian/mods/kubejs/util/JsonIO.java#L124), as those methods take _full_ paths and do not themselves resolve the given path to the game directory. Unless the full instance folder path is known in advance and hard-coded into the script, no configuration files can be read, and while it is _technically_ possible to hardcode paths to store persistent data, doing so would be both platform-dependent and heavily inadvisable.

As a result, the `JsonIO` class is of very limited use, since relative paths depend entirely on the working directory of the game process itself, which may not be guaranteed to be within the instance folder.

**Comment by pietro-lopes** [comment]
I think this is pretty much intended for security reasons.

**Comment by PrincessRTFM** [comment]
That makes no sense, because file access _is_ available, with arbitrary paths. The functionality that's _missing_ is resolving paths to within the game directory specifically. I could access files under AppData if I could guess the user's name, and while I can't read arbitrary file content (JSON only), I _could_ write some random JSON junk _over_ existing files.

**Comment by ChiefArug** [comment]
Having the working folder of the game be the instance folder is a basic assumption modders make in modded minecraft.
The last time the vanilla launcher broke that, almost every single modpack broke and it was quickly reverted.

**Comment by PrincessRTFM** [comment]
That makes sense, and definitely helps. This is still a security flaw though, because you can still overwrite paths outside the instance folder.

**Comment by pietro-lopes** [comment]
I think I'm not understanding the issue here, I tried this and works just fine

```js
StartupEvents.init(_ => {
  let config = JsonIO.readJson("kubejs/config/my_modpack_configs.json")
  if (config == null) {
    config = { someKey: "someValue" }
    JsonIO.write("kubejs/config/my_modpack_configs.json", config)
  }
  // do something with config
})
```

**Comment by MundM2007** [comment]
Ah i now realised what you mean. You think that you need the full Disk path to a specific file to ready Files. This is incorrect though, you only need to specify the path from the modpack instance directory

**Comment by ChiefArug** [comment]
> because you can still overwrite paths outside the instance folder.
Have you actually attempted that? Last I checked, KubeJS verifies that paths you write or read to with JsonIO or NBTIO are within the instance folder.

**Comment by PrincessRTFM** [comment]
I didn't see that in the source, but if so, then my apologies for the false alarm. I was trying to figure out how to handle persistent data storage, and the documentation I found said scripts could only read/write files in the `kubejs/config` directory but never explained _how_, so I started digging through the mod source. The [`kubejs.util.JsonIO.write()` method](https://github.com/KubeJS-Mods/KubeJS/blob/d337e6dcb0bd377e5c408df20b4dfc7b704ed626/src/main/java/dev/latvian/mods/kubejs/util/JsonIO.java#L124) has no checks, so if the path is checked, then I can only assume there's an interface layer I didn't see that handles that.

**Comment by ChiefArug** [comment]
The typewrapper for Path checks if it is allowed or not, so it checks everywhere you pass an object to something that requires Path (even if you pass Path itself).
https://github.com/KubeJS-Mods/KubeJS/blob/2001/common%2Fsrc%2Fmain%2Fjava%2Fdev%2Flatvian%2Fmods%2Fkubejs%2Futil%2FUtilsJS.java#L223

**Comment by PrincessRTFM** [comment]
Aha, that's what I'd missed!
