### ISSUE TITLE
Incorrect Version Support

### ISSUE THREAD

**Issue by mahjerion** [KubeJS-Mods/KubeJS#83]
The latest KubeJS [Fabric] builds say they support the versions below, but only work if Fabric is 1.16.5.
![image](https://user-images.githubusercontent.com/66142256/108543761-7dc97800-72b3-11eb-97c2-cae940380c2e.png)

**Comment by MaxNeedsSnacks** [comment]
Oh yeah, KubeJS only supports 1.16.4+ due to architectury-api on Fabric. I've just updated the version requirements overall
