### ISSUE TITLE
Wrong version, even if it is the same version

### ISSUE THREAD

**Issue by TheMacraft878** [KubeJS-Mods/KubeJS#832]
### Minecraft Version

1.20.1

### KubeJS Version

2001.6.5-build.7

### Rhino Version

unknown

### Architectury Version

unknown

### Forge/Fabric Version

forge 1.20.1 (Modrinth)

### Describe your issue

![Screenshot (46)](https://github.com/KubeJS-Mods/KubeJS/assets/169183565/9bbd3396-0857-406a-9306-474b53a85383)
The issue is, that I want to connect to a server with the Create 5 Modpack from Modrinth, I have the Java Files from Modrinth, but start the mods over the official launcher due to privacy concerns from my side with my Microsoft Account.
It is the same version, and even after getting the Java File from the server side the same problem occurs.

### Crash report/logs

Failed to synchornize registry data from server, closing connection

**Comment by MundM2007** [comment]
Copied from the discord:
Forge is not the smartest. The criteria it judges 'version differences' on is not just the version number, but also what registry objects (like items and blocks) exist.

This means that when you add custom things with KubeJS, Forge can sometimes show a version mismatch error with the exact same versions shown on both sides.

The simple solution for this is to make sure that the startup_scripts folder is the same on client and server.

**Comment by TheMacraft878** [comment]
Okay, thanks!

**Comment by TheMacraft878** [comment]
Do you know a way, of getting in contact with a creator of a modpack on Modrinth?

**Comment by MundM2007** [comment]
If they don't have a GitHub or discord or any other means of communication linked then i don't thinkg there's a way on modrinth, though i don't know really cause I haven't used modrinth . Maybe Check If they also have a curseforge.

**Comment by liopyu** [comment]
this error shows up if the startup scripts in the kubejs>startup_scripts folder are not the same on the client as it is on the server. Both server/client must have the same scripts otherwise there are registry issues which result in this error being the case
