### ISSUE TITLE
Enhancement: add a parameter for ‘replaceInput’

### ISSUE THREAD

**Issue by Yang-Borui** [KubeJS-Mods/KubeJS#84]
Could you please add a parameter about a tag for ‘replaceInput’.So only the recipes of the items or blocks in this tag will change.

**Comment by Spiker985** [comment]
You can already filter replaceInput, and replaceOutput with filters at the beginning of the method call.

https://github.com/KubeJS-Mods/KubeJS/blob/4b0a8e7f98dfaae5213408adcf7c647cb3189dbc/common/src/main/java/dev/latvian/kubejs/recipe/RecipeEventJS.java#L509
https://github.com/KubeJS-Mods/KubeJS/blob/4b0a8e7f98dfaae5213408adcf7c647cb3189dbc/common/src/main/java/dev/latvian/kubejs/recipe/RecipeEventJS.java#L546

**Comment by Yang-Borui** [comment]
Thank you.I'm sorry for causing you trouble

**Comment by Spiker985** [comment]
All is well. There is the discord server that might be able to answer these questions faster if you have them in the future. https://discord.gg/bPFfH6P

**Comment by Yang-Borui** [comment]
I'm a modpack author.I don't know how to use java.Would you please tell me how to filter replaceInput.
