### ISSUE TITLE
Modify item groups (creative inventory)

### ISSUE THREAD

**Issue by mageowl** [KubeJS-Mods/KubeJS#843]
### Describe the feature

It would be nice to be able to change or remove items from the creative inventory for modpacks.

### Additional info

Often two mods have conflicting features (both add an iron rod), and modpack developers can use KubeJS to remove these from recipes, tags, and JEI, but not from the creative inventory without a mod like [MoreCreativeTabs](https://modrinth.com/mod/morecreativetabs).

**Comment by ChiefArug** [comment]
This should already be possible using Forge's events via ForgeEvents, but a dedicated JS side event would be nice.

**Comment by MundM2007** [comment]
You can add and remove Items from the creative Inventory like so:
```js
StartupEvents.modifyCreativeTab('minecraft:redstone_blocks', event => {
	// Adds example item after redstone
	event.addAfter('minecraft:redstone', 'kubejs:example_item')
	// Removes redstone
	event.removeDisplay('minecraft:redstone');
})
```

**Comment by mageowl** [comment]
I didn't see that in the documentation. Thanks for the fix.
