### ISSUE TITLE
Script execution order

### ISSUE THREAD

**Issue by pjlasl** [KubeJS-Mods/KubeJS#86]
If I have several scripts, how do I make sure they execute in sequential order?

**Comment by HipHopHuman** [comment]
i think you can set a priority on the scripts with a comment at the top, like so:

script 1
```js
// priority: 0

/* your code here */
```

script 2
```js
// priority: 1

/* your code here */
```

I'm not sure if this actually works, I just am assuming it does because the default scripts that ship with KubeJS have these priority comments in them

**Comment by MaxNeedsSnacks** [comment]
What HipHopHuman said is correct, otherwise if no priorities are defined the order by default should be A-Z
