### ISSUE TITLE
[1.21] NeoForge Crash on Server Startup

### ISSUE THREAD

**Issue by NielsPilgaard** [KubeJS-Mods/KubeJS#860]
KubeJS is calling a clientside method on the server, it seems like.

https://gist.github.com/NielsPilgaard/dd81bb7ca6d28b989303488eb492b270

**Comment by Prunoideae** [comment]
It's ProbeJS loading a client class, this is fixed in https://www.curseforge.com/minecraft/mc-mods/probejs/files/5490917.
