### ISSUE TITLE
[Bug] Datapacks don't seem to load in.

### ISSUE THREAD

**Issue by Kevin-Marsh** [KubeJS-Mods/KubeJS#861]
### Minecraft Version

1.21

### KubeJS Version

kubejs-2100.7.0-build.63

### Rhino Version

rhino-2100.2.5-build.34

### Architectury Version

architectury-13.0.3-neoforge

### Forge/Fabric Version

Neoforge-21.0.42

### Describe your issue

I have added some datapacks into the /kubejs/data folder and they do not seem to be loading into the game. This is identical to a working instance in 1.20.  Is there a different place that this should be placed or any issues effecting datapacks loading?

**Comment by pietro-lopes** [comment]
Did you follow those changes on folder names?
https://gist.github.com/ChampionAsh5357/d895a7b1a34341e19c80870720f9880f#depluralizing-registry-and-tag-folders

**Comment by Kevin-Marsh** [comment]
These datapacks are for mod recipe changes rather than vanilla and function completely fine when loaded in with a different resourcepack loader such as the mod global packs. It is only Kubejs that fails to load them.

**Comment by liopyu** [comment]
is it a .zip folder you're loading in with it or are you doing kubejs>data>minecraft>...?

**Comment by Kevin-Marsh** [comment]
These are formatted kubejs>data>minecraft>. The repo in question is here:
 https://github.com/AllTheMods/ATM-10/tree/main/kubejs/data

**Comment by pietro-lopes** [comment]
Can confirm, and using the alternative below only works when you /reload
```js
ServerEvents.lowPriorityData(event => {
    let json = JsonIO.read("kubejs/data/occultism/modonomicon/multiblocks/summon_foliot.json")
    // console.log(json)
    event.addJson("occultism:modonomicon/multiblocks/summon_foliot", json);
})
```

**Comment by liopyu** [comment]
yeah i can also confirm using the datapack without the zip does not load

**Comment by pietro-lopes** [comment]
Also converting it to datapack zip (for this specific case) has no effects, doesn't work even with /reload
