### ISSUE TITLE
Fabric Client Crash when Creating World(loading server_scripts)

### ISSUE THREAD

**Issue by Ethanolgie** [KubeJS-Mods/KubeJS#862]
### Minecraft Version

1.19.2

### KubeJS Version

1902.6.1-build.370

### Rhino Version

1902.2.2-build.272

### Architectury Version

6.5.85

### Forge/Fabric Version

Fabric 0.14.22

### Describe your issue

This crash only appear on Client.When generating world,After loading server_scripts:*,A Error was shown that Error adding element: Value 2.14748365E9 outside of range [0.0:1.0]; Value 0 outside of range [1:16].Then Client crashed.
In server,this error will also appear,but it did not make server crash.

**Comment by ChiefArug** [comment]
Please provide logs

**Comment by Ethanolgie** [comment]
![image](https://github.com/KubeJS-Mods/KubeJS/assets/96416339/3a5688ed-3035-428e-bc83-d47dbc348d14)
I'm sorry to update log screenshot in comment

**Comment by ChiefArug** [comment]
A log file please, not screenshots.

**Comment by Ethanolgie** [comment]
[2024-07-02-2.log](https://github.com/user-attachments/files/16077532/2024-07-02-2.log)

**Comment by Ethanolgie** [comment]
[latest.log](https://github.com/user-attachments/files/16077538/latest.log)

**Comment by Ethanolgie** [comment]
This is a full log from launching to crashing when generating world

**Comment by ChiefArug** [comment]
`Caused by: java.lang.IllegalStateException: Unbound values in registry ResourceKey[minecraft:root / minecraft:worldgen/template_pool]: [minecells:portal]`
That just looks like an issue with minecells.

**Comment by Ethanolgie** [comment]
OK,I'll try solving

**Comment by Ethanolgie** [comment]
Thank you
I solved it after deleting kubejs\data\minecells folder.
I don't know this could be a bug of KubeJS or Minecells.
This is from modpack All of Fabric 6

**Comment by ChiefArug** [comment]
If you have a crash with a modpack **always** go to the modpack creator before mod authors please.

**Comment by Ethanolgie** [comment]
I'm so sorry
