### ISSUE TITLE
Kubejs Breaking Recipes

### ISSUE THREAD

**Issue by SaltSouls** [KubeJS-Mods/KubeJS#864]
### Minecraft Version

1.20.1

### KubeJS Version

2001.6.5-build.14

### Rhino Version

2001.2.2-build.18

### Architectury Version

9.2.14

### Forge/Fabric Version

47.3.4

### Describe your issue

Kubejs seems to be breaking recipes from mods that work just fine without it installed. I imagine that this isn't intended behavior. This causes several problems as it require pack creators to have to go in after the fact and recreate the recipes Kubejs breaks in order for the mods they have installed to function as they should. I don't know what is causing the problem as I'm only able to see what recipes are breaking, but if it might be something related to a recipe mixin if Kubejs is changing either how recipes are registered or read.

### Crash report/logs

https://gist.github.com/SaltSouls/71a83c33d3f02273e8ea447bddc978ea

**Comment by ChiefArug** [comment]
Can you provide examples of mods that break and a specific recipe or two of them?

**Comment by SaltSouls** [comment]
The logs towards the bottom have several recipes they mention. Two mods specifically mentioned are `mynethersdelight` and `moredelight`. More delight has the largest amount of recipes that are breaking because of Kubejs. Basically all of their food recipes don't work.

**Comment by ChiefArug** [comment]
Can you send a log without KubeJS?
Those errors look like errors thrown by the mod's recipe parser, and KJS is just catching and logging them.

**Comment by SaltSouls** [comment]
Sure, here you go.
https://gist.github.com/SaltSouls/c88185ed57aa698e0706775e8ebbef31

**Comment by pietro-lopes** [comment]
What happens if you disable the Delightful kubejs addon?

**Comment by SaltSouls** [comment]
Hmmm... That does seem to fix the problem with FD recipes. I'll link this issue to their page so they can take a look into it.

**Comment by SaltSouls** [comment]
I'll close the issue here.
