### ISSUE TITLE
Server crash after restart

### ISSUE THREAD

**Issue by BazZziliuS** [KubeJS-Mods/KubeJS#866]
### Minecraft Version

1.20.1

### KubeJS Version

kubejs-forge-2001.6.5-build.5

### Rhino Version

rhino-forge-2001.2.2-build.18

### Architectury Version

architectury-9.2.14-forge

### Forge/Fabric Version

47.3.1

### Describe your issue

I noticed that the server crashes after the restart
Let me know if you need more information from me.

### Crash report/logs

https://paste.fuix.net/kfXHIdn

**Comment by BazZziliuS** [comment]
> The error looks to be coming from a server tick happening after the server has begun (and mostly finished) its shutdown. Can you share the crash report on another site such as https://gist.github.com as that site seems to have stripped some metadata about which mods are mixining into certain classes, which will be useful for further debugging. Also the full log file would be nice.

crash-log: https://gist.github.com/BazZziliuS/ca64be54e7ecc4bc99d273de9f6027b2
latest: https://gist.github.com/BazZziliuS/9aa32cd3fadda7b8c7d6534e0610422f

**Comment by ChiefArug** [comment]
> Mohist
That is probably your problem. Hybrid server software like Mohist cause tons of issues.
