### ISSUE TITLE
Here is a crash report that is casued by KubeJS

### ISSUE THREAD

**Issue by Admiral-Sebastian** [KubeJS-Mods/KubeJS#87]
https://paste.gg/p/anonymous/40ef2429b7fc482a828ff4237bb32061

**Comment by TheRanker** [comment]
i have about 5 more reports with this same crash.  works single player.. but tick error soon as enter work in multiplayer

**Comment by AderMeepo** [comment]
same problem( 
https://pastebin.com/CFy6mEsu

**Comment by MaxNeedsSnacks** [comment]
See #101, this is caused by Dynamic Surroundings.
