### ISSUE TITLE
Import java class, dev.latvian.mods.rhino.NativeJavaClass cannot be cast to dev.latvian.mods.rhino.NativeJavaPackage

### ISSUE THREAD

**Issue by Tankonyako** [KubeJS-Mods/KubeJS#88]
Error log: https://pastebin.com/rV1At2rg

Crashing when using Packages or import direclty.
![image](https://user-images.githubusercontent.com/48120579/110087069-d876cf80-7d9b-11eb-8187-6968993d1693.png)

How i can use java class in js?

**Comment by LatvianModder** [comment]
```js
var JMath = java.lang.Math
console.info(JMath.PI)
```

**Comment by Tankonyako** [comment]
> I think the class has to be defined on its own, then you can use members
> 
> ```js
> var JMath = java.lang.Math
> console.info(JMath.PI)
> ```

This is not working, im tried too much examples from Rhino. This is bug without KubeJs.

**Comment by Tankonyako** [comment]
I think you can add method for class define to utils or make like API like in Nashorn ``Java.type("class")``

**Comment by LatvianModder** [comment]
I assume you're using *latest* version of KubeJS 1.16, because this was only added recently

**Comment by Tankonyako** [comment]
> I assume you're using _latest_ version of KubeJS 1.16, because this was only added recently

yes.
in kubejs-1605.3.6-build.170 is working?

**Comment by Tankonyako** [comment]
Hello, any fixes?

**Comment by LatvianModder** [comment]
Ok, I get that error too now. Weird, that didn't happen before. I'll look into it

**Comment by LatvianModder** [comment]
Found the issue, need to figure out how to fix. its something to do with Context#setClassShutter, it seems to block too much

**Comment by LatvianModder** [comment]
![image](https://user-images.githubusercontent.com/3844385/110376184-91b6fd00-805b-11eb-8693-fb1e8f605517.png)

Removing class shutter "fixes" it but its probably something simple
