### ISSUE TITLE
Recipe not remove

### ISSUE THREAD

**Issue by Alkasym** [KubeJS-Mods/KubeJS#89]
Hi,

We have an issue with the removed id, the solar panel from solar flux reborn aren't removed with the following code : 

e.remove({ id: 'solarflux:1/mirror' })
e.remove({ output: 'solarflux:sp_1' })
e.remove({ id: 'solarflux:10/sp_2' })
e.remove({ id: 'solarflux:11/sp_3' })
e.remove({ id: 'solarflux:12/sp_4' })
e.remove({ id: 'solarflux:13/sp_5' })
e.remove({ id: 'solarflux:14/sp_6' })
e.remove({ id: 'solarflux:15/sp_7' })
e.remove({ id: 'solarflux:16/sp_8' })

Forge : 36.0.46
KubeJS : 1605.3.6-build.172
Solarflux : 16.2.3

**Comment by Alkasym** [comment]
Same issue with the seed added by mystical customization.

e.remove({ id: "mysticalagriculture:alfsteel_seeds_infusion" }) to example.

Mystical agriculture : 4.1.5
Mystical agradditions : 4.1.4
Mystical customization : 2.1.2

**Comment by MaxNeedsSnacks** [comment]
SolarFlux does some *quite* weird stuff to add recipes at runtime, which we cannot fix on our end, so they'll have to add compatibility themselves. As for Mystical Customisation, I'm assuming they also circumvent the RecipeManager somehow, which is not a good idea as that is ***supposed*** to be the *only* source of truth when it comes to recipes. In any case, they'd also have to add compatibility to ensure recipe modifications could still work with KubeJS
