### ISSUE TITLE
Errors when using MoreDelight

### ISSUE THREAD

**Issue by VendoAU** [KubeJS-Mods/KubeJS#890]
### Minecraft Version

1.21.1

### KubeJS Version

2101.7.0-build.145

### Rhino Version

2100.2.5-build.48

### Architectury Version

13.0.6

### Forge/Fabric Version

21.1.22

### Describe your issue

Initially KubeJS loads fine with no errors, but after any custom recipe is added there will be errors.

Here's the `server_scripts/main.js` that I used:
```js
ServerEvents.recipes(event => {
    event.shapeless("minecraft:diamond", ["minecraft:dirt"]);
});
```

### Crash report/logs

https://mclo.gs/KxtFAzy

**Comment by Donaldino7712** [comment]
These are errors in MoreDelight which KubeJS simply catches and displays, this is not a KJS bug

**Comment by ChiefArug** [comment]
Probably duplicate of #878, where an empty tag is being used as an ingredient and the recipe is not being stopped from loading using a condition.

**Comment by VendoAU** [comment]
I figured out it's because the food category is only supposed to be used for smelting and smoking recipes
