### ISSUE TITLE
KubeJS on new Fabric version?

### ISSUE THREAD

**Issue by N1zyx3** [KubeJS-Mods/KubeJS#891]
### Describe the feature

1.21 and more

**Comment by ChiefArug** [comment]
Fabric and Forge have been dropped in favor of NeoForge.

It is possible to load most Fabric mods on NeoForge through the third party mod Sinytra Connector if there are some you particularly want to keep using that are not Neo-native.

**Comment by N1zard** [comment]
> Fabric and Forge have been dropped in favor of NeoForge.
> 
> It is possible to load most Fabric mods on NeoForge through the third party mod Sinytra Connector if there are some you particularly want to keep using that are not Neo-native.

And those who are only interested in Fabric, Forge the author doesn't care about? Do I understand correctly that the development on these modloaders is finished?

**Comment by DerCommander323** [comment]
Correct. They were already only a small portion of users, and with many Fabric and Forge modders moving to NeoForge the effort of supporting multiple loaders is simply not worth it.

**Comment by ChiefArug** [comment]
If someone personally wants to maintain KubeJS on Fabric then Lat is happy to give them access to the KubeJS projects to upload files, but no one has expressed a desire to do that so far.
