### ISSUE TITLE
error with DensityFunctionCompiler from c2me

### ISSUE THREAD

**Issue by coco875** [KubeJS-Mods/KubeJS#915]
### Minecraft Version

1.21.1

### KubeJS Version

2101.7.1-build.181.jar

### Rhino Version

2101.2.5-build.54

### Architectury Version

none

### Forge/Fabric Version

Neoforge 21.1.72

### Describe your issue

With c2me with `useDensityFunctionCompiler` enable, and with bumblezone (and with connector) when I try to enter in the dimention it freeze and don't load the dimension with a bunch of spam of error.

### Crash report/logs

https://pastebin.com/vgNgF3sc

**Comment by pietro-lopes** [comment]
This error is related to the Scanner that I implemented a while ago and for some reason looks like the resource location is null, I would need to debug it.
Do you mind sharing an instance export? I'm not familiar with connector/fabric stuff

**Comment by coco875** [comment]
ok I will do it

**Comment by coco875** [comment]
I use curseforge for the modpack
[isolate crash.zip](https://github.com/user-attachments/files/17446636/isolate.crash.zip)

**Comment by pietro-lopes** [comment]
I'm not able to reproduce, game works just fine

https://mclo.gs/Zaas65G

**Comment by coco875** [comment]
yeah the crash only happen when I try to enter in the bumblezone dimension and don't forget to enable `useDensityFunctionCompiler` and disable `optimizeAsyncChunkRequest` in c2me.toml (`optimizeAsyncChunkRequest` need to be disable for bumblezone to work correctly with c2me)

**Comment by pietro-lopes** [comment]
> yeah the error only happen when I try to enter in the bumblezone dimension and don't forget to enable `useDensityFunctionCompiler` and disable `optimizeAsyncChunkRequest` in c2me.toml (`optimizeAsyncChunkRequest` need to be disable for bumblezone to work correctly with c2me)

Those options were preserved in your export.
I submitted a PR to fix this issue.

**Comment by coco875** [comment]
ok great will see it in the next release (after I have also other issue with some network disconnect in random configuration in solo after generate the world but can't find the minimal set of mod to reproduce it)
