### ISSUE TITLE
Doesn't generate files on install

### ISSUE THREAD

**Issue by 8kilometers** [KubeJS-Mods/KubeJS#92]
I installed kubejs and it generated the folder when I loaded Minecraft, but it only has the resources folder and it's empty. I have no example scripts or anything.

(Apologies if this is a stupid mistake-this is my first time using this mod.)

**Comment by MaxNeedsSnacks** [comment]
What kind of OS are you using and what permissions do you have for the folder Minecraft is in? Either way, you should be fine just creating the files manually, even if it may be a bit convoluted

**Comment by MaxNeedsSnacks** [comment]
Closing this since there hasn't been any activity on it for about a month. Feel free to reopen if this still affects you ^^

**Comment by Bruniczek2000** [comment]
Hey, uhm i have the same problem as you

I'm running Debian 12 Bookworm with xfce

I have given permissions to the KubeJS folder recursively

I even reinstalled Minecraft. Im using ATLauncher, but i'll switch to PrismLauncher (the new version of multi mc) and get back to you

For now, only the resources folder appears, no other and the folders that where supposed to be there when i created them myself and restarted it did nothing

Im hoping you can help me

Bye for now
