### ISSUE TITLE
Removing Oregen Doesn´t Work

### ISSUE THREAD

**Issue by McJJsHD** [KubeJS-Mods/KubeJS#97]
For a new Modpack i wanted to remove the oregen of certain mods, to not have for example 5 different copper ores. I tried to use this code.

```
onEvent('worldgen.remove', event => {
    event.removeOres(ores => {
      ores.setBlocks(['create:copper_ore', 'iceandfire:copper_ore', 'thermal:copper_ore', 'immersiveengineering:ore_copper', 'thermal:tin_ore','iceandfire:silver_ore','thermal:silver_ore','immersiveengineering:ore_silver','immersiveengineering:ore_nickel','immersiveengineering:ore_uranium','immersiveengineering:ore_lead'])
    })

    console.log("Removing oregen....")
})



onEvent('worldgen.remove', event => {
    event.removeOres(ores => {
      ores.blocks = [ 'minecraft:coal_ore', 'minecraft:iron_ore' ] // Removes coal and iron ore
  
    })

})
```

I am not really sure if the issue lies with KubeJs because certain ores don´t generate.

**Comment by MaxNeedsSnacks** [comment]
Since the feature name is just `immersiveengineering:copper`, can you try with that? Just wanna see things

**Comment by McJJsHD** [comment]
It still doesn´t change if i have done everything right.
```
onEvent('worldgen.remove', event => {
    event.removeOres(ores => {
      ores.blocks = [ 'minecraft:coal_ore', 'minecraft:iron_ore', 'immersiveengineering:copper' ]
  
    })

})
```

**Comment by McJJsHD** [comment]
I did some more Testing. I think the issue lies with immersive engineering. Every other ore i don`t want to generate doesn`t generate. Where the issue directly is? idk.

**Comment by McJJsHD** [comment]
> Since the feature name is just `immersiveengineering:copper`, can you try with that? Just wanna see things

I tried, it didn´t work

**Comment by MaxNeedsSnacks** [comment]
Fair enough. If it works with **all** other features from other mods though, i‘m pretry certain that this may be on IE‘s end

**Comment by McJJsHD** [comment]
I just disabled IE´s oregen in config. I think this can be closed.
