### ISSUE TITLE
Have useAction on Itembuilder

### ISSUE THREAD

**Issue by maxine-red** [KubeJS-Mods/KubeJS#98]
Hello, I try to make drinkable items for my pack.

I added food values, etc to it, but I'd like to use the "drink" action, instead of the normal eat action. (As eating glass bottles, doesn't make much sense and hurts a lot)

I can't see a way to do it though, If there is a way, let me know please. Otherwise I'd like to change the use action on the itemvuilder.

Thank you in advance!

**Comment by MaxNeedsSnacks** [comment]
I don't think you can make an item drinkable as of yet, but it's definitely planned (albeit low-priority)

**Comment by MaxNeedsSnacks** [comment]
This has been implemented a while ago in #331, but GitHub never closed the issue for some reason
