### ISSUE TITLE
forin loop syntax error

### ISSUE THREAD

**Issue by SwanX1** [KubeJS-Mods/KubeJS#99]
Not sure if this is a KubeJS error, or a Rhino error, but running the following code (or something similar) doesn't work:
```javascript
let testobject = {
  a: 'bc',
  foo: 'bar'
};
for (const key in testobject) {
  console.log(key);
}
```
throws a syntax error on line 5, however if the `const` is replaced with `var`, it works fine.

**Comment by 6XAM** [comment]
Yes, this is a javascripting error (your code is wrong/invalid)

Think about it; if key was constant, how could it change for each element of testobject?

**Comment by 6XAM** [comment]
Not supported by Rhino https://mozilla.github.io/rhino/compat/engines.html#ES2015-bindings-const-for-in-loop-iteration-scope (see this page for various compat issues)
